### ISSUE TITLE
Hot deploy of view controllers doesn't work

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1007]
Studio correctly compiles and copies classes to `build/classes`, but doesn't create any trigger file. After implementing a bean method in the framework, file an issue for Studio to create the trigger file with appropriate name.

## Solution

The `io.jmix.flowui.view.ViewRegistry#loadViewClass` method is added in order to be invoked by `TriggerFilesProcessor`

**Comment by knstvk** [comment]
After implementing the following method in ViewRegistry:
```java
public void loadViewClass(String className) {
    Class screenClass = classManager.loadClass(className);

    ViewControllerMeta controllerMeta = new ViewControllerMeta(metadataReaderFactory, screenClass);

    ViewControllerDefinition uiControllerDefinition = new ViewControllerDefinition(
            controllerMeta.getId(), controllerMeta.getControllerClass(), controllerMeta.getResource());

    ViewControllersConfiguration controllersConfiguration =
            new ViewControllersConfiguration(applicationContext, metadataReaderFactory);

    controllersConfiguration.setExplicitDefinitions(Collections.singletonList(uiControllerDefinition));

    configurations.add(controllersConfiguration);

    reset();
}
```

I get an exception at runtime when navigating to the view with reloaded class:

```
com.vaadin.flow.router.NotFoundException: No route found for the given navigation target 'com.company.onboarding.view.user.UserDetailView' and parameters '{id=7sgmdt3se3vfcbxtryb2h4t9mt}'
	at com.vaadin.flow.router.RouteConfiguration.getUrl(RouteConfiguration.java:515)
	at io.jmix.flowui.view.navigation.ViewNavigationSupport.navigate(ViewNavigationSupport.java:34)
	at io.jmix.flowui.view.navigation.AbstractNavigationProcessor.processNavigation(AbstractNavigationProcessor.java:31)
	at io.jmix.flowui.view.navigation.ViewNavigator.navigate(ViewNavigator.java:77)
	at io.jmix.flowui.action.list.EditAction.navigate(EditAction.java:316)
	at io.jmix.flowui.action.list.EditAction.execute(EditAction.java:299)
	at io.jmix.flowui.action.list.ListDataComponentAction.actionPerform(ListDataComponentAction.java:147)
	at io.jmix.flowui.kit.component.button.JmixButtonActionSupport.onButtonClick(JmixButtonActionSupport.java:177)
...
```

Perhaps something needs to be done with `RouteConfiguration`.

**Comment by knstvk** [comment]
Doesn't work:
```
Hot deploy: param, param, param-detail-view.xml, ParamDetailView.java [680 ms]
    param-detail-view.xml -> .jmix/conf
Compiled files:
    com/company/demo/view/param/ParamDetailView.java
2022-09-25 14:49:20.629  INFO 85008 --- [         core-2] io.jmix.core.impl.TriggerFilesProcessor  : Calling io.jmix.flowui.view.ViewRegistry#loadViewClass(com.company.demo.view.param.ParamDetailView)
2022-09-25 14:49:20.632 ERROR 85008 --- [         core-2] io.jmix.core.impl.TriggerFilesProcessor  : Trigger file /Users/knst/work/tmp/2022-09-25-flowui-composition/.jmix/temp/triggers/io.jmix.flowui.view.ViewRegistry#loadViewClass(com.company.demo.view.param.ParamDetailView) processing error: {}

java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at io.jmix.core.impl.TriggerFilesProcessor.processFile(TriggerFilesProcessor.java:139) ~[jmix-core-1.4.999-SNAPSHOT.jar:na]
	at io.jmix.core.impl.TriggerFilesProcessor.process(TriggerFilesProcessor.java:90) ~[jmix-core-1.4.999-SNAPSHOT.jar:na]
	at io.jmix.core.impl.TriggerFileProcessorScheduleConfigurer.lambda$onContextRefreshedEvent$0(TriggerFileProcessorScheduleConfigurer.java:46) ~[jmix-core-1.4.999-SNAPSHOT.jar:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.22.jar:5.3.22]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.lang.NullPointerException: null
	at com.vaadin.flow.router.RouteConfiguration.getApplicationRegistry(RouteConfiguration.java:526) ~[flow-server-23.1.6.jar:23.1.6]
	at com.vaadin.flow.router.RouteConfiguration.forApplicationScope(RouteConfiguration.java:74) ~[flow-server-23.1.6.jar:23.1.6]
	at io.jmix.flowui.view.ViewRegistry.registerRoute(ViewRegistry.java:450) ~[jmix-flowui-1.4.999-SNAPSHOT.jar:na]
	at io.jmix.flowui.view.ViewRegistry.loadViewClass(ViewRegistry.java:413) ~[jmix-flowui-1.4.999-SNAPSHOT.jar:na]
	... 14 common frames omitted
```
