### ISSUE TITLE
Entity inspector fails on exporting entities with embedded attribute

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1012]
Jmix version: 1.3.3

1. Create an entity with embedded attribute, e.g. Customer with Address
2. Create an instance of this entity
3. Open this entity in the Entity Inspector screen and click the "Export as JSON" button

AR: an exception:

```
java.lang.IllegalStateException: unknown property type
	at io.jmix.datatoolsui.screen.entityinspector.EntityInspectorBrowser.createEntityExportPlan(EntityInspectorBrowser.java:557) ~[jmix-datatools-ui-1.3.3.jar:na]
	at io.jmix.datatoolsui.screen.entityinspector.EntityInspectorBrowser$ExportAction.actionPerform(EntityInspectorBrowser.java:711) ~[jmix-datatools-ui-1.3.3.jar:na]
	at io.jmix.ui.component.impl.PopupButtonImpl.lambda$setPopupButtonAction$1(PopupButtonImpl.java:321) ~[jmix-ui-1.3.3.jar:na]
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77) ~[jmix-ui-1.3.3.jar:na]
	at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-8.14.1-2-jmix.jar:8.14.1-2-jmix]
```

See [forum topic](https://forum.cuba-platform.com/t/jmix-entity-inspector-doesn-t-support-export-entities-with-embedded-entities/16514)

Sample project: [exportembedded.zip](https://github.com/jmix-framework/jmix/files/9591218/exportembedded.zip)

Also, we should check how it works in flowui module and in CUBA. The issue must be fixed there as well.

**QA Notes:**
Please, check export of entities with complicated embedded attributes too.

**Comment by lovtsovaik** [comment]
Export works without error for backoffice UI in Jmix.
But attributes from embeddable entity is not exist in UI and Excel. They exists only in JSON
