### ISSUE TITLE
IllegalStateException: Editor of class [...] cannot be open with mode EDIT, entity is not set

### ISSUE THREAD

**Issue by Sanysvo** [jmix-framework/jmix#1013]
Hello, I use this EntityPicker's action : `<action id="openComposition" type="entity_openComposition">`. But I get this error then try click on Button in the editor screen: cannot be open with mode EDIT, entity is not set;

Why? I have OneToOne composition for it entities.

Full stack trace:
`Caused by: java.lang.IllegalStateException: Editor of class com.company.gameserver.entity.common.Money cannot be open with mode EDIT, entity is not set
	at io.jmix.ui.builder.EditorBuilderProcessor.buildEditor(EditorBuilderProcessor.java:84) ~[jmix-ui-1.3.3.jar:na]
	at io.jmix.ui.builder.EditorBuilder.build(EditorBuilder.java:355) ~[jmix-ui-1.3.3.jar:na]
	at io.jmix.ui.action.entitypicker.EntityOpenAction.execute(EntityOpenAction.java:339) ~[jmix-ui-1.3.3.jar:na]
	at io.jmix.ui.action.entitypicker.EntityOpenAction.actionPerform(EntityOpenAction.java:296) ~[jmix-ui-1.3.3.jar:na]
	at io.jmix.ui.component.impl.ValuePickerImpl.lambda$setupButtonAction$0(ValuePickerImpl.java:231) ~[jmix-ui-1.3.3.jar:na]
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77) ~[jmix-ui-1.3.3.jar:na]
	at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-8.14.1-2-jmix.jar:8.14.1-2-jmix]
	... 95 common frames omitted`

**Comment by knstvk** [comment]
Please provide a small test project where the problem is reproduced.
