### ISSUE TITLE
NullPointerException in DynamicAttributesState

### ISSUE THREAD

**Issue by daring2** [jmix-framework/jmix#1036]
Method `DynamicAttributesState#getChanges` throws NullPointerException in some cases.

Stacktrace:
```
Caused by: java.lang.NullPointerException: Cannot invoke "io.jmix.dynattr.DynamicAttributes.getChanges()" because "this.dynamicModel" is null
	at io.jmix.dynattr.DynamicAttributesState.getChanges(DynamicAttributesState.java:99) ~[jmix-dynattr-1.3.3.jar:na]
	at io.jmix.data.impl.BaseAttributeChangesProvider.buildExtraChanges(BaseAttributeChangesProvider.java:185) ~[jmix-data-1.3.3.jar:na]
	at io.jmix.data.impl.BaseAttributeChangesProvider.getAttributeChanges(BaseAttributeChangesProvider.java:78) ~[jmix-data-1.3.3.jar:na]
	at io.jmix.eclipselink.impl.EclipselinkPersistenceSupport$OnSaveEntityVisitor.visit(EclipselinkPersistenceSupport.java:659) ~[jmix-eclipselink-1.3.3.jar:na]
	at io.jmix.eclipselink.impl.EclipselinkPersistenceSupport.beforeStore(EclipselinkPersistenceSupport.java:282) ~[jmix-eclipselink-1.3.3.jar:na]
	at io.jmix.eclipselink.impl.EclipselinkPersistenceSupport.traverseEntities(EclipselinkPersistenceSupport.java:269) ~[jmix-eclipselink-1.3.3.jar:na]
	at io.jmix.eclipselink.impl.EclipselinkPersistenceSupport.processFlush(EclipselinkPersistenceSupport.java:234) ~[jmix-eclipselink-1.3.3.jar:na]
	at io.jmix.eclipselink.impl.JmixEntityManager.flush(JmixEntityManager.java:191) ~[jmix-eclipselink-1.3.3.jar:na]
...
```

**Comment by KremnevDmitry** [comment]
@daring2, could you please provide any test project or steps for reproduction?
