### ISSUE TITLE
DTO entity parameter should not be reloaded on report execution

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1133]
1. Create new DTO entity
1. Create new report
1. Pass the DTO entity as "Entity" parameter to the report
1. Create dataset with "Entity" type
1. Select entity attributes that must be loaded
1. Run the report

![Screenshot 2022-10-24 at 18 21 13](https://user-images.githubusercontent.com/7888486/197549924-c01c579b-cce1-4b20-ade6-037d37f4a37d.png)

AR: DTO will be reloaded from the database

```
com.haulmont.yarg.exception.DataLoadingException: An error occurred while loading data for band [Root] and query [null].
	at com.haulmont.yarg.reporting.extraction.controller.DefaultExtractionController.getQueryData(DefaultExtractionController.java:214) ~[yarg-2.2.18.jar:na]
	at com.haulmont.yarg.reporting.extraction.controller.DefaultExtractionController.getQueriesResult(DefaultExtractionController.java:151) ~[yarg-2.2.18.jar:na]
	at com.haulmont.yarg.reporting.extraction.controller.DefaultExtractionController.getQueriesResult(DefaultExtractionController.java:144) ~[yarg-2.2.18.jar:na]
	at com.haulmont.yarg.reporting.extraction.controller.DefaultExtractionController.extractData(DefaultExtractionController.java:76) ~[yarg-2.2.18.jar:na]
	at com.haulmont.yarg.reporting.DataExtractorImpl.extractData(DataExtractorImpl.java:61) ~[yarg-2.2.18.jar:na]
	at com.haulmont.yarg.reporting.Reporting.loadBandData(Reporting.java:144) ~[yarg-2.2.18.jar:na]
	at com.haulmont.yarg.reporting.Reporting.runReport(Reporting.java:92) ~[yarg-2.2.18.jar:na]
	at com.haulmont.yarg.reporting.Reporting.runReport(Reporting.java:116) ~[yarg-2.2.18.jar:na]
	at io.jmix.reports.runner.impl.ReportRunnerImpl.createReportDocumentInternal(ReportRunnerImpl.java:142) ~[jmix-reports-1.3.5.jar:na]
	at io.jmix.reports.runner.impl.ReportRunnerImpl.run(ReportRunnerImpl.java:90) ~[jmix-reports-1.3.5.jar:na]
	at io.jmix.reportsui.runner.impl.UiReportRunnerImpl.runAndShow(UiReportRunnerImpl.java:97) ~[jmix-reports-ui-1.3.5.jar:na]
	at io.jmix.reportsui.runner.FluentUiReportRunner.runAndShow(FluentUiReportRunner.java:185) ~[jmix-reports-ui-1.3.5.jar:na]
	at io.jmix.reportsui.screen.report.run.InputParametersDialog.onPrintReportButtonClick(InputParametersDialog.java:136) ~[jmix-reports-ui-1.3.5.jar:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-1.3.5.jar:na]
	at io.jmix.ui.component.impl.AbstractComponent.publish(AbstractComponent.java:85) ~[jmix-ui-1.3.5.jar:na]
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:78) ~[jmix-ui-1.3.5.jar:na]
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77) ~[jmix-ui-1.3.5.jar:na]
	at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-8.14.3-0-jmix.jar:8.14.3-0-jmix]

...

Caused by: java.lang.IllegalStateException: No results
	at io.jmix.core.FluentLoader$ById.one(FluentLoader.java:216) ~[jmix-core-1.3.5.jar:na]
	at io.jmix.reports.libintegration.AbstractEntityDataLoader.reloadEntity(AbstractEntityDataLoader.java:61) ~[jmix-reports-1.3.5.jar:na]
	at io.jmix.reports.libintegration.AbstractEntityDataLoader.reloadEntityByDataSetFetchPlan(AbstractEntityDataLoader.java:48) ~[jmix-reports-1.3.5.jar:na]
	at io.jmix.reports.libintegration.SingleEntityDataLoader.loadData(SingleEntityDataLoader.java:52) ~[jmix-reports-1.3.5.jar:na]
	at com.haulmont.yarg.reporting.extraction.controller.DefaultExtractionController.lambda$getQueryData$1(DefaultExtractionController.java:206) ~[yarg-2.2.18.jar:na]
	at com.haulmont.yarg.reporting.extraction.DefaultPreprocessorFactory.lambda$new$0(DefaultPreprocessorFactory.java:35) ~[yarg-2.2.18.jar:na]
	at com.haulmont.yarg.reporting.extraction.controller.DefaultExtractionController.getQueryData(DefaultExtractionController.java:204) ~[yarg-2.2.18.jar:na]
	... 111 common frames omitted
```

There are several possible solutions:
* we may not reload DTO entity at all
* there must be a setting in the report editor that will forbid entity reloading at all (even for JPA entity)
* we can not to reload DTO entity or JPA entity that is already matches selected fetch plan

Project: [report-param-reload.zip](https://github.com/jmix-framework/jmix/files/9852443/report-param-reload.zip)
Report: [report1 (2).zip](https://github.com/jmix-framework/jmix/files/9852444/report1.2.zip)

**Comment by Gavrilov-Ivan** [comment]
Reload is performed only if provided object is a JPA entity and not all of its properties are loaded according to expected fetch plan.
