### ISSUE TITLE
Can't run project with compileWidgets task

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#1137]
**Environment**
*OS: Windows 10
Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4729-222
IntelliJ version: IntelliJ IDEA 2022.2.3 (Ultimate Edition)*

**Steps**
* Create new project
* Add charts or maps addon
* Run project

**AR:** Project doesn't run.
```
> Task :compileWidgets FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: org/gradle/internal/classpath/Instrumented
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:2388)
	at org.apache.commons.io.FileUtils.readLines(FileUtils.java:2561)
	at io.jmix.gradle.ClassPathCommandLine.readAndRemoveFile(ClassPathCommandLine.java:82)
	at io.jmix.gradle.ClassPathCommandLine.main(ClassPathCommandLine.java:37)
Caused by: java.lang.ClassNotFoundException: org.gradle.internal.classpath.Instrumented
Caused by: java.lang.ClassNotFoundException: org.gradle.internal.classpath.Instrumented

	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 4 more

Execution failed for task ':compileWidgets'.
> Process 'command 'C:\Program Files\Java\jdk-11.0.13\bin\java.exe'' finished with non-zero exit value 1
```
Simple test project: [testcharts.zip](https://github.com/jmix-framework/jmix/files/9859656/testcharts.zip)

**Note:**
Open `gradle-wrapper.properties` file and replace version from 7.5.1 to 7.4.2 in `distributionUrl` property.
Then the project runs successfully

*Can't reproduce on Mac OS*

**Comment by Flaurite** [comment]
Bug occurs only in Windows OS. `ClassPathCommandLine` class is used to short the command generating GWT widgetSet in Windows OS.
In our case, we use `javaexec()` to perform `ClassPathCommandLine` main method with specific args and JVM args. We use the same class path that is provided by plugin build script. It seems somehow `Gradle` enhance class path dependencies and in the not Gradle plugin related context it produces the exception that `org/gradle/internal/classpath/Instrumented` not found.

The solution is to use separated Configuration with the correct dependencies and provide it to the `javaexec()` class path.
See discussion in: https://github.com/gradle/gradle/issues/14727

**Comment by Flaurite** [comment]
It was decided to do not use the separated configuration, but avoiding using `ClassPathCommandLine` and directly invoking the GWT compiler.

**Comment by lovtsovaik** [comment]
Tested with plugin version '1.4.0-M6'
(on Windows)
