### ISSUE TITLE
Studio 1.4.0 broken with IntelliJ on Windows and project in WSL2

### ISSUE THREAD

**Issue by tkonsta** [jmix-framework/jmix#1157]
With version 1.4.0 of studio installed, working on the windows subsystem for linux v2 (WSL2) is not possible anymore. 

Already without any user action IntelliJ shows an error `java.lang.IllegalArgumentException: 'other' is different type of Path` (full stacktrace see below).

Trying to start the jmix application the same error appears again and from then on the "start" button in IntelliJ is disabled.

Uninstalling studio version 1.4.0 and reinstalling 1.3.9 fixes the issue.

Setup:

- Windows 11
- WSL2 with Ubuntu 22.04
- IntelliJ is installed in Windows
- Project sources are located under WSL2 (`\\wsl.localhost\Ubuntu-20.04\path\to\project`)
- Java 17 installation is located under WSL2

**Full stack trace**
```
2022-10-31 10:25:38,918 [ 105535] SEVERE - #c.i.o.a.i.ApplicationImpl - 'other' is different type of Path
java.lang.IllegalArgumentException: 'other' is different type of Path
	at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:400)
	at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:42)
	at com.haulmont.jmixstudio.util.HPsiUtil.tryGetRelativePath(HPsiUtil.kt:81)
	at com.haulmont.jmixstudio.backend.properties.JmixPropertySourceKt.pathString(JmixPropertySource.kt:75)
	at com.haulmont.jmixstudio.intellij.properties.JmixPropertiesManagerImpl$loadProjectModulePropertySourcesNoCache$4.invoke(JmixPropertiesManagerImpl.kt:195)
	at com.haulmont.jmixstudio.intellij.properties.JmixPropertiesManagerImpl$loadProjectModulePropertySourcesNoCache$4.invoke(JmixPropertiesManagerImpl.kt:195)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3347)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3364)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3363)
	at com.haulmont.jmixstudio.intellij.properties.JmixPropertiesManagerImpl.loadProjectModulePropertySourcesNoCache(JmixPropertiesManagerImpl.kt:195)
	at com.haulmont.jmixstudio.intellij.properties.JmixPropertiesManagerImpl.loadPropertySources$lambda-15(JmixPropertiesManagerImpl.kt:167)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.haulmont.jmixstudio.intellij.properties.JmixPropertiesManagerImpl.loadPropertySources(JmixPropertiesManagerImpl.kt:166)
	at com.haulmont.jmixstudio.intellij.properties.JmixPropertiesManagerImpl.loadProperties(JmixPropertiesManagerImpl.kt:80)
	at com.haulmont.jmixstudio.intellij.properties.JmixPropertiesManagerImpl.loadProperty(JmixPropertiesManagerImpl.kt:73)
	at com.haulmont.jmixstudio.intellij.project.resolve.JmixProjectStartupActivity$markJmixSystemDirsAsExcluded$lambda-7$$inlined$runReadAction$1.compute(actions.kt:62)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:928)
	at com.haulmont.jmixstudio.intellij.project.resolve.JmixProjectStartupActivity.markJmixSystemDirsAsExcluded$lambda-7(JmixModuleStateService.kt:369)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
```

**Comment by Gasloff** [comment]
Hi!
Thanks for reporting the issue.

I've created YouTrack [issue](https://youtrack.cuba-platform.com/issue/JST-3389/Studio-broken-with-IntelliJ-on-Windows-and-project-in-WSL2), so you can follow the progress there.

**Comment by Gasloff** [comment]
Hi, @tkonsta 
Could you please check your case with project in WSL2 using Jmix Studio 1.4 nightly build?
See [installation instructions](https://docs.jmix.io/jmix/studio/install.html#nightly).

**Comment by tkonsta** [comment]
Hi @Gasloff ,
I tested with the nightly build and it works fine again for me 👍 Thank you for the fix!

**Comment by tkonsta** [comment]
Hi @Gasloff ,
I just had another Exception message coming up when I opened a new non-jmix project in IntelliJ. It sounds a bit similar as the one from this topic, but I don't know if this relates to the initial problem here, or if this is something different. 

Should I open a new issue?

The StackTrace was the following:
```
com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: Views; ViewsIntention; while looking for description.html [Plugin: io.jmix.studio]
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getResourceLocation(IntentionActionMetaData.java:61)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:125)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings$IntentionSearchableOptionContributor.processOptions(IntentionManagerSettings.kt:170)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.lambda$initialize$0(SearchableOptionsRegistrarImpl.java:125)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:34)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:46)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.initialize(SearchableOptionsRegistrarImpl.java:125)
	at com.intellij.openapi.options.newEditor.SettingsFilter.lambda$new$1(SettingsFilter.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Gasloff** [comment]
Hi @tkonsta,

This is known minor issue relevant for several specific nighlty build versions.
You can update Jmix plugin to the latest nightly build where the problem is fixed.
