### ISSUE TITLE
Cannot search components in tabsheet 

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#1318]
#### Problem
Tabsheet does not return components from inside tabs that makes impossible to find these components on screen.

#### Steps
1. Open project [tabbug.zip](https://github.com/jmix-framework/jmix/files/10323554/tabbug.zip)
2. Try to open "Test twoes", 
**AR:** Empty screen, IllegalStateException
```java
java.lang.IllegalArgumentException: Component with id 'pagination' not found
	at io.jmix.flowui.component.UiComponentUtils.lambda$getComponent$0(UiComponentUtils.java:54) ~[jmix-flowui-1.5.999-SNAPSHOT.jar:na]
	at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
	at io.jmix.flowui.component.UiComponentUtils.getComponent(UiComponentUtils.java:53) ~[jmix-flowui-1.5.999-SNAPSHOT.jar:na]
	at io.jmix.flowui.xml.facet.QueryParametersFacetProvider$PaginationQueryParametersBinderInitTask.execute(QueryParametersFacetProvider.java:141) ~[jmix-flowui-1.5.999-SNAPSHOT.jar:na]
	at io.jmix.flowui.xml.layout.loader.ComponentLoaderContext.executePreInitTasks(ComponentLoaderContext.java:144) ~[jmix-flowui-1.5.999-SNAPSHOT.jar:na]
	at io.jmix.flowui.sys.ViewSupport.initView(ViewSupport.java:115) ~[jmix-flowui-1.5.999-SNAPSHOT.jar:na]
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.init(JmixSpringInstantiator.java:50) ~[jmix-flowui-1.5.999-SNAPSHOT.jar:na]
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.getOrCreate(JmixSpringInstantiator.java:43) ~[jmix-flowui-1.5.999-SNAPSHOT.jar:na]
	at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:193) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:132) ~[flow-server-23.3.0.jar:23.3.0]
	at java.base/java.util.Optional.orElseGet(Optional.java:369) ~[na:na]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:131) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:492) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:473) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:211) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handle(JavaScriptNavigationStateRenderer.java:78) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.handleNavigation(JavaScriptBootstrapUI.java:317) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.renderViewForRoute(JavaScriptBootstrapUI.java:280) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.lambda$connectClient$e368b2b7$1(JavaScriptBootstrapUI.java:143) ~[flow-server-23.3.0.jar:23.3.0]

```

**Comment by KremnevDmitry** [comment]
**Reason**: the `getOwnComponents()` method of the `ComponentContainer` interface returns a collection of tabs for JmixTabSheet.
**Solution**:  return the content component of the tab.

**P.S.**

- Now, `getChildren()` method returns the stream of nested tabs
- `getComponents()` method returns all child components of the tabs content.
- `getOwnComponents()` method returns the contents component of the tab.
