### ISSUE TITLE
Search add-on: Error getting instance name

### ISSUE THREAD

**Issue by Yarik2308** [jmix-framework/jmix#1375]
Here is a problem, we got 3 entities: 

```
@JmixEntity
@Table(name = "JT_TEST_ENTITY1", indexes = [
    Index(name = "IDX_JTTESTENTITY1_TESTENTITY2", columnList = "TEST_ENTITY2_ID")
])
@Entity(name = "jt_TestEntity1")
open class TestEntity1 {

    @JmixGeneratedValue
    @Column(name = "ID", nullable = false)
    @Id
    var id: UUID? = null

    @Column(name = "NAME")
    var name: String? = null

    @JoinColumn(name = "TEST_ENTITY2_ID")
    @ManyToOne(fetch = FetchType.LAZY)
    var testEntity2: TestEntity2? = null

    val instanceName: String
        @DependsOnProperties("name", "testEntity2")
        @InstanceName
        get() = name + " " + if (testEntity2 != null) testEntity2!!.instanceName else ""

}

@JmixEntity
@Table(name = "JT_TEST_ENTITY2", indexes = [
    Index(name = "IDX_JTTESTENTITY2_TESTENTITY3", columnList = "TEST_ENTITY3_ID")
])
@Entity(name = "jt_TestEntity2")
open class TestEntity2 {

    @JmixGeneratedValue
    @Column(name = "ID", nullable = false)
    @Id
    var id: UUID? = null

    @Column(name = "NAME")
    var name: String? = null

    @JoinColumn(name = "TEST_ENTITY3_ID")
    @ManyToOne(fetch = FetchType.LAZY)
    var testEntity3: TestEntity3? = null

    val instanceName: String
        @InstanceName
        @DependsOnProperties("name", "testEntity3")
        get() = "$name ${if (testEntity3 != null) testEntity3!!.name else ""}"

}

@JmixEntity
@Table(name = "JT_TEST_ENTITY3")
@Entity(name = "jt_TestEntity3")
open class TestEntity3 {

    @JmixGeneratedValue
    @Column(name = "ID", nullable = false)
    @Id
    var id: UUID? = null

    @InstanceName
    @Column(name = "NAME")
    var name: String? = null

    @Column(name = "CODE")
    var code: String? = null
}
```

and `JmixEntitySearchIndex`
```
@JmixEntitySearchIndex(entity = TestEntity1::class)
interface TestEntity1IndexDefinition {

    @AutoMappedField(
        includeProperties = ["*"],
        excludeProperties = ["testEntity2"]
    )
    fun mapping()
}
```

As u can see, we do not want `testEntity2` to be add to index of `TestEntity1` because it is already used in its `InstanceName`. 
It throws exception:
```
java.lang.RuntimeException: Error getting instance name
	at io.jmix.core.impl.InstanceNameProviderImpl.getInstanceName(InstanceNameProviderImpl.java:133) ~[jmix-core-1.4.1.jar:na]
	at io.jmix.core.MetadataTools.getInstanceName(MetadataTools.java:213) ~[jmix-core-1.4.1.jar:na]
	at io.jmix.search.index.mapping.propertyvalue.impl.DisplayedNameValueExtractor.getValue(DisplayedNameValueExtractor.java:42) ~[jmix-search-1.4.1.jar:na]
	at io.jmix.search.index.mapping.DisplayedNameDescriptor.getValue(DisplayedNameDescriptor.java:60) ~[jmix-search-1.4.1.jar:na]
	at io.jmix.search.index.impl.EntityIndexerImpl.addIndexActionToBulkRequest(EntityIndexerImpl.java:258) ~[jmix-search-1.4.1.jar:na]
	at io.jmix.search.index.impl.EntityIndexerImpl.indexGroupedInstances(EntityIndexerImpl.java:139) ~[jmix-search-1.4.1.jar:na]
	at io.jmix.search.index.impl.EntityIndexerImpl.indexCollectionByEntityIds(EntityIndexerImpl.java:98) ~[jmix-search-1.4.1.jar:na]
	at io.jmix.search.index.queue.impl.JpaIndexingQueueManager.processQueueItemsGroup(JpaIndexingQueueManager.java:513) ~[jmix-search-1.4.1.jar:na]
	at io.jmix.search.index.queue.impl.JpaIndexingQueueManager.processQueueItems(JpaIndexingQueueManager.java:498) ~[jmix-search-1.4.1.jar:na]
	at io.jmix.search.index.queue.impl.JpaIndexingQueueManager.processQueue(JpaIndexingQueueManager.java:458) ~[jmix-search-1.4.1.jar:na]
	at io.jmix.search.index.queue.impl.JpaIndexingQueueManager.processNextBatch(JpaIndexingQueueManager.java:301) ~[jmix-search-1.4.1.jar:na]
	at io.jmix.search.index.queue.impl.JpaIndexingQueueManager.processNextBatch(JpaIndexingQueueManager.java:296) ~[jmix-search-1.4.1.jar:na]
	at io.jmix.autoconfigure.search.job.IndexingQueueProcessingJob.execute(IndexingQueueProcessingJob.java:32) ~[jmix-search-starter-1.4.1.jar:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at io.jmix.core.impl.InstanceNameProviderImpl.getInstanceName(InstanceNameProviderImpl.java:130) ~[jmix-core-1.4.1.jar:na]
	... 14 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot get unfetched attribute [name] from detached object com.company.jmix.test.entity.TestEntity2-97ad4e02-ef57-b260-0241-3000e2c6ed81 [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100) ~[org.eclipse.persistence.core-2.7.9-6-jmix.jar:na]
	at io.jmix.eclipselink.impl.JmixEntityFetchGroup.onUnfetchedAttribute(JmixEntityFetchGroup.java:67) ~[jmix-eclipselink-1.4.1.jar:na]
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:3027) ~[org.eclipse.persistence.jpa-2.7.9-6-jmix.jar:na]
	at com.company.jmix.test.entity.TestEntity2._persistence_checkFetched(TestEntity2.kt) ~[main/:na]
	at com.company.jmix.test.entity.TestEntity2._persistence_get_name(TestEntity2.kt) ~[main/:na]
	at com.company.jmix.test.entity.TestEntity2.getInstanceName(TestEntity2.kt:32) ~[main/:na]
	at com.company.jmix.test.entity.TestEntity1.getInstanceName(TestEntity1.kt:32) ~[main/:na]
	... 19 common frames omitted
```

Here test project:
[jmix-test.zip](https://github.com/jmix-framework/jmix/files/10456386/jmix-test.zip)

**Comment by Yarik2308** [comment]
I extended `EntityIndexerImpl` and overrided `createFetchPlan` add check `instanceNameRelatedProperty.range.isClass` this helped:
```
override fun createFetchPlan(indexConfiguration: IndexConfiguration): FetchPlan {
        val fetchPlanBuilder = fetchPlans.builder(indexConfiguration.entityClass)
        indexConfiguration.mapping.fields.values.forEach { field ->
            log.trace("Add property to fetch plan: {}", field.entityPropertyFullName)
            fetchPlanBuilder.add(field.entityPropertyFullName)
            field.instanceNameRelatedProperties.forEach { instanceNameRelatedProperty ->
                log.trace(
                    "Add instance name related property to fetch plan: {}",
                    instanceNameRelatedProperty.toPathString()
                )
                fetchPlanBuilder.add(instanceNameRelatedProperty.toPathString())
            }
        }

        indexConfiguration.mapping
            .displayedNameDescriptor
            .instanceNameRelatedProperties
            .forEach { instanceNameRelatedProperty ->
                log.trace(
                    "Add instance name related property (displayed name) to fetch plan: {}",
                    instanceNameRelatedProperty.toPathString()
                )
                if (instanceNameRelatedProperty.range.isClass) {
                    fetchPlanBuilder.add(instanceNameRelatedProperty.toPathString(), FetchPlan.INSTANCE_NAME)
                } else {
                    fetchPlanBuilder.add(instanceNameRelatedProperty.toPathString())
                }
            }

        return fetchPlanBuilder.build()
    }
```

**Comment by Gavrilov-Ivan** [comment]
Hello,
Yes, there is a gap in fetch plan for instance name. Your fix is good, it will be included.
Thanks.
