### ISSUE TITLE
Improve navigating to Views in Flow UI Test Assist

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1426]
### Description
For now: 
1) Editors can be opened only with `withBackwardNavigation(false)`
2) Second navigating in one test does not work:
```
Trying to detach an element from parent that does not have it.
java.lang.IllegalArgumentException: Trying to detach an element from parent that does not have it.    
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:125)    
	at com.vaadin.flow.dom.Node.removeChild(Node.java:483)    
	at com.vaadin.flow.dom.Node.removeChild(Node.java:466)    
	at com.vaadin.flow.dom.Element.removeFromParent(Element.java:515)    
	at com.vaadin.flow.component.applayout.AppLayout.remove(AppLayout.java:355)    
	at com.vaadin.flow.component.applayout.AppLayout.removeContent(AppLayout.java:349)    
	at com.vaadin.flow.component.applayout.AppLayout.setContent(AppLayout.java:231)    
	at com.vaadin.flow.component.applayout.AppLayout.showRouterLayoutContent(AppLayout.java:315)    
	at io.jmix.flowui.app.main.StandardMainView.showRouterLayoutContent(StandardMainView.java:38)    
	at com.vaadin.flow.component.internal.UIInternals.showRouteTarget(UIInternals.java:753)    
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:231)    
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.forward(AbstractNavigationStateRenderer.java:715)    
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handleTriggeredBeforeEvent(AbstractNavigationStateRenderer.java:676)    
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.notifyNavigationTarget(AbstractNavigationStateRenderer.java:626)    
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEvent(AbstractNavigationStateRenderer.java:600)    
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:501)    
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:473)    
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:211)    
	at com.vaadin.flow.router.internal.ErrorStateRenderer.handle(ErrorStateRenderer.java:106)    
	at com.vaadin.flow.router.Router.handleExceptionNavigation(Router.java:286)    
	at com.vaadin.flow.router.Router.navigate(Router.java:221)    
	at com.vaadin.flow.router.Router.navigate(Router.java:186)    
	at com.vaadin.flow.component.UI.navigate(UI.java:1128)    
	at io.jmix.flowui.view.navigation.ViewNavigationSupport.navigate(ViewNavigationSupport.java:51)    
	at io.jmix.flowui.view.navigation.AbstractNavigationProcessor.processNavigation(AbstractNavigationProcessor.java:58)    
	at io.jmix.flowui.view.navigation.ViewNavigator.navigate(ViewNavigator.java:148)
```

**Comment by gorbunkov** [comment]
@Flaurite Has this issue been fixed in https://github.com/jmix-framework/jmix/issues/1467 ?
If so, then please close the current one.

**Comment by Flaurite** [comment]
Fixed in: https://github.com/jmix-framework/jmix/issues/1467
