### ISSUE TITLE
Database creation failed for Reports add-on and MySQL (MariaDB)

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1438]
* Create new project on Jmix 1.5
* Change database type to MySQL or MariaDB
* Add Reports add-on
* Run the project.

While applying liquibase changesets, an exception will be thrown:

```
Unexpected error running Liquibase: Migration failed for change set io/jmix/reports/liquibase/changelog/004-reports.xml::1-mysql::reports:
     Reason: liquibase.exception.DatabaseException: (conn=22) Cannot change column 'GROUP_ID': used in a foreign key constraint 'FK_REPORT_TO_REPORT_GROUP' [Failed SQL: (1832) ALTER TABLE mariarep.REPORT_REPORT MODIFY GROUP_ID VARCHAR(32) NULL]
For more information, please use the --logLevel flag
[2023-02-17 16:30:02] SEVERE [liquibase.integration] Unexpected error running Liquibase: Migration failed for change set io/jmix/reports/liquibase/changelog/004-reports.xml::1-mysql::reports:
     Reason: liquibase.exception.DatabaseException: (conn=22) Cannot change column 'GROUP_ID': used in a foreign key constraint 'FK_REPORT_TO_REPORT_GROUP' [Failed SQL: (1832) ALTER TABLE mariarep.REPORT_REPORT MODIFY GROUP_ID VARCHAR(32) NULL]
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set io/jmix/reports/liquibase/changelog/004-reports.xml::1-mysql::reports:
     Reason: liquibase.exception.DatabaseException: (conn=22) Cannot change column 'GROUP_ID': used in a foreign key constraint 'FK_REPORT_TO_REPORT_GROUP' [Failed SQL: (1832) ALTER TABLE mariarep.REPORT_REPORT MODIFY GROUP_ID VARCHAR(32) NULL]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126)
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:265)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:264)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2405)
	at liquibase.Liquibase.update(Liquibase.java:211)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1869)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:398)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.integration.commandline.Main$1.run(Main.java:397)
	at liquibase.integration.commandline.Main$1.run(Main.java:221)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.Main.run(Main.java:221)
	at liquibase.integration.commandline.Main.main(Main.java:164)
```

It is related to the changes made in #1295

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.0-RC3
Jmix Studio plugin version: 1.5.SNAPSHOT4968-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
