### ISSUE TITLE
DataManager.getReference() increments underlying sequence

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1451]
See [forum topic](https://forum.jmix.io/t/datamanger-getreference-increases-the-underlying-sequence/2552).

Testing:

- Check if entity instances with all types of numeric ID (and with Embedded ID with numeric part) can be successfully created.
- Check if execution DataManager#getReference(Class<T> entityClass, Object id) with such entity instances doesn't increment internal sequence (Id for the next created instance is generated without gap).

**Comment by rusiaikinat** [comment]
> For QA: pls, do a quick smoke test of AppSettings functionality

NoSuchMethodError: 'java.lang.Object io.jmix.core.Metadata.create(java.lang.Class, java.lang.Object)'

TC
Save Current value

AR

```
java.lang.NoSuchMethodError: 'java.lang.Object io.jmix.core.Metadata.create(java.lang.Class, java.lang.Object)'
	at io.jmix.appsettings.impl.AppSettingsToolsImpl.loadAppSettingsEntityFromDataStore(AppSettingsToolsImpl.java:51)
	at io.jmix.appsettings.impl.AppSettingsImpl.getAppSettingsEntity(AppSettingsImpl.java:56)
	at io.jmix.appsettings.impl.AppSettingsImpl.save(AppSettingsImpl.java:48)
	at io.jmix.appsettingsflowui.view.appsettings.AppSettingsEntityView.saveChanges(AppSettingsEntityView.java:438)
	at io.jmix.appsettingsflowui.view.appsettings.AppSettingsEntityView.onSave(AppSettingsEntityView.java:411)
	at io.jmix.flowui.kit.event.EventBus.fireEvent(EventBus.java:82)
	at io.jmix.flowui.kit.action.BaseAction.actionPerform(BaseAction.java:67)
	at io.jmix.flowui.kit.component.button.JmixButtonActionSupport.onButtonClick(JmixButtonActionSupport.java:177)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233)
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:475)
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:292)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447)
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:75)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:438)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:419)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:419)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:320)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)

```

**Comment by gorbunkov** [comment]
@rusiaikinat Please try once again. It seems that snapshot hasn't been correctly built.
