### ISSUE TITLE
Ui Tests with data grid component and refresh operation throws exception

### ISSUE THREAD

**Issue by mariodavid** [jmix-framework/jmix#1465]
# Jmix Problem - UI Test data grid refresh

When creating a UI test with a data grid component and using
any kind of refresh mechanism (either via standard refresh action or via custom code that performs `getScreenData().loadAll()`),
an `com.vaadin.event.ListenerMethod$MethodException` is thrown.

Therefore the test cannot be performed correctly.

The same behaviour works fine when using the table component.

#### Example Project
[jmix-problem-ui-test-datagrid-reload-data.zip](https://github.com/jmix-framework/jmix/files/10847230/jmix-problem-ui-test-datagrid-reload-data.zip)

See test case example: [UserUiTest.java](src/test/java/problem/user/UserUiTest.java).

#### Example test case `UserUiTest`:
```
package problem.user;

import problem.entity.User;
import problem.screen.user.UserBrowse;
import problem.screen.user.UserEdit;
import problem.test_support.UiIntegrationTest;
import io.jmix.core.DataManager;
import io.jmix.ui.component.Button;
import io.jmix.ui.component.GroupTable;
import io.jmix.ui.component.PasswordField;
import io.jmix.ui.component.TextField;
import io.jmix.ui.component.data.TableItems;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

/**
 * Sample UI integration test for the User entity.
 */
public class UserUiTest extends UiIntegrationTest {

    @Autowired
    DataManager dataManager;

    @Test
    void when_reloadData_via_standardRefreshAction_then_no_exception() {
        // given:
        UserBrowse userBrowseScreen = getScreens().create(UserBrowse.class);
        userBrowseScreen.show();

        // and:
        Button refreshBtn = findComponent(userBrowseScreen, "refreshBtn");

        // expect: no exception is thrown, but in fact  com.vaadin.event.ListenerMethod$MethodException is thrown
        assertDoesNotThrow(refreshBtn::click);
    }
    @Test
    void when_reloadData_via_customActionWithScreenDataLoadAll_then_no_exception() {
        // given:
        UserBrowse userBrowseScreen = getScreens().create(UserBrowse.class);
        userBrowseScreen.show();

        // and:
        Button customReloadButton = findComponent(userBrowseScreen, "reloadBtn");

        // expect: no exception is thrown, but in fact  com.vaadin.event.ListenerMethod$MethodException is thrown
        assertDoesNotThrow(customReloadButton::click);
    }

    @AfterEach
    void tearDown() {
        dataManager.load(User.class)
                .query("e.username like ?1", "test-user-%")
                .list()
                .forEach(u -> dataManager.remove(u));
    }
}

```

#### Root cause Exception
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.locks.Lock.tryLock(long, java.util.concurrent.TimeUnit)" because the return value of "com.vaadin.server.VaadinSession.getLockInstance()" is null
```

#### Full Stacktrace:
```
2023-02-28 07:33:32.408  INFO 41913 --- [    Test worker] eclipselink.logging.all                  : EclipseLink, version: Eclipse Persistence Services - 2.7.9.6-jmix
2023-02-28 07:33:32.546  INFO 41913 --- [    Test worker] i.j.core.impl.FetchPlanRepositoryImpl    : Initializing fetch plans
2023-02-28 07:33:32.624  WARN 41913 --- [    Test worker] com.vaadin.spring.internal.BeanStore     : Storing non-serializable bean [io.jmix.ui.sys.ScreensImpl@31ab93ea] with name [ui_Screens] in [UIBeanStore[id=1e09f149, name=UI:1]]
2023-02-28 07:33:32.625  WARN 41913 --- [    Test worker] com.vaadin.spring.internal.BeanStore     : Storing non-serializable bean [io.jmix.ui.navigation.WebUrlRouting@770f77f3] with name [ui_UrlRouting] in [UIBeanStore[id=1e09f149, name=UI:1]]
2023-02-28 07:33:32.646  INFO 41913 --- [    Test worker] io.jmix.ui.WindowConfig                  : WindowConfig initialized in 20 ms
2023-02-28 07:33:32.696  WARN 41913 --- [    Test worker] com.vaadin.spring.internal.BeanStore     : Storing non-serializable bean [io.jmix.ui.sys.DialogsImpl@581fa170] with name [ui_Dialogs] in [UIBeanStore[id=1e09f149, name=UI:1]]
2023-02-28 07:33:32.698  WARN 41913 --- [    Test worker] com.vaadin.spring.internal.BeanStore     : Storing non-serializable bean [io.jmix.ui.sys.NotificationsImpl@45c57d7f] with name [ui_Notifications] in [UIBeanStore[id=1e09f149, name=UI:1]]
2023-02-28 07:33:32.699  WARN 41913 --- [    Test worker] com.vaadin.spring.internal.BeanStore     : Storing non-serializable bean [io.jmix.ui.sys.FragmentsImpl@37a45e67] with name [ui_Fragments] in [UIBeanStore[id=1e09f149, name=UI:1]]
2023-02-28 07:33:32.700  WARN 41913 --- [    Test worker] com.vaadin.spring.internal.BeanStore     : Storing non-serializable bean [io.jmix.ui.sys.WebBrowserToolsImpl@732ba741] with name [ui_WebBrowserTools] in [UIBeanStore[id=1e09f149, name=UI:1]]
2023-02-28 07:33:32.846  WARN 41913 --- [    Test worker] com.vaadin.spring.internal.BeanStore     : Storing non-serializable bean [io.jmix.ui.navigation.WebHistory@232cf070] with name [ui_History] in [UIBeanStore[id=1e09f149, name=UI:1]]
2023-02-28 07:33:32.856  WARN 41913 --- [    Test worker] com.vaadin.spring.internal.BeanStore     : Storing non-serializable bean [io.jmix.ui.navigation.UrlChangeHandler@1b2cd4e4] with name [ui_UrlChangeHandler] in [UIBeanStore[id=1e09f149, name=UI:1]]
2023-02-28 07:33:32.874  INFO 41913 --- [    Test worker] io.jmix.ui.WindowConfig                  : WindowConfig initialized in 12 ms

Unexpected exception thrown: com.vaadin.event.ListenerMethod$MethodException: Invocation of method onDataChange in com.vaadin.data.provider.DataCommunicator$$Lambda$1791/0x0000000800efa210 failed.
org.opentest4j.AssertionFailedError: Unexpected exception thrown: com.vaadin.event.ListenerMethod$MethodException: Invocation of method onDataChange in com.vaadin.data.provider.DataCommunicator$$Lambda$1791/0x0000000800efa210 failed.
	at app//org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at app//org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at app//org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at app//org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3135)
	at app//problem.user.UserUiTest.when_reloadData_via_standardRefreshAction_then_no_exception(UserUiTest.java:37)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.3/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@17.0.3/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@17.0.3/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.3/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method onDataChange in com.vaadin.data.provider.DataCommunicator$$Lambda$1791/0x0000000800efa210 failed.
	at app//com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:729)
	at app//com.vaadin.event.EventRouter.fireEvent(EventRouter.java:399)
	at app//com.vaadin.event.EventRouter.fireEvent(EventRouter.java:363)
	at app//com.vaadin.data.provider.AbstractDataProvider.fireEvent(AbstractDataProvider.java:90)
	at app//io.jmix.ui.component.datagrid.DataGridDataProvider.datasourceItemSetChanged(DataGridDataProvider.java:115)
	at app//io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at app//io.jmix.ui.component.data.datagrid.ContainerDataGridItems.containerCollectionChanged(ContainerDataGridItems.java:69)
	at app//io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at app//io.jmix.ui.model.impl.CollectionContainerImpl.fireCollectionChanged(CollectionContainerImpl.java:241)
	at app//io.jmix.ui.model.impl.CollectionContainerImpl.setItems(CollectionContainerImpl.java:106)
	at app//io.jmix.ui.model.impl.CollectionLoaderImpl._load(CollectionLoaderImpl.java:102)
	at app//io.jmix.ui.model.impl.CollectionLoaderImpl.load(CollectionLoaderImpl.java:75)
	at app//io.jmix.ui.action.list.RefreshAction.execute(RefreshAction.java:114)
	at app//io.jmix.ui.action.list.RefreshAction.actionPerform(RefreshAction.java:75)
	at app//io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75)
	at app//io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:60)
	at app//com.vaadin.ui.Button.click(Button.java:360)
	at app//io.jmix.ui.component.impl.ButtonImpl.click(ButtonImpl.java:271)
	at app//org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:50)
	... 88 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.locks.Lock.tryLock(long, java.util.concurrent.TimeUnit)" because the return value of "com.vaadin.server.VaadinSession.getLockInstance()" is null
	at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2053)
	at com.vaadin.server.VaadinService.accessSession(VaadinService.java:2021)
	at com.vaadin.server.VaadinSession.access(VaadinSession.java:1409)
	at com.vaadin.ui.UI.access(UI.java:1572)
	at com.vaadin.data.provider.DataCommunicator.lambda$attachDataProviderListener$7a32c94f$1(DataCommunicator.java:885)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:709)
	... 106 more


```

**Comment by gorbunkov** [comment]
Please reopen the issue if it is relevant for Jmix 2.x
