### ISSUE TITLE
Spring context doesn't start in tests if there is a bean with injected PasswordEncoder

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1473]
- Create a new project
- Add a bean like this:
  ```
  package com.company.untitled1.app;
  
  import org.springframework.security.crypto.password.PasswordEncoder;
  import org.springframework.stereotype.Component;
  
  @Component
  public class SampleBean {
  
      private final PasswordEncoder passwordEncoder;
  
      public SampleBean(PasswordEncoder passwordEncoder) {
          this.passwordEncoder = passwordEncoder;
      }
  }
  ```
- Try to start any `@SpringBootTest`. You will get an error with the root cause:
  ```
  org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'sec_PasswordEncoder': Requested bean is currently in creation: Is there an unresolvable circular reference?
      at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.beforeSingletonCreation(DefaultSingletonBeanRegistry.java:355)
      at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:227)
      at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
      at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
      at app//org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
      at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
      at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
      at app//org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
      ... 143 more
  ```

Why is this important?
`PasswordEncoder` is required for creating users. Users are usually created programmatically in integrations and in data initializers. See for example https://github.com/jmix-framework/jmix-onboarding/blob/main/src/main/java/com/company/onboarding/listener/DemoDataInitializer.java
As soon as such a bean is present in the project, all tests fail to start. An inexperienced developer will be confused and unable to find a workaround.

**Comment by breakingfox** [comment]
Reproduces in version 2 and and lower
Doesn't reproduce in 2.1
