### ISSUE TITLE
Quartz jobs screen displays no jobs if any of job classes has been removed

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1551]
Jmix: 1.5.0

Create several job classes in your application.
Manually add several quartz jobs using the "Quartz jobs" screen.
Delete one of job classes.
Restart the app and open the Quartz Jobs screen

AR:
No jobs are displayed on the screen and the exception appeared in the log:

```
org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found: com.company.removedquartzjob.job.SampleJob1
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1393) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$9.execute(JobStoreSupport.java:1382) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreCMT.executeInLock(JobStoreCMT.java:245) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeWithoutLock(JobStoreSupport.java:3800) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1379) ~[quartz-2.3.2.jar:na]
	at org.quartz.core.QuartzScheduler.getJobDetail(QuartzScheduler.java:1493) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.StdScheduler.getJobDetail(StdScheduler.java:498) ~[quartz-2.3.2.jar:na]
	at io.jmix.quartz.service.QuartzService.getAllJobs(QuartzService.java:54) ~[jmix-quartz-1.5.0.jar:na]
	at io.jmix.quartzui.screen.jobs.JobModelBrowse.loadJobsData(JobModelBrowse.java:67) ~[jmix-quartz-ui-1.5.0.jar:na]
	at io.jmix.quartzui.screen.jobs.JobModelBrowse.onBeforeShow(JobModelBrowse.java:63) ~[jmix-quartz-ui-1.5.0.jar:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-1.5.0.jar:na]
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124) ~[jmix-ui-1.5.0.jar:na]
	at io.jmix.ui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:58) ~[jmix-ui-1.5.0.jar:na]
	at io.jmix.ui.sys.ScreensImpl.fireScreenBeforeShowEvent(ScreensImpl.java:1364) ~[jmix-ui-1.5.0.jar:na]
	at io.jmix.ui.sys.ScreensImpl.show(ScreensImpl.java:357) ~[jmix-ui-1.5.0.jar:na]
	at io.jmix.ui.sys.ScreensImpl.showFromNavigation(ScreensImpl.java:452) ~[jmix-ui-1.5.0.jar:na]
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:193) ~[jmix-ui-1.5.0.jar:na]
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:272) ~[jmix-ui-1.5.0.jar:na]
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:257) ~[jmix-ui-1.5.0.jar:na]
	at io.jmix.ui.component.mainwindow.impl.SideMenuImpl$MenuItemImpl.menuSelected(SideMenuImpl.java:587) ~[jmix-ui-1.5.0.jar:na]
	at io.jmix.ui.widget.JmixSideMenu$1.menuItemTriggered(JmixSideMenu.java:91) ~[jmix-ui-1.5.0.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
```

See [forum topic](https://forum.jmix.io/t/loading-jobs-fails-if-a-job-class-is-re-moved/2751)

**Comment by lovtsovaik** [comment]
For 1.5.999-SNAPSHOT Quartz job screen is opened. Only jobs linked with not-deleted class are displayed in the list, so you can't delete irrelevant job instances via UI screen.

The error is still in logs
`org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found: com.company.jm159.app.SampleJob` 
and then
`2023-05-02 20:41:00.873 ERROR 31040 --- [nio-8080-exec-9] io.jmix.quartz.service.QuartzService     : Unable to fetch information about the job: DEFAULT.sample2`

*Note: it seems user wanted to delete this jobs via UI*

**Comment by gorbunkov** [comment]
While working on this issue I made valid jobs visible. Previously no jobs were displayed at all. I've created a separate issue for ability to remove invalid jobs: https://github.com/jmix-framework/jmix/issues/1669. We won't do it in the current issue.
