### ISSUE TITLE
TimeoutException is thrown while logging out using LogoutAction

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1579]
### Description
1) Create Flow UI project with 1.5.1 version.
2) Launch the application and try to log out

**AR**
```
java.util.concurrent.TimeoutException: null
	at org.atmosphere.cpr.BroadcasterFuture.get(BroadcasterFuture.java:127) ~[atmosphere-runtime-2.7.3.slf4jvaadin4.jar:na]
	at com.vaadin.flow.server.communication.AtmospherePushConnection.disconnect(AtmospherePushConnection.java:331) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.component.internal.UIInternals.setPushConnection(UIInternals.java:467) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.component.internal.UIInternals.setSession(UIInternals.java:419) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.server.VaadinSession.removeUI(VaadinSession.java:621) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.server.VaadinService.lambda$fireSessionDestroy$20ed7015$1(VaadinService.java:648) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:466) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:427) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.server.VaadinService.lambda$fireSessionDestroy$9c853e43$1(VaadinService.java:638) ~[flow-server-23.3.0.jar:23.3.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2059) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:712) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2025) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:1992) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:1016) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.server.VaadinService.fireSessionDestroy(VaadinService.java:629) ~[flow-server-23.3.0.jar:23.3.0]
	at com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:208) ~[flow-server-23.3.0.jar:23.3.0]
	at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1894) ~[tomcat-embed-core-9.0.73.jar:9.0.73]
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:861) ~[tomcat-embed-core-9.0.73.jar:9.0.73]
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:744) ~[tomcat-embed-core-9.0.73.jar:9.0.73]
	at org.apache.catalina.session.StandardSession.invalidate(StandardSession.java:1237) ~[tomcat-embed-core-9.0.73.jar:9.0.73]
	at org.apache.catalina.session.StandardSessionFacade.invalidate(StandardSessionFacade.java:170) ~[tomcat-embed-core-9.0.73.jar:9.0.73]
	at org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler.logout(SecurityContextLogoutHandler.java:65) ~[spring-security-web-5.7.7.jar:5.7.7]
	at org.springframework.security.web.authentication.logout.CompositeLogoutHandler.logout(CompositeLogoutHandler.java:54) ~[spring-security-web-5.7.7.jar:5.7.7]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:99) ~[spring-security-web-5.7.7.jar:5.7.7]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.7.7.jar:5.7.7]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.7.jar:5.7.7]
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117) ~[spring-security-web-5.7.7.jar:5.7.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.26.jar:5.3.26]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.7
	...
```

**Comment by Flaurite** [comment]
Probably, the same problem discussed here: https://stackoverflow.com/questions/68609725/vaadin-sometimes-often-i-get-java-util-concurrent-timeoutexception-null-befo

**Comment by MeyersJeff** [comment]
I reported this issue in the [Forums](https://forum.jmix.io/t/upgrade-1-5-to-2-0-2-questions/3629) and it is also happening in Jmix 2.0.

**Comment by Flaurite** [comment]
Is not reproduced in 2.1+

**Comment by rusiaikinat** [comment]
Is reproduced in 1.5.5 FlowUI
