### ISSUE TITLE
IllegalStateException: Current item is null. When click OK in the Template editor

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1613]
env
Jmix version: 1.5.1

TC
Open report -> Templates -> Create
Select output type : Table
Click OK
or
Open report -> Templates
Open an existing template with the `Table`  type
Click OK

AR

```
java.lang.IllegalStateException: Current item is null
	at io.jmix.ui.model.impl.InstanceContainerImpl.getItem(InstanceContainerImpl.java:74)
	at io.jmix.ui.screen.ScreenListComponentValidation.validateListComponent(ScreenListComponentValidation.java:74)
	at io.jmix.ui.screen.ScreenValidation.lambda$validateUiListComponents$1(ScreenValidation.java:112)
	at io.jmix.ui.component.ComponentsHelper.lambda$traverseComponents$0(ComponentsHelper.java:74)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at io.jmix.ui.component.ComponentsHelper.traverseComponents(ComponentsHelper.java:73)
	at io.jmix.ui.component.ComponentsHelper.lambda$traverseComponents$0(ComponentsHelper.java:77)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at io.jmix.ui.component.ComponentsHelper.traverseComponents(ComponentsHelper.java:73)
	at io.jmix.ui.component.ComponentsHelper.lambda$traverseComponents$0(ComponentsHelper.java:77)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at io.jmix.ui.component.ComponentsHelper.traverseComponents(ComponentsHelper.java:73)
	at io.jmix.ui.component.ComponentsHelper.lambda$traverseComponents$0(ComponentsHelper.java:77)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at io.jmix.ui.component.ComponentsHelper.traverseComponents(ComponentsHelper.java:73)
	at io.jmix.ui.component.ComponentsHelper.lambda$traverseComponents$0(ComponentsHelper.java:77)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at io.jmix.ui.component.ComponentsHelper.traverseComponents(ComponentsHelper.java:73)
	at io.jmix.ui.component.ComponentsHelper.lambda$traverseComponents$0(ComponentsHelper.java:77)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at io.jmix.ui.component.ComponentsHelper.traverseComponents(ComponentsHelper.java:73)
	at io.jmix.ui.component.ComponentsHelper.lambda$traverseComponents$0(ComponentsHelper.java:77)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at io.jmix.ui.component.ComponentsHelper.traverseComponents(ComponentsHelper.java:73)
	at io.jmix.ui.screen.ScreenValidation.validateUiListComponents(ScreenValidation.java:109)
	at io.jmix.ui.screen.StandardEditor.validateUiComponents(StandardEditor.java:555)
	at io.jmix.ui.screen.StandardEditor.validateScreen(StandardEditor.java:537)
	at io.jmix.ui.screen.StandardEditor.commitChanges(StandardEditor.java:418)
	at io.jmix.ui.screen.StandardEditor.closeWithCommit(StandardEditor.java:626)
	at io.jmix.ui.screen.StandardEditor.commitAndClose(StandardEditor.java:580)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220)
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	.....
```

**Note**: If you select a string in BAND, the exception will not appear

**Comment by breakingfox** [comment]
Already fixed in version 1.5.2
