### ISSUE TITLE
NoSuchBeanDefinitionException: No bean named '<undefined>' available

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1716]
Jmix version: 2.0.999-SNAPSHOT

TC
Open project  [flow2meta.zip](https://github.com/jmix-framework/jmix/files/11528898/flow2meta.zip) or

Create Jpa Entity 
Create  views
Create MappedSuperclass
Add the MappedSuperclass load collection to the JpaEntity 
Add loader (MappedSuperclass ) in controller JpaEntity 
Run project
Create an instance of an JpaEntity 

AR
NoSuchBeanDefinitionException: No bean named 'undefined'  available

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named '<undefined>' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:893)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1132)
	at io.jmix.core.impl.DataStoreFactory.lambda$get$1(DataStoreFactory.java:47)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.jmix.core.impl.DataStoreFactory.get(DataStoreFactory.java:46)
	at io.jmix.core.impl.UnconstrainedDataManagerImpl.saveContextToStore(UnconstrainedDataManagerImpl.java:256)
	at io.jmix.core.impl.UnconstrainedDataManagerImpl.save(UnconstrainedDataManagerImpl.java:221)
	at io.jmix.flowui.model.impl.DataContextImpl.saveToDataManager(DataContextImpl.java:708)
	at io.jmix.flowui.model.impl.DataContextImpl.performSave(DataContextImpl.java:689)
	at io.jmix.flowui.model.impl.DataContextImpl.save(DataContextImpl.java:650)
	at io.jmix.flowui.view.StandardDetailView.lambda$createStandardSaveAction$2(StandardDetailView.java:264)
	at io.jmix.flowui.view.StandardDetailView.saveChanges(StandardDetailView.java:226)
	at io.jmix.flowui.view.StandardDetailView.closeWithSave(StandardDetailView.java:299)
	at io.jmix.flowui.action.view.DetailSaveCloseAction.execute(DetailSaveCloseAction.java:66)
	at io.jmix.flowui.action.view.ViewAction.actionPerform(ViewAction.java:140)
	at io.jmix.flowui.kit.component.button.JmixButtonActionSupport.onButtonClick(JmixButtonActionSupport.java:177)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233)
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:475)
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:292)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447)
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:74)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:438)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:419)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:419)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:320)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:114)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1534)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:399)
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	...

```

**Comment by knstvk** [comment]
You cannot load MappedSuperclass. Please create an issue for Studio if it generates a loader for MappedSuperclass.
