### ISSUE TITLE
Notifications add-on with Flow UI

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1719]
----
### Changes

To add add-on to Jmix application use the following code:
```
implementation('io.jmix.notifications:jmix-notifications-starter')
implementation('io.jmix.notifications:jmix-notifications-flowui-starter')
```

UI part of add-on was migrated to Flow UI.

#### UI

1) Added new action - `CreateNotificationAction`. It opens Create Notification Dialog. Action is secured by specific permission `NotificationsCreateDialogContext`. Usage example

```
<view xmlns="http://jmix.io/schema/flowui/view">
    <actions>
        <action id="createNotification" type="ntf_createNotification"/>
    </actions>
    <layout>
        <button id="createNotificationBtn" action="createNotification"/>
    </layout>
</view>
```

2) To work with `InAppNotification` there are views: `InAppNotificationListView` / `...DetailView`. 
    Note, `InAppNotificationListView` for creation opens `CreateNotificationDialog` for editing `InAppNotificationDetailView`.
    
#### Roles

Four roles:
1) `NotificationsSenderAccessRole` - has all permissions to send notification.
2) `InAppNotificationReaderAccessRole` - has all permissions to read notifications.
3) `NotificationsUserAccessRole` - combines "sender" and "reader" roles.
4) `NotificationsAdminAccessRole` - has all permissions to work notifications.

#### Component

Add-on has `NotificationsIndicator` component. It shows unread notifications count (`InAppNotification` entity) for current user.
You can show all notifications in dialog by clicking the component. 

#### XML example
```
<view xmlns="http://jmix.io/schema/flowui/view"
      xmlns:ntf="http://jmix.io/schema/notifications/ui">
    <layout>
        <ntf:notificationsIndicator id="notificationsIndicator"/>
    </layout>
</view>
```
#### Java example
```
NotificationsIndicator indicator = uiComponents.create(NotificationsIndicator.class);
hbox.add(indicator);
```
### Specific API
1) `addCountChangeListener()` - adds notifications count change listener;
2) `set/getIcon()` - sets/gets icon

**Comment by rusiaikinat** [comment]
Reopened
Create and read notification

```
java.lang.ClassCastException: class io.jmix.notificationsflowui.event.VaadinSessionNotificationEvent cannot be cast to class io.jmix.core.usersubstitution.event.UiUserSubstitutionsChangedEvent (io.jmix.notificationsflowui.event.VaadinSessionNotificationEvent and io.jmix.core.usersubstitution.event.UiUserSubstitutionsChangedEvent are in unnamed module of loader 'app')
    at io.jmix.flowui.sys.event.UiEventsManager.invokeListener(UiEventsManager.java:124)
    at io.jmix.flowui.sys.event.UiEventsManager.publish(UiEventsManager.java:117)
    at io.jmix.notificationsflowui.event.VaadinSessionNotificationEventPublisher.lambda$onSessionAccess$16b70441$1(VaadinSessionNotificationEventPublisher.java:146)
    at com.vaadin.flow.component.UI.accessSynchronously(UI.java:487)
    at com.vaadin.flow.component.UI.accessSynchronously(UI.java:448)
    at io.jmix.notificationsflowui.event.VaadinSessionNotificationEventPublisher.onSessionAccess(VaadinSessionNotificationEventPublisher.java:144)
    at io.jmix.notificationsflowui.event.VaadinSessionNotificationEventPublisher.lambda$publishEvent$f0516ea$1(VaadinSessionNotificationEventPublisher.java:127)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2024)
    at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:146)
    at com.vaadin.flow.server.communication.UidlRequestHandler.createUidl(UidlRequestHandler.java:155)
    at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:145)
    at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115)
    at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
    at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1529)
    at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398)
    at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106)
    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
```

**Comment by Flaurite** [comment]
@rusiaikinat could you check again? Should be fixed here: https://github.com/jmix-framework/jmix/issues/2334

**Comment by Fedoseew** [comment]
@Flaurite, to display the `notifications indicator` component correctly in preview, you should define the component, meta description and frontend files into a separate kit module.

Example can be found in `JST-4345` branch (jmix-all, jmix-premium and jmix projects).

Also see Studio ticket here: https://youtrack.jmix.io/issue/JST-4345/Load-add-ons-dependencies-before-building-the-frontend
