### ISSUE TITLE
Error on editing a process variable with Entity type in the process instance editor

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1723]
Jmix: 1.5.2

1. Create a process with input dialog process form on the start
1. Add some property with "entity" type to the start form
1. Run the process
1. Open the process instance editor
1. Try to edit the entity process variable

AR: the exception:

```
Caused by: java.lang.IllegalArgumentException: MetaClass not found for null
	at io.jmix.core.metamodel.model.impl.SessionImpl.getClass(SessionImpl.java:43) ~[jmix-core-1.5.2.jar:na]
	at io.jmix.core.impl.MetadataImpl.getClass(MetadataImpl.java:129) ~[jmix-core-1.5.2.jar:na]
	at io.jmix.bpmui.screen.processvariable.VariableInstanceDataEdit.createEntityPickerField(VariableInstanceDataEdit.java:237) ~[jmix-bpm-ui-1.5.2.jar:na]
	at io.jmix.bpmui.screen.processvariable.VariableInstanceDataEdit.createComponent(VariableInstanceDataEdit.java:183) ~[jmix-bpm-ui-1.5.2.jar:na]
	at io.jmix.bpmui.screen.processvariable.VariableInstanceDataEdit.initValueComponent(VariableInstanceDataEdit.java:117) ~[jmix-bpm-ui-1.5.2.jar:na]
	at io.jmix.bpmui.screen.processvariable.VariableInstanceDataEdit.onBeforeShow(VariableInstanceDataEdit.java:77) ~[jmix-bpm-ui-1.5.2.jar:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-1.5.2.jar:na]
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124) ~[jmix-ui-1.5.2.jar:na]
	at io.jmix.ui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:58) ~[jmix-ui-1.5.2.jar:na]
	at io.jmix.ui.sys.ScreensImpl.fireScreenBeforeShowEvent(ScreensImpl.java:1364) ~[jmix-ui-1.5.2.jar:na]
	at io.jmix.ui.sys.ScreensImpl.show(ScreensImpl.java:357) ~[jmix-ui-1.5.2.jar:na]
	at io.jmix.ui.screen.Screen.show(Screen.java:306) ~[jmix-ui-1.5.2.jar:na]
	at io.jmix.bpmui.screen.processinstance.ProcessInstanceEditRuntimeFragment.onVariablesTableEdit(ProcessInstanceEditRuntimeFragment.java:261) ~[jmix-bpm-ui-1.5.2.jar:na]
```

See [forum topic](https://forum.jmix.ru/t/oshibka-illegalargumentexception-pri-redaktirovanii-peremennoj-s-tipom-entity/1083)

Sample project: [entity-variable-edit.zip](https://github.com/jmix-framework/jmix/files/11531974/entity-variable-edit.zip)

Additionally we need to test this in FlowUI screens.

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT5208-223
IntelliJ version: IntelliJ IDEA 2022.3.3 (Ultimate Edition)
