### ISSUE TITLE
StackOverflowError occurs in the datePicker validator

### ISSUE THREAD

**Issue by sukhova** [jmix-framework/jmix#1785]
Jmix version: 2.0.999-SNAPSHOT

This test case is only relevant for 2.0.999-SNAPSHOT. In 1.5 version it works ok.

Test case:
1) Create `datePicker`:
```
<datePicker id="birthDatePicker" label="Date of birth"/>
```
2) Generate validator for it:
```
    @Install(to = "birthDatePicker", subject = "validator")
    private void birthDatePickerValidator(Date date) {
        Date now = timeSource.currentTimestamp();
        if (date != null && DateUtils.addYears(now,-18).compareTo(date) < 0) {
            throw new ValidationException("The age must be over 18 years");
        }
    }
```
3) Launch the application. Select some date few years ago, for example, in 2021

**AR**:
```
java.lang.StackOverflowError
	at java.base/java.util.HashMap.containsKey(HashMap.java:594)
	at com.vaadin.flow.internal.StateNode.hasFeature(StateNode.java:546)
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.supports(AbstractNodeStateProvider.java:50)
	at com.vaadin.flow.dom.impl.BasicElementStateProvider.supports(BasicElementStateProvider.java:123)
	at com.vaadin.flow.dom.Node.<init>(Node.java:67)
	at com.vaadin.flow.dom.Element.<init>(Element.java:104)
```
Full stack trace see in the [attachments](https://github.com/jmix-framework/jmix/files/11651465/error.txt)

**Comment by glebfox** [comment]
Duplicates: https://github.com/jmix-framework/jmix/issues/1795
