### ISSUE TITLE
Required Select produces StackOverflowError

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1795]
Case: 

Create a blank view with the following:
```
<layout>
    <select id="select" required="true"/>
</layout>
```

Open a view

AR:

```
java.lang.StackOverflowError
	at java.base/java.util.HashMap.get(HashMap.java:556)
	at com.vaadin.flow.internal.nodefeature.NodeMap$HashMapValues.get(NodeMap.java:130)
	at com.vaadin.flow.internal.nodefeature.NodeMap.get(NodeMap.java:232)
	at com.vaadin.flow.internal.nodefeature.NodeMap.put(NodeMap.java:192)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.putWithDeferredChangeEvent(ElementPropertyMap.java:177)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.put(ElementPropertyMap.java:149)
	at com.vaadin.flow.internal.nodefeature.AbstractPropertyMap.setProperty(AbstractPropertyMap.java:62)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.setProperty(ElementPropertyMap.java:99)
	at com.vaadin.flow.dom.impl.BasicElementStateProvider.setProperty(BasicElementStateProvider.java:266)
	at com.vaadin.flow.dom.Element.setRawProperty(Element.java:811)
	at com.vaadin.flow.dom.Element.setProperty(Element.java:622)
```

ER:
No exception

**Comment by lovtsovaik** [comment]
verified
