### ISSUE TITLE
Cannot add value to entity list parameter in Dashboard due to the exception

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1796]
### Description
See Ru forum: [discussion](https://forum.jmix.ru/t/addon-dashboards-this-canvasfragment-is-null/1123/2).

### Steps to reproduce
1. Create dashboard
2. Add entity list parameter
3. Try to add value

**AR**
```
java.lang.IllegalStateException: Id name is not set
	at io.jmix.core.entity.KeyValueEntity.setId(KeyValueEntity.java:161)
	at io.jmix.core.entity.KeyValueEntity$KeyValueEntityEntry.setEntityId(KeyValueEntity.java:75)
	at io.jmix.core.entity.EntityValues.setId(EntityValues.java:46)
	at io.jmix.core.impl.MetadataImpl.internalCreate(MetadataImpl.java:74)
	at io.jmix.core.impl.MetadataImpl.internalCreate(MetadataImpl.java:67)
	at io.jmix.core.impl.MetadataImpl.create(MetadataImpl.java:91)
	at io.jmix.dashboardsui.screen.parameter.fragment.EntityListValueFragment.createKeyValueEntity(EntityListValueFragment.java:130)
	at io.jmix.dashboardsui.screen.parameter.fragment.EntityListValueFragment.saveWindowValue(EntityListValueFragment.java:124)
	at io.jmix.dashboardsui.screen.parameter.fragment.EntityListValueFragment.lambda$openEntityValueScreen$0(EntityListValueFragment.java:112)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124)
	at io.jmix.ui.screen.Screen.close(Screen.java:330)
	at io.jmix.dashboardsui.screen.parameter.fragment.EntityValueScreen.commitAndClose(EntityValueScreen.java:77)
	at io.jmix.dashboardsui.screen.parameter.fragment.EntityValueScreen.commitAndClose(EntityValueScreen.java:55)
```
### Solution
Do not create `KeyValueEntity` by `Metadata`, use constructor instead.

The same exception occurs if you click on "Cancel" button without adding value.  
See `EntityValueScreen#cancelAndClose()`, it uses wrong close action id.

**Comment by gorbunkov** [comment]
Metadata.create() for KeyValueEntity is fixed in the issue https://github.com/jmix-framework/jmix/issues/1708. It seems that this bug will not be reproduced in Dashboards when 1.5.3 is released.
