### ISSUE TITLE
Unable to create a trigger after saving a job. StackOverflowError

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#1804]
Jmix version: 2.0.999-SNAPSHOT

**Prepare project**
- use flowui project with quartz addon
- create a simple job class as described in [documentation](https://docs.jmix.io/jmix/quartz/index.html#usage)

**Test Case**

- Open Quartz > Quartz jobs screen
- Create a new job without any trigger
- Open this job for editing
- Start creating a trigger

AR:
Can't create a trigger
![image](https://github.com/jmix-framework/jmix/assets/73226373/11a1d2e1-9a5d-4c69-9047-a30f93610ae5)

```
java.lang.StackOverflowError
	at com.vaadin.flow.dom.impl.BasicElementStateProvider.getPropertyFeatureIfInitialized(BasicElementStateProvider.java:176)
	at com.vaadin.flow.dom.impl.BasicElementStateProvider.getProperty(BasicElementStateProvider.java:256)
	at com.vaadin.flow.dom.Element.getPropertyRaw(Element.java:981)
	at com.vaadin.flow.dom.Element.getProperty(Element.java:895)
	at io.jmix.flowui.component.delegate.AbstractFieldDelegate.isInvalidInternal(AbstractFieldDelegate.java:245)
	at io.jmix.flowui.component.delegate.AbstractFieldDelegate.executeValidators(AbstractFieldDelegate.java:121)
	at io.jmix.flowui.component.delegate.AbstractFieldDelegate.validatorsPassed(AbstractFieldDelegate.java:254)
	at io.jmix.flowui.component.delegate.AbstractFieldDelegate.updateInvalidState(AbstractFieldDelegate.java:239)
	at io.jmix.flowui.component.delegate.AbstractFieldDelegate.isInvalid(AbstractFieldDelegate.java:221)
	at io.jmix.flowui.component.select.JmixSelect.isInvalid(JmixSelect.java:96)
	at com.vaadin.flow.component.select.Select$InvalidChangeEvent.<init>(Select.java:1050)
	at com.vaadin.flow.component.select.Select.lambda$new$c53a20e4$2(Select.java:156)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.lambda$fireEvent$2(ElementPropertyMap.java:465)
...
```
see full stacktrace in file 
[java.lang.StackOverflowError.txt](https://github.com/jmix-framework/jmix/files/11678677/java.lang.StackOverflowError.txt)

**Comment by lovtsovaik** [comment]
UPD: reproduced also when create a trigger together with job

**Comment by KremnevDmitry** [comment]
Should be fixed by: https://github.com/jmix-framework/jmix/issues/1795

**Comment by lovtsovaik** [comment]
Fixed in 1795

Verified
