### ISSUE TITLE
SimplePagination total count calculation fails when using together with KeyValueCollectionContainer for FlowUI

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1986]
See descriptor #1707

**TC** 
Open blankView project [1707flow.zip](https://github.com/jmix-framework/jmix/files/11964613/1707flow.zip)

**AR**

```
java.lang.RuntimeException: Unable to find selected entity name [select e.aaa, e.bbb from flow2_NewEntity e]
	at io.jmix.data.impl.jpql.QueryTreeAnalyzer.getMainSelectedEntityName(QueryTreeAnalyzer.java:79)
	at io.jmix.data.impl.jpql.transform.QueryTransformerAstBased.createMainSelectedPathNodeVariableNN(QueryTransformerAstBased.java:341)
	at io.jmix.data.impl.jpql.transform.QueryTransformerAstBased.replaceWithCount(QueryTransformerAstBased.java:151)
	at io.jmix.data.impl.JpqlQueryBuilder.applyCount(JpqlQueryBuilder.java:272)
	at io.jmix.data.impl.JpqlQueryBuilder.buildResultQuery(JpqlQueryBuilder.java:221)
	at io.jmix.data.impl.JpqlQueryBuilder.getResultQueryString(JpqlQueryBuilder.java:157)
	at io.jmix.data.impl.JpqlQueryBuilder.getQuery(JpqlQueryBuilder.java:170)
	at io.jmix.eclipselink.impl.JpaDataStore.createLoadQuery(JpaDataStore.java:538)
	at io.jmix.eclipselink.impl.JpaDataStore.countAllValues(JpaDataStore.java:348)
	at io.jmix.core.datastore.AbstractDataStore.getCount(AbstractDataStore.java:294)
```

## Reason

`io.jmix.data.QueryTransformer#replaceWithCount` can't handle `KeyValueCollectionLoader`.

## Solution

* `SimplePagination` - do not display `[?]` button at all. Disable `LastButton`. Use message without `of` for `middle` and `first_incomplete` states.

**Comment by MaxKatyshev** [comment]
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5881-233
IntelliJ version: IntelliJ IDEA 2023.3 (Ultimate Edition)
_verified_
