### ISSUE TITLE
NPE and other bugs in bpm modeler

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#2126]
See [forum topic](https://forum.jmix.io/t/bpm-addon-receiving-nullpointerexception/3396).
#### I
1. Follow the https://docs.jmix.io/jmix/bpm/getting-started.html manual till creating parameters for Approval task. (No need to create all parameters, `requestNumber` will be enough)
2. Select `requestNumber` according to manual
**ER:** Caption automatically added from previous task
**AR:** Caption is empty (**bug 1**)
3. Close the parameter editor, try edit this parameter again
**ER:** Editor is opened
**AR:** (**bug 2**)
```java
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "io.jmix.bpmflowui.model.ProcessVariableModel.getName()" is null
	at io.jmix.bpmflowui.view.modeler.properties.formdata.FormDataPropertiesFragment.lambda$showFormFieldEditWithProcessVariables$2(FormDataPropertiesFragment.java:405)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at io.jmix.bpmflowui.view.modeler.properties.formdata.FormDataPropertiesFragment.showFormFieldEditWithProcessVariables(FormDataPropertiesFragment.java:405)
	at io.jmix.bpmflowui.view.modeler.properties.formdata.FormDataPropertiesFragment.onFormFieldsTableEdit(FormDataPropertiesFragment.java:385)
```
#### II
After deploying the process and opening it again business key is empty for startEvent (**bug 3**). There is no `businessKey` in bpmn xml too.
<img width="510" alt="изображение" src="https://github.com/jmix-framework/jmix/assets/38808384/46915b0d-c1c4-43a1-b6f5-15b35223dd43">

### Additionally:
(**potential localisation mismatch 4**)Check captions: is the change of "Process variable" to "Business id" planned?
<img width="510" alt="old" src="https://github.com/jmix-framework/jmix/assets/38808384/90c1783e-5097-46aa-bee3-e85ec757504e">
<img width="510" alt="new" src="https://github.com/jmix-framework/jmix/assets/38808384/e4d5b003-3e48-47ed-b720-79521c888e49">

**Comment by KartnDev** [comment]
Seems like "1" point is not bug, this is ok behaviour because businessId was not empty and rule that "auto-fills" caption is Input Variable that would be created should be "new"

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5432-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
