### ISSUE TITLE
Some components not registered with UiComponents

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#2139]
See: https://forum.jmix.io/t/entity-instance-issues-using-uicomponents/3430

For QA:
How does is work

`uiComponents.create` must return a Jmix component
For example `uiComponents.create(Select.class)` should return `JmixSelect`

Affected components:

- `Checkbox`
- `CheckboxGroup`
- `RadioButtonGroup`
- `Image`
- `ListBox`
- `MultiSelectListBox`
- ~~`TabSheet`~~
- `Scroller`
- `SplitLayout`
- `Select`
- `MultiSelectListBox`
- `TextArea`

**Comment by rusiaikinat** [comment]
_Jmix version: 2.0.999-SNAPSHOT_

TabSheet tabSheet = uiComponents.create(TabSheet.class);

```
java.lang.ClassCastException: class io.jmix.flowui.component.tabsheet.JmixTabSheet cannot be cast to class com.vaadin.flow.component.tabs.TabSheet (io.jmix.flowui.component.tabsheet.JmixTabSheet and com.vaadin.flow.component.tabs.TabSheet are in unnamed module of loader 'app')
	at com.company.flow2.view.newentity.NewEntityDetailView.onInit(NewEntityDetailView.java:64)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:222)
	at com.vaadin.flow.component.Component.fireEvent(Component.java:411)
	at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:416)
	at io.jmix.flowui.view.ViewControllerUtils.fireEvent(ViewControllerUtils.java:109)
	at io.jmix.flowui.sys.ViewSupport.fireViewInitEvent(ViewSupport.java:403)
	at io.jmix.flowui.sys.ViewSupport.initView(ViewSupport.java:121)
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.init(JmixSpringInstantiator.java:50)
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.getOrCreate(JmixSpringInstantiator.java:43)
	at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:136)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:133)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:132)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:493)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:474)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:212)
	at com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handle(JavaScriptNavigationStateRenderer.java:78)
	at com.vaadin.flow.component.UI.handleNavigation(UI.java:1785)
	at com.vaadin.flow.component.UI.navigate(UI.java:1170)
	at io.jmix.flowui.view.navigation.ViewNavigationSupport.navigate(ViewNavigationSupport.java:56)
	at io.jmix.flowui.view.navigation.AbstractNavigationProcessor.lambda$processNavigation$28d5aa88$1(AbstractNavigationProcessor.java:57)
```

Not reproduced on 2.0.1

**Comment by Flaurite** [comment]
`JmixTabSheet` does not inherit `TabSheet` so the registration removed from `UiComponents`.

@rusiaikinat check the correct behavior:
```
JmixTabSheet tabSheet = uiComponents.create(JmixTabSheet.class);
TabSheet tabSheet = uiComponents.create(TabSheet.class);
```

**Comment by rusiaikinat** [comment]
for example:
`JmixCheckboxGroup checkboxGroup = (JmixCheckboxGroup) uiComponents.create(CheckboxGroup.class);`
