### ISSUE TITLE
Collection expression changed dialog appears on each user task element selection

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2176]
Jmix version: 2.0.1

1. Create new BPMN process in the runtime modeler
2. For the start process element define an Input dialog process form
3. Add an input dialog parameter with "entity-list" type and "User" entity
4. Add User task element 
5. For the user task element select the "Parallel" multi-instance type, "Process variable" collection source and select the variable created on the previous step
6. Collection expression changed dialog will appear, click "Yes"
7. Select some other process model element, and then select the user task again

AR: the "Collection expression changed" appears again

<img width="768" alt="Screenshot 2023-08-29 at 12 45 34" src="https://github.com/jmix-framework/jmix/assets/7888486/82939d31-920f-43ef-a9fe-384d873b3bb4">

**Comment by KartnDev** [comment]
Also can be reproduce in ant element with "Multi Instance"

**Comment by rusiaikinat** [comment]
step 4 

```
java.lang.NullPointerException: Cannot provide an id for a null item.
    at java.base/java.util.Objects.requireNonNull(Objects.java:235) ~[na:na]
    at com.vaadin.flow.data.provider.DataProvider.getId(DataProvider.java:151) ~[flow-data-24.0.9.jar:24.0.9]
    at com.vaadin.flow.data.provider.KeyMapper.has(KeyMapper.java:105) ~[flow-data-24.0.9.jar:24.0.9]
    at com.vaadin.flow.data.provider.DataCommunicator.lambda$activate$9(DataCommunicator.java:1452) ~[flow-data-24.0.9.jar:24.0.9]
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
    at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541) ~[na:na]
    at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:200) ~[na:na]
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
    at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[na:na]
    at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
    at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
    at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
    at com.vaadin.flow.data.provider.DataCommunicator.activate(DataCommunicator.java:1451) ~[flow-data-24.0.9.jar:24.0.9]
    at com.vaadin.flow.data.provider.DataCommunicator.collectKeysToFlush(DataCommunicator.java:1394) ~[flow-data-24.0.9.jar:24.0.9]
    at com.vaadin.flow.data.provider.DataCommunicator.flush(DataCommunicator.java:1196) ~[flow-data-24.0.9.jar:24.0.9]
    at com.vaadin.flow.data.provider.DataCommunicator.lambda$requestFlush$7258256f$1(DataCommunicator.java:1123) ~[flow-data-24.0.9.jar:24.0.9]
    at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$2(StateTree.java:392) ~[flow-server-24.0.9.jar:24.0.9]
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]

```

**Comment by KartnDev** [comment]
> step 4
> 
> ```
> java.lang.NullPointerException: Cannot provide an id for a null item.
>     at java.base/java.util.Objects.requireNonNull(Objects.java:235) ~[na:na]
>     at com.vaadin.flow.data.provider.DataProvider.getId(DataProvider.java:151) ~[flow-data-24.0.9.jar:24.0.9]
>     at com.vaadin.flow.data.provider.KeyMapper.has(KeyMapper.java:105) ~[flow-data-24.0.9.jar:24.0.9]
>     at com.vaadin.flow.data.provider.DataCommunicator.lambda$activate$9(DataCommunicator.java:1452) ~[flow-data-24.0.9.jar:24.0.9]
>     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
>     at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541) ~[na:na]
>     at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:200) ~[na:na]
>     at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
>     at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[na:na]
>     at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
>     at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
>     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
>     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
>     at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
>     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
>     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
>     at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
>     at com.vaadin.flow.data.provider.DataCommunicator.activate(DataCommunicator.java:1451) ~[flow-data-24.0.9.jar:24.0.9]
>     at com.vaadin.flow.data.provider.DataCommunicator.collectKeysToFlush(DataCommunicator.java:1394) ~[flow-data-24.0.9.jar:24.0.9]
>     at com.vaadin.flow.data.provider.DataCommunicator.flush(DataCommunicator.java:1196) ~[flow-data-24.0.9.jar:24.0.9]
>     at com.vaadin.flow.data.provider.DataCommunicator.lambda$requestFlush$7258256f$1(DataCommunicator.java:1123) ~[flow-data-24.0.9.jar:24.0.9]
>     at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$2(StateTree.java:392) ~[flow-server-24.0.9.jar:24.0.9]
>     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
>     at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
>     at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
>     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
> ```

## In 2.1 (Master branch) Forms is broken:
![image](https://github.com/jmix-framework/jmix/assets/43281522/23881a38-d841-42a8-9d99-53875db58c5b)


3 step cannot be reproduce since forms broken


## In 2.0 release branch all works(All steps works):
![image](https://github.com/jmix-framework/jmix/assets/43281522/9322bebe-e2ca-4cd1-9314-83a4f30dbba7)
