### ISSUE TITLE
IllegalStateException: Failed to install Node

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#2177]
See Studio ticket: https://youtrack.jmix.io/issue/JST-4235/IllegalStateException-Failed-to-install-Node

**Environment:**
Jmix version: 1.5.3
Jmix Studio plugin version: 2.0.2-223
IntelliJ version: IntelliJ IDEA 2022.3.3 (Ultimate Edition)
ubuntu22

**Exception:**
```
java.lang.IllegalStateException: Failed to install Node
	at io.jmix.flowui.devserver.frontend.FrontendTools.installNode(FrontendTools.java:665)
	at io.jmix.flowui.devserver.frontend.FrontendTools.getNodeExecutable(FrontendTools.java:429)
	at io.jmix.flowui.devserver.frontend.FrontendTools.getNodeBinary(FrontendTools.java:1102)
	at io.jmix.flowui.devserver.frontend.FrontendTools.getNodeVersionAndExecutable(FrontendTools.java:637)
	at io.jmix.flowui.devserver.frontend.FrontendTools.validateNodeAndNpmVersion(FrontendTools.java:597)
	at io.jmix.flowui.devserver.frontend.TaskRunNpmInstall.runNpmInstall(TaskRunNpmInstall.java:276)
	at io.jmix.flowui.devserver.frontend.TaskRunNpmInstall.execute(TaskRunNpmInstall.java:175)
	at io.jmix.flowui.devserver.frontend.NodeTasks.execute(NodeTasks.java:988)
	at io.jmix.flowui.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:465)
	at io.jmix.flowui.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.vaadin.flow.server.frontend.installer.InstallationException: Could not extract the Node archive
	at com.vaadin.flow.server.frontend.installer.NodeInstaller.installNode(NodeInstaller.java:261)
	at com.vaadin.flow.server.frontend.installer.NodeInstaller.install(NodeInstaller.java:217)
	at io.jmix.flowui.devserver.frontend.FrontendTools.installNode(FrontendTools.java:663)
	... 16 more
Caused by: com.vaadin.flow.server.frontend.installer.ArchiveExtractionException: Could not extract archive: '/home/tata/.vaadin/node-v18.12.1-linux-x64.tar.gz'
	at com.vaadin.flow.server.frontend.installer.DefaultArchiveExtractor.extract(DefaultArchiveExtractor.java:57)
	at com.vaadin.flow.server.frontend.installer.NodeInstaller.extractFile(NodeInstaller.java:471)
	at com.vaadin.flow.server.frontend.installer.NodeInstaller.installNode(NodeInstaller.java:251)
	... 18 more
Caused by: java.io.EOFException
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.read(GzipCompressorInputStream.java:306)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:738)
	at java.base/java.io.InputStream.read(InputStream.java:218)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1309)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:978)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1282)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:953)
	at com.vaadin.flow.server.frontend.installer.DefaultArchiveExtractor.copyTarFileContents(DefaultArchiveExtractor.java:178)
	at com.vaadin.flow.server.frontend.installer.DefaultArchiveExtractor.extractGzipTarArchive(DefaultArchiveExtractor.java:149)
	at com.vaadin.flow.server.frontend.installer.DefaultArchiveExtractor.extract(DefaultArchiveExtractor.java:54)
	... 20 more

```

**Comment by Fedoseew** [comment]
Also reported on forum: https://forum.jmix.io/t/jmix-studio-2-0-4-232-view-error/3796
