### ISSUE TITLE
NullPointerException: Editing an empty "Process variable" parameter 

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2204]
Jmix version: 2.0.999-SNAPSHOT

**TC**
Create new BPMN process in the runtime modeler
For the start process element define an Input dialog process form
Add an input dialog parameter with "entity-list" type and "User" entity, "Process variable" leave empty -> OK
Edit the created parameter 

**AR**
```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "io.jmix.bpmflowui.model.ProcessVariableModel.getName()" is null
	at io.jmix.bpmflowui.view.modeler.properties.formdata.FormDataPropertiesFragment.lambda$showFormFieldEditWithProcessVariables$2(FormDataPropertiesFragment.java:412)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at io.jmix.bpmflowui.view.modeler.properties.formdata.FormDataPropertiesFragment.showFormFieldEditWithProcessVariables(FormDataPropertiesFragment.java:412)
	at io.jmix.bpmflowui.view.modeler.properties.formdata.FormDataPropertiesFragment.onFormFieldsTableEdit(FormDataPropertiesFragment.java:392)
	at io.jmix.flowui.kit.event.EventBus.fireEvent(EventBus.java:82)
	at io.jmix.flowui.kit.action.BaseAction.actionPerform(BaseAction.java:67)
	at io.jmix.flowui.action.list.ListDataComponentAction.actionPerform(ListDataComponentAction.java:165)
	at io.jmix.flowui.kit.component.button.JmixButtonActionSupport.onButtonClick(JmixButtonActionSupport.java:159)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233)
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:475)
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:292)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447)
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:74)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:438)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:419)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:419)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:320)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:114)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1529)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:399)
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106)

```

**Comment by KartnDev** [comment]
Fixed for Jmix 2.0 (release 2_0 branch)
For 2.1 was fixed already in revision: 1e39b91cf4de12732847f04cd279bb9953c74462 (https://github.com/jmix-framework/jmix-premium/pull/195/files)

**Comment by rusiaikinat** [comment]
Reopened

Create new BPMN process in the runtime modeler
For the start process element define an Input dialog process form
Add an input dialog parameter with "String" entity, "Process variable" leave empty -> OK

Create TaskUser - element define an `Input dialog` form type
Create `Input dialog parameters`
Select Process variable 

AR
```
java.lang.NullPointerException: Cannot provide an id for a null item.
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at com.vaadin.flow.data.provider.DataProvider.getId(DataProvider.java:151)
	at com.vaadin.flow.data.provider.KeyMapper.has(KeyMapper.java:105)
	at com.vaadin.flow.data.provider.DataCommunicator.lambda$activate$9(DataCommunicator.java:1452)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:200)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
```

**Comment by KartnDev** [comment]
Close issue due to new [issue](https://github.com/jmix-framework/jmix/issues/2432), this is irrelevant logics that process variable field inside input dialog parameter window can be not filled
