### ISSUE TITLE
Error on obtaining an access token if user has a row-level role

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2211]
Jmix version: 1.5.3

1. Create a **runtime** row-level role. 
1. Add a row-level policy with **Predicate** type to the role.
1. Assign this row-level role to the user.
1. Try to obtain a REST API access token for the user who has this row-level role.

AR: Exception:

```java.lang.IllegalArgumentException: java.io.NotSerializableException: io.jmix.securitydata.impl.role.provider.DatabaseRowLevelRoleProvider
	at org.springframework.security.oauth2.common.util.DefaultSerializationStrategy.serialize(DefaultSerializationStrategy.java:47) ~[spring-security-oauth2-2.5.2.RELEASE.jar:na]
	at org.springframework.security.oauth2.common.util.SerializationUtils.serialize(SerializationUtils.java:73) ~[spring-security-oauth2-2.5.2.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.token.store.JdbcTokenStore.serializeAuthentication(JdbcTokenStore.java:399) ~[spring-security-oauth2-2.5.2.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.token.store.JdbcTokenStore.storeAccessToken(JdbcTokenStore.java:158) ~[spring-security-oauth2-2.5.2.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices.createAccessToken(DefaultTokenServices.java:134) ~[spring-security-oauth2-2.5.2.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices$$FastClassBySpringCGLIB$$5a1f25c.invoke(<generated>) ~[spring-security-oauth2-2.5.2.RELEASE.jar:na]
```

See [forum topic](https://forum.jmix.ru/t/notserializableexception-databaserowlevelroleprovider/1019)

Sample project (try to get token for user **alice** and password **1**): [role-ser-problem-java.zip](https://github.com/jmix-framework/jmix/files/12550856/role-ser-problem-java.zip)

**Comment by gorbunkov** [comment]
It seems that the problem is that we use the field of enclosing class (`io.jmix.securitydata.impl.role.provider.DatabaseRowLevelRoleProvider#scriptEvaluator`) in the lambda body:

```java
    public RowLevelBiPredicate<Object, ApplicationContext> createPredicateFromScript(String script) {
        return (entity, applicationContext) -> {
            String modifiedScript = script.replace("{E}", "__entity__");
            Map<String, Object> arguments = new HashMap<>();
            arguments.put("__entity__", entity);
            arguments.put("applicationContext", applicationContext);
            return Boolean.TRUE.equals(scriptEvaluator.evaluate(new StaticScriptSource(modifiedScript), arguments));
        };
    }
```

This causes the serizalization of the `DatabaseRowLevelRoleProvider`. We can try getting the scriptEvaluator from the ApplicationContext inside the lambda function  body.
