### ISSUE TITLE
Jmix UI Samples. NoClassDefFoundError when you click the Export button

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2222]
Open https://demo.jmix.io/sampler/#main/6/sample?id=pivottable-data-export
Click Export button

AR
```
java.lang.NoClassDefFoundError: Could not initialize class sun.font.SunFontManager
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(Unknown Source)
	at java.desktop/sun.java2d.SunGraphics2D.getFontMetrics(Unknown Source)
	at io.jmix.gridexportui.exporter.excel.ExcelAutoColumnSizer.getFontMetrics(ExcelAutoColumnSizer.java:70)
	at io.jmix.gridexportui.exporter.excel.ExcelAutoColumnSizer.notifyCellValue(ExcelAutoColumnSizer.java:110)
	at io.jmix.pivottable.component.impl.PivotExcelExporter.updateColumnSize(PivotExcelExporter.java:323)
	at io.jmix.pivottable.component.impl.PivotExcelExporter.createRows(PivotExcelExporter.java:256)
	at io.jmix.pivottable.component.impl.PivotExcelExporter.exportPivotTable(PivotExcelExporter.java:188)
	at io.jmix.pivottable.component.impl.PivotTableExtensionImpl.exportTableToXls(PivotTableExtensionImpl.java:65)
	at io.jmix.sampler.screen.ui.pivottable.dataexport.PivotTableDataExportSample.onExportBtnClick(PivotTableDataExportSample.java:33)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.component.impl.AbstractComponent.publish(AbstractComponent.java:85)
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:78)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by gorbunkov** [comment]
It is probably related to https://github.com/jmix-framework/jmix/issues/1107
