### ISSUE TITLE
Implement support for chart in XLSX reports

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#2311]
# Description
Previously, YARG had the ability to create an XLSX report with a chart, the data for which is taken from a table, example:

![image](https://github.com/jmix-framework/jmix/assets/47520144/2006a3dc-87b4-47de-aa09-e41f9218dcd5)

To do this, it was necessary to create a report template and link the table to the diagram.

> To process the data as an Excel chart, create an empty band in the report structure and a named region with the same name in the template. Then create a chart inside this named region and refer to related bands using the Select data button in the chart context menu. If your chart data is in a continuous range of cells, select any cell in that range. Your chart will include all the data in the range. If your data isn’t in a continuous range, select nonadjacent cells or ranges.

**Example report:**
<img width="1314" alt="image" src="https://github.com/jmix-framework/jmix/assets/47520144/6d339561-84d2-4697-9160-113cd3eb88cc">

Currently, the report with the diagram fails with an error because it cannot determine the range:

**Error:**
```
java.lang.NullPointerException: Cannot invoke "io.jmix.reports.yarg.formatters.impl.xlsx.Range.getSheet()" because "range" is null
	at io.jmix.reports.yarg.formatters.impl.xlsx.Range.intersects(Range.java:193) ~[jmix-reports-2.1.3.jar:na]
	at io.jmix.reports.yarg.formatters.impl.XlsxFormatter.updateCharts(XlsxFormatter.java:275) ~[jmix-reports-2.1.3.jar:na]
	at io.jmix.reports.yarg.formatters.impl.XlsxFormatter.renderDocument(XlsxFormatter.java:126) ~[jmix-reports-2.1.3.jar:na]
	at io.jmix.reports.yarg.reporting.Reporting.generateReport(Reporting.java:132) ~[jmix-reports-2.1.3.jar:na]
	at io.jmix.reports.yarg.reporting.Reporting.runReport(Reporting.java:91) ~[jmix-reports-2.1.3.jar:na]
	at io.jmix.reports.yarg.reporting.Reporting.runReport(Reporting.java:114) ~[jmix-reports-2.1.3.jar:na]
	at io.jmix.reports.runner.impl.ReportRunnerImpl.createReportDocumentInternal(ReportRunnerImpl.java:134) ~[jmix-reports-2.1.3.jar:na]
	at io.jmix.reports.runner.impl.ReportRunnerImpl.run(ReportRunnerImpl.java:82) ~[jmix-reports-2.1.3.jar:na]
	at io.jmix.reportsflowui.runner.impl.UiReportRunnerImpl.runAndShow(UiReportRunnerImpl.java:111) ~[jmix-reports-flowui-2.1.3.jar:na]
	at io.jmix.reportsflowui.runner.FluentUiReportRunner.runAndShow(FluentUiReportRunner.java:184) ~[jmix-reports-flowui-2.1.3.jar:na]
	at io.jmix.reportsflowui.view.report.ReportListView.onReportsDataGridRunReport(ReportListView.java:159) ~[jmix-reports-flowui-2.1.3.jar:na]
	at io.jmix.flowui.kit.event.EventBus.fireEvent(EventBus.java:82) ~[jmix-flowui-kit-2.1.3.jar:na]
	at io.jmix.flowui.kit.action.BaseAction.actionPerform(BaseAction.java:67) ~[jmix-flowui-kit-2.1.3.jar:na]
	at io.jmix.flowui.action.list.ListDataComponentAction.actionPerform(ListDataComponentAction.java:165) ~[jmix-flowui-2.1.3.jar:na]
	at io.jmix.flowui.kit.component.button.JmixButtonActionSupport.onButtonClick(JmixButtonActionSupport.java:159) ~[jmix-flowui-kit-2.1.3.jar:na]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233) ~[flow-server-24.1.14.jar:24.1.14]
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:475) ~[flow-server-24.1.14.jar:24.1.14]
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:292) ~[flow-server-24.1.14.jar:24.1.14]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447) ~[flow-server-24.1.14.jar:24.1.14]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447) ~[flow-server-24.1.14.jar:24.1.14]
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62) ~[flow-server-24.1.14.jar:24.1.14]
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:74) ~[flow-server-24.1.14.jar:24.1.14]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:459) ~[flow-server-24.1.14.jar:24.1.14]
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$2(ServerRpcHandler.java:440) ~[flow-server-24.1.14.jar:24.1.14]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
```

**Test case:**
- Start the Jmix project with Reports Add-on
- Import the Chart report
- Run the report with the `(error) Chart_template_1.xlsx` template.

**Result:**
<img width="1293" alt="image" src="https://github.com/jmix-framework/jmix/assets/47520144/981e0e79-038d-4cd8-82f9-bd274a512bd3">

**Report:**
[Test chart.zip](https://github.com/jmix-framework/jmix/files/14871733/Test.chart.zip)

---
## Documentation:

**XLSX Template:**
https://docs.jmix.io/1.x/jmix/1.5/reports/creation/templates.html#template_xls

**YARG:**
https://www.jmix.io/cuba-blog/report-generator/

**Comment by breakingfox** [comment]
Note to QA:
Problem was related to Google Sheets anchors for charts.
Therefore it's needed to test templates created in LibreOffice, Google Sheets and Microsoft Excel if possible.
