### ISSUE TITLE
Support for menu merging

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2347]
Currently, the following menu.xml configuration 

```
<menu-config xmlns="http://jmix.io/schema/flowui/menu">
    <menu id="application" title="msg://com.company.demo/menu.application.title" opened="true">
        <item view="demo_User.list" title="msg://com.company.demo.view.user/UserListView.title"/>
        <item view="demo_Order.list" title="msg://com.company.demo.view.order/orderListView.title"/>
    </menu>
    <menu id="system" title="msg://com.company.demo/menu.system.title">
        <item view="demo_SandboxView" title="msg://com.company.demo.view.sandbox/sandboxView.title"/>
    </menu>
</menu-config>
```

produces the following exception:

```
java.lang.IllegalArgumentException: Menu item with id "system" already exists
	at io.jmix.flowui.kit.component.main.ListMenu.checkItemIdDuplicate(ListMenu.java:407)
	at io.jmix.flowui.kit.component.main.ListMenu.createMenuRecursively(ListMenu.java:210)
	at io.jmix.flowui.kit.component.main.ListMenu.addMenuItem(ListMenu.java:102)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.jmix.flowui.menu.ListMenuBuilder.build(ListMenuBuilder.java:84)
```

ER:

1. Content of `menu` elements with the same `id` is merged similar to Classic UI
2. Some `order` definition may be needed in case of merging

**Comment by MaxKatyshev** [comment]
_Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT5973-233
IntelliJ version: IntelliJ IDEA 2023.3.2 (Community Edition)_
verified
