### ISSUE TITLE
UnitOfWorkQueryValueHolder is not wrapped properly

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#2461]
See forum [topic](https://forum.jmix.io/t/onetoone-plan-fetch/3266).
### Steps:
1. Download and run project: [unfetch.zip](https://github.com/jmix-framework/jmix/files/13343070/unfetch.zip)
2. Open Blank Screen
3. Press upper button, then bottom button
**ER:** No exceptions
**AR:**
```java
java.lang.IllegalStateException: Cannot get unfetched attribute [infoEntity] from detached object com.company.jmix_unfetch.entity.LastEntity-92a4bf42-6755-3b2a-c5ba-2badd96853f2 [detached].
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.throwUnfetchedAttributeException(UnitOfWorkValueHolder.java:326)
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:106)
	at com.company.jmix_unfetch.entity.LastEntity._persistence_get_infoEntity(LastEntity.java)
	at com.company.jmix_unfetch.entity.LastEntity.getInfoEntity(LastEntity.java:25)
	at com.company.jmix_unfetch.screen.blank.BlankScreen.onReadClick(BlankScreen.java:49)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
```
### Cause: 
UnitOfWorkQueryValueHolder is not wrapped for `infoEntity` property in deeply nested entity `LastEntity`, because it is already loaded despite absence in fetch plan.

see `io.jmix.eclipselink.impl.lazyloading.JpaLazyLoadingListener#processValueHolders`

### Possible solutions:
a. Prevent excessive loading
b. Modify wrapping logic
c. leave as is if there are no "good" solutions

**Comment by dtaimanov** [comment]
May be solved by #3507. Need to be checked after it will be merged.

**Comment by SergeiAksenov2** [comment]
Demo project Jmix 2.8.999: 

[T2461-j28999.zip](https://github.com/user-attachments/files/26749607/T2461-j28999.zip)

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.8.999-SNAPSHOT
Jmix Studio Plugin Version: 2.8.0-261
IntelliJ version: IntelliJ IDEA 2026.1.1 Preview
