### ISSUE TITLE
Remove double-click handler in decision tables list view

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2475]
Jmix: 2.1.0

Double-click on decision tables grid row causes an exception:

```
java.util.NoSuchElementException: null
	at java.base/java.util.Collections$EmptyIterator.next(Collections.java:4310) ~[na:na]
	at io.jmix.bpmflowui.view.dmndecisiontable.DmnDecisionTableListView.openInModeler(DmnDecisionTableListView.java:172) ~[jmix-bpm-flowui-2.1.0.jar:na]
	at io.jmix.bpmflowui.view.dmndecisiontable.DmnDecisionTableListView.lambda$onBeforeShow$9b3fb906$1(DmnDecisionTableListView.java:87) ~[jmix-bpm-flowui-2.1.0.jar:na]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233) ~[flow-server-24.1.12.jar:24.1.12]
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:475) ~[flow-server-24.1.12.jar:24.1.12]
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:292) ~[flow-server-24.1.12.jar:24.1.12]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447) ~[flow-server-24.1.12.jar:24.1.12]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
```

We should remove this double-click handler, because we don't use this approach (open the details view by double click) anywhere in the framework. In future releases some mechanism for opening items be some action in datagrid row will appear.

See [forum](https://forum.jmix.io/t/small-bug-in-decision-tables-view/3956).

**Comment by KartnDev** [comment]
Double click listener removed
