### ISSUE TITLE
Error starting application if additional data store has no entities

### ISSUE THREAD

**Issue by Gasloff** [jmix-framework/jmix#2482]
Jmix 2.1.0

Create new Java project
Add additional datastore (tested for PostgreSQL & MSSQL)
Run application
AR: bootRun fails
```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-11-16T11:50:47.729+04:00 ERROR 31172 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pglEntityManagerFactory' defined in class path resource [com/company/untitled31/PglStoreConfiguration.class]: Index 0 out of bounds for length 0
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1158) ~[spring-context-6.0.12.jar:6.0.12]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932) ~[spring-context-6.0.12.jar:6.0.12]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.12.jar:6.0.12]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.4.jar:3.1.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) ~[spring-boot-3.1.4.jar:3.1.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[spring-boot-3.1.4.jar:3.1.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-3.1.4.jar:3.1.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-3.1.4.jar:3.1.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-3.1.4.jar:3.1.4]
	at com.company.untitled31.Untitled31Application.main(Untitled31Application.java:32) ~[main/:na]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[na:na]
	at java.base/java.util.Objects.checkIndex(Objects.java:359) ~[na:na]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[na:na]
	at org.springframework.core.annotation.AnnotationTypeMappings.get(AnnotationTypeMappings.java:159) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.core.annotation.TypeMappedAnnotation.of(TypeMappedAnnotation.java:618) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.core.annotation.MergedAnnotation.of(MergedAnnotation.java:612) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.core.type.classreading.MergedAnnotationReadingVisitor.visitEnd(MergedAnnotationReadingVisitor.java:98) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.asm.ClassReader.readElementValues(ClassReader.java:3010) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.asm.ClassReader.accept(ClassReader.java:610) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.asm.ClassReader.accept(ClassReader.java:426) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:48) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:122) ~[spring-core-6.0.12.jar:6.0.12]
	at org.springframework.orm.jpa.persistenceunit.PersistenceManagedTypesScanner.scanPackage(PersistenceManagedTypesScanner.java:113) ~[spring-orm-6.0.12.jar:6.0.12]
	at org.springframework.orm.jpa.persistenceunit.PersistenceManagedTypesScanner.scan(PersistenceManagedTypesScanner.java:90) ~[spring-orm-6.0.12.jar:6.0.12]
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.buildDefaultPersistenceUnitInfo(DefaultPersistenceUnitManager.java:537) ~[spring-orm-6.0.12.jar:6.0.12]
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.readPersistenceUnitInfos(DefaultPersistenceUnitManager.java:515) ~[spring-orm-6.0.12.jar:6.0.12]
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.preparePersistenceUnitInfos(DefaultPersistenceUnitManager.java:445) ~[spring-orm-6.0.12.jar:6.0.12]
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.afterPropertiesSet(DefaultPersistenceUnitManager.java:429) ~[spring-orm-6.0.12.jar:6.0.12]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:339) ~[spring-orm-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817) ~[spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[spring-beans-6.0.12.jar:6.0.12]
	... 16 common frames omitted

```

### Changes
~~`RuntimeException` will be thrown If build-time generated by jmix gradle plugin `persistence.xml` has been moved to another directory. 
If you have changed the location of `persistence.xml`, please override `io.jmix.data.impl.JmixEntityManagerFactoryBean#getPersistenceXmlPath` in [store configuration](https://docs.jmix.io/jmix/data-model/data-stores.html#additional).~~

Discussed again and decided to log more detailed warning message instead of `RuntimeException`. It will help to avoid unnecessary problems in case of complex project with empty data store and custom properties file location.

**Comment by knstvk** [comment]
The framework doesn't create {store}-persistence.xml if there are no JPA entities defined for this data store. It leads to search for entities in classpath (see `io.jmix.data.impl.JmixBaseEntityManagerFactoryBean#setupPersistenceUnit`) which is reflected in the log:
```
2023-11-14 10:46:34.713  WARN 18224 --- [main] i.j.d.i.JmixBaseEntityManagerFactoryBean : Cannot find persistence.xml for 'add' store. Falling back to classpath scan for entity classes.
```

This in turn can lead to error starting the application if some entities of the main data store contain references to entities from add-ons, i.e. to entities of the main store defined outside current project. For example:

```
2023-11-14 10:46:35.126 ERROR 18224 --- [main] i.j.d.impl.JmixEntityManagerFactoryBean  : Failed to initialize JPA EntityManagerFactory: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.7.9.6-jmix): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [add] failed.
Internal Exception: Exception [EclipseLink-7250] (Eclipse Persistence Services - 2.7.9.6-jmix): org.eclipse.persistence.exceptions.ValidationException
Exception Description: [class com.company.additionaldatastore.entity.NewEntity] uses a non-entity [class io.jmix.securitydata.entity.ResourceRoleEntity] as target entity in the relationship attribute [field role].
2023-11-14 10:46:35.128  WARN 18224 --- [main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'addEntityManagerFactory' defined in class path resource [com/company/additionaldatastore/AddStoreConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.7.9.6-jmix): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [add] failed.
Internal Exception: Exception [EclipseLink-7250] (Eclipse Persistence Services - 2.7.9.6-jmix): org.eclipse.persistence.exceptions.ValidationException
Exception Description: [class com.company.additionaldatastore.entity.NewEntity] uses a non-entity [class io.jmix.securitydata.entity.ResourceRoleEntity] as target entity in the relationship attribute [field role].
2023-11-14 10:46:35.191 ERROR 18224 --- [main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'addEntityManagerFactory' defined in class path resource [com/company/additionaldatastore/AddStoreConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.7.9.6-jmix): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [add] failed.
Internal Exception: Exception [EclipseLink-7250] (Eclipse Persistence Services - 2.7.9.6-jmix): org.eclipse.persistence.exceptions.ValidationException
Exception Description: [class com.company.additionaldatastore.entity.NewEntity] uses a non-entity [class io.jmix.securitydata.entity.ResourceRoleEntity] as target entity in the relationship attribute [field role].
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.29.jar:5.3.29]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.29.jar:5.3.29]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.29.jar:5.3.29]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.29.jar:5.3.29]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.29.jar:5.3.29]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.29.jar:5.3.29]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.29.jar:5.3.29]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1157) ~[spring-context-5.3.29.jar:5.3.29]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:911) ~[spring-context-5.3.29.jar:5.3.29]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.29.jar:5.3.29]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.15.jar:2.7.15]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.15.jar:2.7.15]
...
```

I think we should always generate {store}-persistence.xml file for any JPA data store, and fail fast if it doesn't exist instead of falling back to default classpath scanning.
