### ISSUE TITLE
Error when adding click listener to textItem of dropdownButton 

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#2614]
### Environment

Jmix version: 2.1.1

### Steps To Reproduce

- Add textItem to a dropdownButton:
```
<dropdownButton id="additionalBtn" text="msg://additionalMenu" icon="COG">
    <items>
        <!-- ... -->
        <textItem id="testItem" text="Test"/>
    </items>
</dropdownButton>
```

- Generate click listener with Studio:
```
@Subscribe("testItem")
public void onTestItemClick(final DropdownButtonItem.ClickEvent event) {
    System.out.println(">>>> test");
}
```

- Run the app and open the view

### Current Behavior

Exception occurs:
```
java.lang.ClassCastException: class io.jmix.flowui.kit.component.dropdownbutton.AbstractDropdownButton$TextItemImpl cannot be cast to class com.vaadin.flow.component.Component (io.jmix.flowui.kit.component.dropdownbutton.AbstractDropdownButton$TextItemImpl and com.vaadin.flow.component.Component are in unnamed module of loader 'app')
	at io.jmix.flowui.component.UiComponentUtils.getComponentRecursively(UiComponentUtils.java:97) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.component.UiComponentUtils.getComponentRecursively(UiComponentUtils.java:91) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.component.UiComponentUtils.findComponent(UiComponentUtils.java:66) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.sys.ViewControllerDependencyInjector.findMethodTarget(ViewControllerDependencyInjector.java:672) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.sys.ViewControllerDependencyInjector.initSubscribeListeners(ViewControllerDependencyInjector.java:415) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.sys.ViewControllerDependencyInjector.inject(ViewControllerDependencyInjector.java:82) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.sys.ViewControllerDependencyManager.inject(ViewControllerDependencyManager.java:40) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.sys.ViewSupport.initView(ViewSupport.java:119) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.init(JmixSpringInstantiator.java:65) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.getOrCreate(JmixSpringInstantiator.java:58) ~[jmix-flowui-2.1.1.jar:na]
	at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:136) ~[flow-server-24.1.12.jar:24.1.12]
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.createRouteTarget(JmixSpringInstantiator.java:49) ~[jmix-flowui-2.1.1.jar:na]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:131) ~[flow-server-24.1.12.jar:24.1.12]
	at java.base/java.util.Optional.orElseGet(Optional.java:364) ~[na:na]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:130) ~[flow-server-24.1.12.jar:24.1.12]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:479) ~[flow-server-24.1.12.jar:24.1.12]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:460) ~[flow-server-24.1.12.jar:24.1.12]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:210) ~[flow-server-24.1.12.jar:24.1.12]
	at com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handle(JavaScriptNavigationStateRenderer.java:78) ~[flow-server-24.1.12.jar:24.1.12]
	at com.vaadin.flow.component.UI.handleNavigation(UI.java:1857) ~[flow-server-24.1.12.jar:24.1.12]
	at com.vaadin.flow.component.UI.renderViewForRoute(UI.java:1820) ~[flow-server-24.1.12.jar:24.1.12]
	at com.vaadin.flow.component.UI.lambda$connectClient$83bb1bf7$1(UI.java:1732) ~[flow-server-24.1.12.jar:24.1.12]
	at com.vaadin.flow.component.UI.connectClient(UI.java:1742) ~[flow-server-24.1.12.jar:24.1.12]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at ...
```

### Other problems to consider
- A click handler for componentItem leads to the same exception 
- A click handler for actionItem leads to `io.jmix.core.DevelopmentException: Unable to find @Subscribe target changePasswordItem in UserListView`
- If you add a button inside componentItem and generate the click listener for this button, you will get `io.jmix.core.DevelopmentException: Unable to find @Subscribe target testBtn in UserListView`

**Comment by KremnevDmitry** [comment]
- Incorrect handler generation for `TextItem`/`ComponentItem` is a studio problem: https://youtrack.jmix.io/issue/JST-4536/Incorrect-event-handler-generation-for-dropdownButtonItems
- ActionItem does not support click listener. The ability to add it has been removed
- Subscription to events for child components for item components has never been implemented
  After an investigation, it was concluded that the implementation of the functionality is impossible as part of a bugfix release; it will be implemented later in a patch release. The corresponding issue has beed created:

**Comment by MaxKatyshev** [comment]
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5881-233
IntelliJ version: IntelliJ IDEA 2023.3 (Ultimate Edition)
verified
