### ISSUE TITLE
Misleading error message if Tab has no children

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#2619]
### Environment

Jmix version: 2.1.1

### Steps To Reproduce

Create a tabSheet tab without children:
```
<tabSheet id="tabSheet" width="100%" height="100%">
    <tab id="myTab"/>
</tabSheet>
```

Suppose you are going to add the content programmatically `onInit()`.

### Current Behavior

Exception is thrown:
```
io.jmix.flowui.exception.GuiDevelopmentException: Tab should have only one child component
	at io.jmix.flowui.xml.layout.loader.container.TabSheetLoader$TabLoader.createSubComponents(TabSheetLoader.java:106) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.xml.layout.loader.container.TabSheetLoader$TabLoader.initComponent(TabSheetLoader.java:95) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.xml.layout.loader.container.TabSheetLoader.createTabs(TabSheetLoader.java:58) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.xml.layout.loader.container.TabSheetLoader.initComponent(TabSheetLoader.java:42) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.xml.layout.loader.container.AbstractContainerLoader.createSubComponents(AbstractContainerLoader.java:49) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.xml.layout.loader.ViewLoader.createContent(ViewLoader.java:45) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.xml.layout.loader.LayoutLoader.createViewContent(LayoutLoader.java:139) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.sys.ViewSupport.loadWindowFromXml(ViewSupport.java:423) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.sys.ViewSupport.initView(ViewSupport.java:110) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.init(JmixSpringInstantiator.java:65) ~[jmix-flowui-2.1.1.jar:na]
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.getOrCreate(JmixSpringInstantiator.java:58) ~[jmix-flowui-2.1.1.jar:na]
	at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:136) ~[flow-server-24.1.12.jar:24.1.12]
...
```

### Expected Behavior

Either the exception should read "a single" child component, or better it should allow defining a tab without content in XML.
Also, add the tab id to the exception message.

**Comment by KremnevDmitry** [comment]
It isn't possible to add a tab without content (Vaadin's limitation).
