### ISSUE TITLE
No SecurityContext available when process websocket "Connect" requests

### ISSUE THREAD

**Issue by yuriy-khrebtov** [jmix-framework/jmix#2622]
### Environment

Jmix version: 1.6

### Bug Description

Current user authentication is not set when websocket "Connect" request from frontend is processed.

### Steps To Reproduce

It's difficult to reproduce because the requests between frontend and backend processed in different order from one time to another. The bug was discovered in the case:
1. Create a dto entity
2. Create a browse screen for the entity with tree data grid
3. Subscribe to UiRefreshEvent - run background task where tree data grid items and selection are updated in `done` method

### Current Behavior

After several refreshes of the page using F5 the exception is thrown:
![image](https://github.com/jmix-framework/jmix/assets/142792860/c2c29148-3a29-4eb3-87cf-953b4b36d6a4)
```
java.lang.IllegalStateException: Authentication is not set. Use SystemAuthenticator in non-user requests like schedulers or asynchronous calls.
	at io.jmix.core.security.impl.CurrentAuthenticationImpl.getAuthentication(CurrentAuthenticationImpl.java:47) ~[jmix-core-1.6.999-SNAPSHOT.jar:na]
	at io.jmix.core.security.impl.CurrentAuthenticationImpl.getLocale(CurrentAuthenticationImpl.java:73) ~[jmix-core-1.6.999-SNAPSHOT.jar:na]
	at io.jmix.core.MetadataTools.format(MetadataTools.java:173) ~[jmix-core-1.6.999-SNAPSHOT.jar:na]
	at io.jmix.ui.component.valueprovider.StringPresentationValueProvider.apply(StringPresentationValueProvider.java:43) ~[jmix-ui-1.6.999-SNAPSHOT.jar:na]
	at io.jmix.ui.component.valueprovider.StringPresentationValueProvider.apply(StringPresentationValueProvider.java:26) ~[jmix-ui-1.6.999-SNAPSHOT.jar:na]
	at com.vaadin.ui.Grid$Column.generateRendererValue(Grid.java:1140) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.ui.Grid$Column.access$1100(Grid.java:871) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.ui.Grid$Column$1.generateData(Grid.java:920) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.data.provider.DataCommunicator.getDataObject(DataCommunicator.java:510) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:395) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:368) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:118) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:164) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.server.communication.AtmospherePushConnection.connect(AtmospherePushConnection.java:263) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.server.communication.PushHandler.lambda$new$0(PushHandler.java:114) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:247) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.server.communication.PushHandler.onConnect(PushHandler.java:541) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:100) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:76) ~[vaadin-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225) ~[atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114) ~[atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67) ~[atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297) ~[atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594) ~[atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:224) ~[atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:264) ~[atmosphere-runtime-2.4.30-1-cuba.jar:2.4.30-1-cuba]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:131) ~[tomcat-embed-websocket-9.0.83.jar:9.0.83]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:970) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

```

Looks like the error appears when there is a data that is pending to be transferred to frontend (in described scenario - deselection of the grid during` setItems(...)` call) and there is websocket connection request incoming from frontend (request to connect appears every time we refresh the page). In this case after connection is successfully established the data will be also transferred to frontend in the same request. As the request is made through websocket protocol, there is no SecurityContext provided for the request thread. If authentication is used when the data is being prepared for transfer (in the described case - metadataTools tries to format a value using current locale), the transfer fails.

### Expected Behavior

Successful refresh of the page and completion of background task.

### Ideas
Seems that setting of SecurityContext in Atmosphere interceptor solves the problem but it should be explored for consequences:
```
@Component
public class SecurityContextHolderAtmosphereInterceptor implements AtmosphereInterceptor {

    @EventListener
    public void onReady(ApplicationReadyEvent event) {
        Universe.framework().interceptor(this);
    }

    @Override
    public Action inspect(AtmosphereResource atmosphereResource) {
        Object context = atmosphereResource.getRequest().getSession().getAttribute(
                HttpSessionSecurityContextRepository.SPRING_SECURITY_CONTEXT_KEY);
        if (context instanceof SecurityContext) {
            SecurityContextHolder.setContext((SecurityContext) context);
        }
        return Action.CONTINUE;
    }

    @Override
    public void postInspect(AtmosphereResource atmosphereResource) {
        SecurityContext context = SecurityContextHolder.getContext();
        atmosphereResource.getRequest().getSession().setAttribute(
                HttpSessionSecurityContextRepository.SPRING_SECURITY_CONTEXT_KEY, context);
        SecurityContextHolder.clearContext();
    }

    @Override
    public void destroy() {

    }

    @Override
    public void configure(AtmosphereConfig config) {

    }
}
```
### Example project

Example project is attached (TestDtoEntityBrowse screen). There are delays in the background task that force this error to appear more frequently. 
[websocket-auth-issue.zip](https://github.com/jmix-framework/jmix/files/13674378/websocket-auth-issue.zip)

**Comment by yuriy-khrebtov** [comment]
Same issue can be reproduced on 2.x version if we subscribe to BeforeShowEvent instead of UiRefreshEvent (because we don't have the last one in that versions). Custom interceptor works well here too.
