### ISSUE TITLE
@Value annotation in screen controllers supports only String

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2713]
### Environment

Jmix version: 1.5.5

### Bug Description

A description of what the bug is.

### Steps To Reproduce

1. Define a custom int app property in `application.properties`, e.g.: `app.test-int=10`
2. Inject it in a screen using `@Value`, e.g.: 
```
@Value("${app.test-int}")
private Integer appTestInt;
```

### Current Behavior

```
Caused by: java.lang.IllegalArgumentException: Can not set java.lang.Integer field com.company.demo.screen.sandbox.SandboxScreen.appTestInt to java.lang.String

	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:na]
	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[na:na]
	at java.base/java.lang.reflect.Field.set(Field.java:799) ~[na:na]
	at io.jmix.ui.sys.UiControllerDependencyInjector.assignValue(UiControllerDependencyInjector.java:770) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.sys.UiControllerDependencyInjector.doInjection(UiControllerDependencyInjector.java:474) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.sys.UiControllerDependencyInjector.injectValues(UiControllerDependencyInjector.java:262) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.sys.UiControllerDependencyInjector.inject(UiControllerDependencyInjector.java:99) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.sys.UiControllerDependencyManager.inject(UiControllerDependencyManager.java:61) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:212) ~[jmix-ui-1.5.5.jar:na]
```

Hint: `UiControllerDependencyInjector#getInjectedInstance` uses `AutowireCapableBeanFactory#resolveEmbeddedValue` for `@Value` annotation and it is always returns `String`.

### Expected Behavior

All value types supported by `@Value` can be used. 

---

Source: [forum](https://forum.jmix.io/t/integer-value-injection-not-working/4198/3)

**Comment by ilushaaa** [comment]
https://github.com/jmix-framework/jmix/commit/66c06c687eddef0d46133448ed06c27007cdd0bd

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Ultimate Edition)
![inject value](https://github.com/jmix-framework/jmix/assets/158277660/5c9fc15d-ac25-41b1-ad31-f467e1341750)
