### ISSUE TITLE
Icon attribute in menu.xml does not support Vaadin icon collection naming

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2715]
### Environment
Jmix version: 2.1.2

### Bug Description

`MenuConfig` loads icon from XML as name of VaadinIcon enum value. However, Studio additionally offers to enter value with "vaadin:" prefix.

For 2.1.x version only `VaadinIcon` enum can be supported. It means that icons from other factories cannot be used, e.g. `icon="lumo:bell"` won't work.

~~For 2.2.x we can support all factories using `setPrefixComponent()` method, see:~~
~~1) `ComponentUtils#parseIcon()`~~
~~2) `ListMenu.MenuItem#setPrefixComponent()`~~
Moved to https://github.com/jmix-framework/jmix/issues/2746

### Steps To Reproduce

1. Add to menu `icon="vaadin:factory"`

### Current Behavior
```
java.lang.IllegalArgumentException: No enum constant com.vaadin.flow.component.icon.VaadinIcon.vaadin:factory
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at com.vaadin.flow.component.icon.VaadinIcon.valueOf(VaadinIcon.java:28)
	at io.jmix.flowui.menu.ListMenuBuilder.createMenuBar(ListMenuBuilder.java:128)
	at io.jmix.flowui.menu.ListMenuBuilder.createListMenu(ListMenuBuilder.java:95)
	at io.jmix.flowui.menu.ListMenuBuilder.build(ListMenuBuilder.java:83)
	at io.jmix.flowui.component.main.JmixListMenu.loadMenuConfig(JmixListMenu.java:77)
	at io.jmix.flowui.xml.layout.loader.component.ListMenuLoader.loadMenuConfig(ListMenuLoader.java:44)
	at io.jmix.flowui.xml.layout.loader.component.ListMenuLoader.loadComponent(ListMenuLoader.java:30)
```
### QA
Check:
1) `<menu ... icon="FACTORY">`
2)  `<menu ... icon="vaadin:factory">`
3) `<item ... icon="FACTORY">`
4) `<item ... icon="vaadin:factory">`

**Comment by MaxKatyshev** [comment]
IntelliJ IDEA 2023.3.2 (Community Edition)
io.jmix.studio (2.2.SNAPSHOT6012-232)
Jmix version: 2.1.999-SNAPSHOT
verified
