### ISSUE TITLE
Save Shortcut saves twice

### ISSUE THREAD

**Issue by alferink** [jmix-framework/jmix#2845]
### Environment

Jmix version: 2.1.3

### Bug Description

I have registered a keyboard shortcut for save. When I use the shortcut the action is called twice and the entity is saved twice. The result is also that the back navigation is broken. This happens also for the close shortcut.

### Steps To Reproduce

I have created shortcuts for save and close in applications.properties (see [shortcut-demo.zip](https://github.com/jmix-framework/jmix/files/14167722/shortcut-demo.zip)):
``` 
jmix.ui.view.save-shortcut=CONTROL-ENTER  
jmix.ui.view.close-shortcut=ESCAPE
```

 1. Open the (customer) list view
 2. Select an entity in the grid and click edit
 3. The detail view is opened
 4. Press CONTROL-ENTER

**Acutal behaviour:** The entity is saved (twice), the view is closed and the main view is displayed.
**Expected behaviour:** The entity should be saved only once and instead of the main view the list view should be displayed.

### First analysis

I have set a breakpoint in DetailSaveAction.execute.
After I have pressed CONTROL-ENTER, the execute method is called twice. In the selection call there is no backwards-url, so it is not possible to navigate back to the list view.

There seems to be 1 call from the action and 1 call from the button:

**First call**
```
"http-nio-8080-exec-13@16496" daemon prio=5 tid=0x47 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at io.jmix.flowui.action.view.DetailSaveCloseAction.execute(DetailSaveCloseAction.java:66)
	  at io.jmix.flowui.action.view.ViewAction.actionPerform(ViewAction.java:140)
	  at io.jmix.flowui.kit.component.button.JmixButtonActionSupport.onButtonClick(JmixButtonActionSupport.java:159)
	  at io.jmix.flowui.kit.component.button.JmixButtonActionSupport$$Lambda$2143/0x0000000801917c78.onComponentEvent(Unknown Source:-1)
	  at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233)
	  at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:222)
	  at com.vaadin.flow.component.Component.fireEvent(Component.java:411)
	  at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:416)
	  at com.vaadin.flow.component.ClickNotifier.lambda$addClickShortcut$681279f$1(ClickNotifier.java:143)
	  at com.vaadin.flow.component.ClickNotifier$$Lambda$2451/0x000000080196d230.onShortcut(Unknown Source:-1)

```

**Second call**
```
"http-nio-8080-exec-13@16496" daemon prio=5 tid=0x47 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at io.jmix.flowui.action.view.DetailSaveCloseAction.execute(DetailSaveCloseAction.java:66)
	  at io.jmix.flowui.action.view.ViewAction.actionPerform(ViewAction.java:140)
	  at io.jmix.flowui.action.binder.AbstractShortcutActionBindingImpl.lambda$addShortcutRegistrationIfNeeded$dc4b3eb1$1(AbstractShortcutActionBindingImpl.java:63)
	  at io.jmix.flowui.action.binder.AbstractShortcutActionBindingImpl$$Lambda$2289/0x000000080194f590.onShortcut(Unknown Source:-1)
	  at com.vaadin.flow.component.ShortcutRegistration.invokeShortcutEventListener(ShortcutRegistration.java:643)
	  at com.vaadin.flow.component.ShortcutRegistration.fireShortcutEvent(ShortcutRegistration.java:593)
	  at com.vaadin.flow.component.ShortcutRegistration.lambda$updateHandlerListenerRegistration$89e5c563$1(ShortcutRegistration.java:551)
```

**Comment by glebfox** [comment]
Fixed in https://github.com/jmix-framework/jmix/issues/1758
