### ISSUE TITLE
DataManager throws unfetched attribute exception if it used in the after commit listener with joinTransaction(false)

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2948]
### Environment

Jmix version: 2.1.3

### Bug Description

A description of what the bug is.

### Steps To Reproduce

1. Create an **after commit listener** for an entity with an association attribute
2. Load entity by its `id` using `DataManager` with `joinTransaction(false)` to avoid exception.
3. Try to access an association attribute

```
@Component
public class TaskEventListener {

    private final DataManager dataManager;

    public TaskEventListener(DataManager dataManager) {
        this.dataManager = dataManager;
    }

    @TransactionalEventListener
    public void onTaskChangedAfterCommit(final EntityChangedEvent<Task> event) {
        Task task = dataManager.load(event.getEntityId())
                .joinTransaction(false)
                .one();
        User user = task.getUser();
    }
}
```

### Current Behavior

`DataManager` throws **unfetched attribute** exception if it used in the **after commit listener** with `joinTransaction(false)`:

```
java.lang.IllegalStateException: Cannot get unfetched attribute [user] from detached object com.company.demo.entity.Task-a3621080-70a5-0928-2fee-dc6a96313d9a [detached].
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.throwUnfetchedAttributeException(UnitOfWorkValueHolder.java:337) ~[org.eclipse.persistence.core-4.0.1-15-jmix.jar:na]
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:111) ~[org.eclipse.persistence.core-4.0.1-15-jmix.jar:na]
	at io.jmix.eclipselink.impl.lazyloading.AbstractValueHolder.getValue(AbstractValueHolder.java:274) ~[jmix-eclipselink-2.1.3.jar:na]
	at com.company.demo.entity.Task._persistence_get_user(Task.java) ~[main/:na]
	at com.company.demo.entity.Task.getUser(Task.java:33) ~[main/:na]
	at com.company.demo.listener.TaskEventListener.onTaskChangedAfterCommit(TaskEventListener.java:24) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
```

### Expected Behavior

`DataManager` loads an association attribute as it usually does.

### Sample Project

[after-commit-problem.zip](https://github.com/jmix-framework/jmix/files/14444738/after-commit-problem.zip)

**Comment by knstvk** [comment]
It is not recommended to use `joinTransaction(false)` in "after commit" listener. Instead, start a new transaction using `@Transactional(propagation = Propagation.REQUIRES_NEW)`.

The documentation has been updated.
