### ISSUE TITLE
Filterable column hidden by security produces exception

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3079]
### Environment
Jmix version: 2.2.1

### Bug Description
See support forum: [topic](https://forum.jmix.io/t/problems-accessing-list-views/4689).

### Steps To Reproduce
1. In `user-list-view.xml` make `lastName` column filterable:
```
<column property="lastName" filterable="true"/>
```
2. Create role with `User` read access and enable all properties excluding `lastName`
3. Assign role to an user and log in.
4. Open `Users` view

### Current Behavior
```
java.lang.IllegalArgumentException: Cannot find a cell from this row that would correspond to the given column
	at com.vaadin.flow.component.grid.AbstractRow.lambda$getCellFor$4(AbstractRow.java:201)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at com.vaadin.flow.component.grid.AbstractRow.getCellFor(AbstractRow.java:195)
	at com.vaadin.flow.component.grid.AbstractRow.getCell(AbstractRow.java:190)
	at com.vaadin.flow.component.grid.HeaderRow.getCell(HeaderRow.java:34)
	at com.vaadin.flow.component.grid.Grid$Column.setHeader(Grid.java:942)
	at io.jmix.flowui.component.grid.DataGridColumn.setFilterable(DataGridColumn.java:65)
	at io.jmix.flowui.xml.layout.loader.component.AbstractGridLoader.lambda$loadData$1(AbstractGridLoader.java:161)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.jmix.flowui.xml.layout.loader.component.AbstractGridLoader.loadData(AbstractGridLoader.java:161)
	at io.jmix.flowui.xml.layout.loader.component.AbstractGridLoader.loadComponent(AbstractGridLoader.java:126)
	at io.jmix.flowui.xml.layout.loader.container.AbstractContainerLoader.loadSubComponents(AbstractContainerLoader.java:37)
	at io.jmix.flowui.xml.layout.loader.container.AbstractContainerLoader.loadSubComponentsAndExpand(AbstractContainerLoader.java:74)
	at io.jmix.flowui.xml.layout.loader.ViewLoader.loadComponent(ViewLoader.java:75)
	at io.jmix.flowui.sys.ViewSupport.loadWindowFromXml(ViewSupport.java:447)
	at io.jmix.flowui.sys.ViewSupport.initView(ViewSupport.java:122)
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.init(JmixSpringInstantiator.java:65)
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.getOrCreate(JmixSpringInstantiator.java:58)
```

**Comment by KremnevDmitry** [comment]
Can't be reproduced on `2.2.999-SNAPSHOT`

Should be fixed with #3038
