### ISSUE TITLE
Exception when filterable column is not permitted

### ISSUE THREAD

**Issue by alferink** [jmix-framework/jmix#3088]
### Environment

Jmix version: 2.2.1

### Bug Description

I have a grid with two filterable columns. The user is not permitted to see one of the columns. The application throws an IllegalArgumentException when I open the view.

### Steps To Reproduce

1. Login as user (Password 'user')
2. Open Orders

### Current Behavior

An exception is shown:
```
java.lang.IllegalArgumentException: Cannot find a cell from this row that would correspond to the given column
	at com.vaadin.flow.component.grid.AbstractRow.lambda$getCellFor$4(AbstractRow.java:201)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at com.vaadin.flow.component.grid.AbstractRow.getCellFor(AbstractRow.java:195)
	at com.vaadin.flow.component.grid.AbstractRow.getCell(AbstractRow.java:190)
	at com.vaadin.flow.component.grid.HeaderRow.getCell(HeaderRow.java:34)
	at com.vaadin.flow.component.grid.Grid$Column.setHeader(Grid.java:942)
	at io.jmix.flowui.component.grid.DataGridColumn.setFilterable(DataGridColumn.java:65)
	at io.jmix.flowui.xml.layout.loader.component.AbstractGridLoader.lambda$loadData$1(AbstractGridLoader.java:161)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.jmix.flowui.xml.layout.loader.component.AbstractGridLoader.loadData(AbstractGridLoader.java:161)
	at io.jmix.flowui.xml.layout.loader.component.AbstractGridLoader.loadComponent(AbstractGridLoader.java:126)
	at io.jmix.flowui.xml.layout.loader.container.AbstractContainerLoader.loadSubComponents(AbstractContainerLoader.java:37)
	at io.jmix.flowui.xml.layout.loader.container.AbstractContainerLoader.loadSubComponentsAndExpand(AbstractContainerLoader.java:74)
	at io.jmix.flowui.xml.layout.loader.ViewLoader.loadComponent(ViewLoader.java:75)
	at io.jmix.flowui.sys.ViewSupport.loadWindowFromXml(ViewSupport.java:447)
	at io.jmix.flowui.sys.ViewSupport.initView(ViewSupport.java:122)
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.init(JmixSpringInstantiator.java:65)
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.getOrCreate(JmixSpringInstantiator.java:58)
	at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:136)
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.createRouteTarget(JmixSpringInstantiator.java:49)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:132)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:131)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:480)
	....
```

### Expected Behavior

The view should open without exception. On the one column should be visible.

### Sample Project

[grid-visibility-demo.zip](https://github.com/jmix-framework/jmix/files/14851208/grid-visibility-demo.zip)

**Comment by gorbunkov** [comment]
Dyplicates #3079
