### ISSUE TITLE
Cannot update composition with composite key

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#3099]
### Environment

Jmix version: 2.2.1

### Bug Description

REST add-on fails on updating composition (root together with nested collection) if the nested entity has composite PK.

### Steps To Reproduce

Create composite key:
```
@JmixEntity
@Embeddable
public class MyKey {
    @Column(name = "CODE1", nullable = false)
    @NotNull
    private String code1;

    @Column(name = "CODE2", nullable = false)
    @NotNull
    private Integer code2;
```

Create root entity:
```
@JmixEntity
@Table(name = "ROOT")
@Entity
public class Root {
    @EmbeddedId
    private MyKey id;

    @InstanceName
    @Column(name = "NAME")
    private String name;

    @Composition
    @OneToMany(mappedBy = "root")
    private List<Branch> branches;
```

Create nested entity:
```
@JmixEntity
@Table(name = "BRANCH", indexes = {
        @Index(name = "IDX_BRANCH_ROCOROCO", columnList = "ROOT_CODE1, ROOT_CODE2")
})
@Entity
public class Branch {
    @EmbeddedId
    private MyKey id;

    @InstanceName
    @Column(name = "NAME")
    private String name;
    @OnDeleteInverse(DeletePolicy.CASCADE)
    @JoinColumns({
            @JoinColumn(name = "ROOT_CODE1", referencedColumnName = "CODE1", nullable = false),
            @JoinColumn(name = "ROOT_CODE2", referencedColumnName = "CODE2", nullable = false)
    })
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    private Root root;
```

Create UI views, start application and create some instances of Root and Branch.

Create named fetch plan:
```
<fetchPlan entity="Root" name="root-aggregate" extends="_base">
    <property name="branches" fetchPlan="_base"/>
</fetchPlan>
```

Open Postman and load a Root by id (which is Base64-encoded JSON):
```
GET http://localhost:8080/rest/entities/Root/eyJjb2RlMSI6ICJyIiwiY29kZTIiOiAxfQ==?fetchPlan=root-aggregate
```

Try to update the same entity:
```
PUT http://localhost:8080/rest/entities/Root/eyJjb2RlMSI6ICJyIiwiY29kZTIiOiAxfQ==
{...}
```

### Current Behavior

Error in response, exception in the server log:
```
2024-04-05T09:47:22.684+04:00 ERROR 2576 --- [nio-8080-exec-2] i.j.r.i.c.RestControllerExceptionHandler : Exception in REST controller

java.lang.IllegalArgumentException: You have attempted to set a value of type class java.lang.String for parameter entityId with expected type of class com.company.demo.entity.MyKey from query string select e from Root e where e.id = :entityId.
	at org.eclipse.persistence.internal.jpa.QueryImpl.setParameterInternal(QueryImpl.java:941) ~[org.eclipse.persistence.jpa-4.0.2-2-jmix.jar:na]
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:586) ~[org.eclipse.persistence.jpa-4.0.2-2-jmix.jar:na]
	at io.jmix.eclipselink.impl.JmixEclipseLinkQuery$Param.apply(JmixEclipseLinkQuery.java:942) ~[jmix-eclipselink-2.2.1.jar:na]
	at io.jmix.eclipselink.impl.JmixEclipseLinkQuery.getQuery(JmixEclipseLinkQuery.java:490) ~[jmix-eclipselink-2.2.1.jar:na]
	at io.jmix.eclipselink.impl.JmixEclipseLinkQuery.getSingleResult(JmixEclipseLinkQuery.java:157) ~[jmix-eclipselink-2.2.1.jar:na]
	at io.jmix.eclipselink.impl.JpaDataStore.executeQuery(JpaDataStore.java:593) ~[jmix-eclipselink-2.2.1.jar:na]
	at io.jmix.eclipselink.impl.JpaDataStore.loadOne(JpaDataStore.java:146) ~[jmix-eclipselink-2.2.1.jar:na]
	at io.jmix.core.datastore.AbstractDataStore.load(AbstractDataStore.java:87) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.core.impl.UnconstrainedDataManagerImpl.load(UnconstrainedDataManagerImpl.java:97) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.eclipselink.impl.lazyloading.SingleValueOwningPropertyHolder.loadValue(SingleValueOwningPropertyHolder.java:61) ~[jmix-eclipselink-2.2.1.jar:na]
	at io.jmix.eclipselink.impl.lazyloading.AbstractValueHolder.getValue(AbstractValueHolder.java:277) ~[jmix-eclipselink-2.2.1.jar:na]
	at com.company.demo.entity.Branch._persistence_get_root(Branch.java) ~[main/:na]
	at com.company.demo.entity.Branch.getRoot(Branch.java:30) ~[main/:na]
	at io.jmix.core.entity.BaseEntityEntry.getAttributeValue(BaseEntityEntry.java:85) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.core.entity.BaseEntityEntry.setAttributeValue(BaseEntityEntry.java:101) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.core.entity.EntityValues.setValue(EntityValues.java:73) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.core.impl.importexport.EntityImportExportImpl.lambda$importOneToManyCollectionAttribute$4(EntityImportExportImpl.java:512) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.core.impl.importexport.CollectionCompare.compare(CollectionCompare.java:63) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.core.impl.importexport.EntityImportExportImpl.importOneToManyCollectionAttribute(EntityImportExportImpl.java:532) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.core.impl.importexport.EntityImportExportImpl.importEntity(EntityImportExportImpl.java:438) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.core.impl.importexport.EntityImportExportImpl.importEntities(EntityImportExportImpl.java:250) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.core.impl.importexport.EntityImportExportImpl.importEntities(EntityImportExportImpl.java:220) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.rest.impl.service.EntitiesControllerManager.getUpdatedEntity(EntitiesControllerManager.java:726) ~[jmix-rest-2.2.1.jar:na]
	at io.jmix.rest.impl.service.EntitiesControllerManager.updateEntity(EntitiesControllerManager.java:606) ~[jmix-rest-2.2.1.jar:na]
	at io.jmix.rest.impl.controller.EntitiesController.updateEntity(EntitiesController.java:142) ~[jmix-rest-2.2.1.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:261) ~[spring-web-6.1.3.jar:6.1.3]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:189) ~[spring-web-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:925) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:550) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.3.jar:6.1.3]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
...
``` 

### Sample Project

[demo.zip](https://github.com/jmix-framework/jmix/files/14880478/demo.zip)

**Comment by gorbunkov** [comment]
The problem could be not in REST API, but in lazy loading.

The following test fails with an error from the issue description:

```groovy
import io.jmix.core.DataManager
import io.jmix.core.Id
import io.jmix.core.entity.EntityValues
import org.springframework.beans.factory.annotation.Autowired
import test_support.DataSpec
import test_support.entity.composite_pk.Branch
import test_support.entity.composite_pk.MyKey
import test_support.entity.composite_pk.Root

class LazyLoadingCompositePkTest extends DataSpec {

    @Autowired
    DataManager dataManager


    def "lazy loading and composite primary key"() {

        given:
        
        MyKey myKey1 = dataManager.create(MyKey)
        myKey1.code1 = 'c1'
        myKey1.code2 = 1

        Root root1 = dataManager.create(Root)
        root1.id = myKey1
        root1.name = 'root1'

        MyKey myKey2 = dataManager.create(MyKey)
        myKey2.code1 = 'c2'
        myKey2.code2 = 2

        Branch branch1 = dataManager.create(Branch)
        branch1.name = 'branch1'
        branch1.root = root1
        branch1.id = myKey2

        dataManager.save(branch1, root1)

        when:

        Branch reloadedBranch = dataManager.load(Branch).id(Id.of(myKey2)).one()
        Root rootAttributeValue = EntityValues.getValue(reloadedBranch, 'root')

        then:

        rootAttributeValue.id == myKey1
    }
}
```

The `io.jmix.core.entity.EntityValues#getValue`invokes the `io.jmix.eclipselink.impl.lazyloading.ValueHoldersSupport#getEntityIdFromValueHolder`.

The method `io.jmix.eclipselink.impl.lazyloading.ValueHoldersSupport#getEntityIdFromValueHolder` doesn't work for composite primary keys:

```java
    public static Object getEntityIdFromValueHolder(QueryBasedValueHolder queryBasedValueHolder) {
        AtomicReference<String> fieldName = new AtomicReference<>();
        ExpressionIterator iterator = new ExpressionIterator() {
            @Override
            public void iterate(Expression each) {
                if (each instanceof ParameterExpression) {
                    fieldName.set(((ParameterExpression) each).getField().getQualifiedName());
                }
            }
        };
        iterator.iterateOn(queryBasedValueHolder.getQuery().getSelectionCriteria());
        return queryBasedValueHolder.getRow().get(fieldName.get());
    }
```

A patch with the test: [Lazy_loading_issue_with_composite_key.patch](https://github.com/jmix-framework/jmix/files/14981436/Lazy_loading_issue_with_composite_key.patch)
