### ISSUE TITLE
Exception if a user has no permission to a column that is collapsed via XML

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3110]
### Environment

Jmix version: 1.5.5

### Bug Description

Origin: [forum](https://forum.jmix.io/t/screen-unusable-if-column-to-collapse-is-out-of-users-permission/4701)

If a column related to the entity attributes that is hidden by security permissions is collapsed via XML then exception is thrown

### Steps To Reproduce

1. Create a **resource role** that grants permission to an any entity (e.g. User) but hides some attributes
2. Add `collapsed="true"` to columns related to hidden attributes, e.g.:

```
<groupTable id="usersTable"
                    width="100%"
                    dataContainer="usersDc"
                    multiselect="true">
            ...
            <columns>
                <column id="username"/>
                <column id="firstName"/>
                <column id="lastName"/>
                <column id="email"/>
                <column id="timeZoneId" collapsed="true"/>
                <column id="active" collapsed="true"/>
            </columns>
```

3. Open the screen

### Current Behavior

```
Caused by: java.lang.IllegalArgumentException: Property 'active' was not found in the container

	at com.vaadin.v7.ui.Table.setColumnCollapsed(Table.java:1381) ~[vaadin-compatibility-server-8.14.3-4-jmix.jar:8.14.3-4-jmix]
	at io.jmix.ui.component.impl.AbstractTable$ColumnImpl.setCollapsed(AbstractTable.java:2016) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.xml.layout.loader.AbstractTableLoader.lambda$loadColumn$0(AbstractTableLoader.java:457) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.xml.layout.loader.ComponentLoaderContext.executePostInitTasks(ComponentLoaderContext.java:141) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:228) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:145) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.createScreen(MenuItemCommands.java:230) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:169) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:272) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:257) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.component.mainwindow.impl.SideMenuImpl$MenuItemImpl.menuSelected(SideMenuImpl.java:587) ~[jmix-ui-1.5.5.jar:na]
	at io.jmix.ui.widget.JmixSideMenu$1.menuItemTriggered(JmixSideMenu.java:91) ~[jmix-ui-1.5.5.jar:na]
	... 94 common frames omitted
```

### Expected Behavior

screen is opened

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6324-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
2) Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6329-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)

Column is collapsed, there are no Exception - Ok.
