### ISSUE TITLE
Wrong value for Flowable event listener entity type is written to BPMN XML

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3117]
### Environment

Jmix version: 2.2.1

### Bug Description

Wrong value is written to `entityType` attribute of `flowable:eventListener` BPMN XML by BPMN runtime modeler.

### Steps To Reproduce

1. Create new BPMN process in runtime modeler
1. Add a new process event listener
1. Select a Java class, select entity type (e.g. Process instance) and event.
1. Try to deploy the process

<img width="837" alt="Screenshot 2024-04-09 at 15 57 29" src="https://github.com/jmix-framework/jmix/assets/7888486/e2b93388-a814-48c9-bb1e-0f99c11c115c">

### Current Behavior

Exception:

```
org.flowable.common.engine.api.FlowableIllegalArgumentException: Unsupported entity-type for a FlowableEventListener: Process instance
	at org.flowable.engine.impl.bpmn.parser.factory.DefaultListenerFactory.getEntityType(DefaultListenerFactory.java:224)
	at org.flowable.engine.impl.bpmn.parser.factory.DefaultListenerFactory.createClassDelegateEventListener(DefaultListenerFactory.java:163)
	at org.flowable.engine.impl.bpmn.parser.handler.ProcessParseHandler.createEventListeners(ProcessParseHandler.java:93)
	at org.flowable.engine.impl.bpmn.parser.handler.ProcessParseHandler.transformProcess(ProcessParseHandler.java:73)
	at org.flowable.engine.impl.bpmn.parser.handler.ProcessParseHandler.executeParse(ProcessParseHandler.java:49)
	at org.flowable.engine.impl.bpmn.parser.handler.ProcessParseHandler.executeParse(ProcessParseHandler.java:33)
	at org.flowable.engine.impl.bpmn.parser.handler.AbstractBpmnParseHandler.parse(AbstractBpmnParseHandler.java:57)
	at org.flowable.engine.impl.bpmn.parser.BpmnParseHandlers.parseElement(BpmnParseHandlers.java:79)
	at org.flowable.engine.impl.bpmn.parser.BpmnParse.applyParseHandlers(BpmnParse.java:282)
	at org.flowable.engine.impl.bpmn.parser.BpmnParse.execute(BpmnParse.java:195)
	at org.flowable.engine.impl.bpmn.deployer.ParsedDeploymentBuilder.createBpmnParseFromResource(ParsedDeploymentBuilder.java:97)
...
```

The problem is that wrong value is written to BPMN XML:

```xml
<flowable:eventListener class="io.jmix.bpm.engine.eventlistener.ActivityStartedEventListener" events="ENTITY_CREATED" entityType="Process instance" />
```
but the attribute entityType should have another value:

```xml
<flowable:eventListener class="io.jmix.bpm.engine.eventlistener.ActivityStartedEventListener" events="PROCESS_STARTED" entityType="process-instance" />
```

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.2-241
IntelliJ version: IntelliJ IDEA 2024.1
