### ISSUE TITLE
Error when using dynamic attribute with a cyrillic code in a generic filter

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3152]
### Environment

Jmix version: 2.2.1

### Bug Description

When a dynamic attribute code contains cyrillic characters,  then the exception is thrown on applying generic filter that uses this attribute.

### Steps To Reproduce

1. Create some dynamic attribute category and dynamic attribute with cyrillic code.
2. Open the entity list view, add a condition for the dynamic attribute
3. Apply a filter

### Current Behavior

Exception:

```
io.jmix.data.impl.jpql.JpqlSyntaxException: Errors found while parsing where condition:[(exists (select cavPhPXm from dynat_CategoryAttributeValue cavPhPXm where cavPhPXm.entity.entityId=e.id and cavPhPXm.stringValue like :категорияпродуктЦветCAionNNk and cavPhPXm.categoryAttribute.id='7c8fe873-a967-25bc-e046-1c6a6633aff3'))] for query:[select e from Product e]
line 1:141 mismatched character 'К' expecting set null
	at io.jmix.data.impl.jpql.transform.QueryTransformerAstBased.parseWhereCondition(QueryTransformerAstBased.java:253) ~[jmix-data-2.2.1.jar:na]
	at io.jmix.data.impl.jpql.transform.QueryTransformerAstBased.addWhere(QueryTransformerAstBased.java:110) ~[jmix-data-2.2.1.jar:na]
	at io.jmix.data.impl.jpql.generator.ConditionJpqlGenerator.processQuery(ConditionJpqlGenerator.java:66) ~[jmix-data-2.2.1.jar:na]
	at io.jmix.data.impl.JpqlQueryBuilder.applyFiltering(JpqlQueryBuilder.java:269) ~[jmix-data-2.2.1.jar:na]
	at io.jmix.data.impl.JpqlQueryBuilder.buildResultQuery(JpqlQueryBuilder.java:230) ~[jmix-data-2.2.1.jar:na]
	at io.jmix.data.impl.JpqlQueryBuilder.getResultQueryString(JpqlQueryBuilder.java:168) ~[jmix-data-2.2.1.jar:na]
	at io.jmix.data.impl.JpqlQueryBuilder.getQuery(JpqlQueryBuilder.java:181) ~[jmix-data-2.2.1.jar:na]
	at io.jmix.eclipselink.impl.JpaDataStore.createQuery(JpaDataStore.java:516) ~[jmix-eclipselink-2.2.1.jar:na]
	at io.jmix.eclipselink.impl.JpaDataStore.loadAll(JpaDataStore.java:168) ~[jmix-eclipselink-2.2.1.jar:na]
	at io.jmix.core.datastore.AbstractDataStore.loadList(AbstractDataStore.java:129) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.core.impl.UnconstrainedDataManagerImpl.loadList(UnconstrainedDataManagerImpl.java:112) ~[jmix-core-2.2.1.jar:na]
	at io.jmix.flowui.model.impl.CollectionLoaderImpl._load(CollectionLoaderImpl.java:120) ~[jmix-flowui-2.2.1.jar:na]
	at io.jmix.flowui.model.impl.CollectionLoaderImpl.load(CollectionLoaderImpl.java:100) ~[jmix-flowui-2.2.1.jar:na]
	at io.jmix.flowui.component.filter.SingleFilterComponentBase.apply(SingleFilterComponentBase.java:207) ~[jmix-flowui-2.2.1.jar:na]
	at io.jmix.flowui.component.filter.SingleFilterComponentBase.onFilterValueChanged(SingleFilterComponentBase.java:110) ~[jmix-flowui-2.2.1.jar:na]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.lambda$addValueChangeListener$828eca10$1(AbstractFieldSupport.java:98) ~[flow-server-24.3.3.jar:24.3.3]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:239) ~[flow-server-24.3.3.jar:24.3.3]
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:228) ~[flow-server-24.3.3.jar:24.3.3]
	at com.vaadin.flow.component.Component.fireEvent(Component.java:411) ~[flow-server-24.3.3.jar:24.3.3]
	at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:416) ~[flow-server-24.3.3.jar:24.3.3]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setValue(AbstractFieldSupport.java:209) ~[flow-server-24.3.3.jar:24.3.3]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setModelValue(AbstractFieldSupport.java:169) ~[flow-server-24.3.3.jar:24.3.3]
	at com.vaadin.flow.component.AbstractField.setModelValue(AbstractField.java:225) ~[flow-server-24.3.3.jar:24.3.3]
	at io.jmix.flowui.component.filter.SingleFilterComponentBase.onFieldValueChanged(SingleFilterComponentBase.java:398) ~[jmix-flowui-2.2.1.jar:na]
```
### Expected Behavior

The problem is that dynamic attribute code is used as a JPQL query parameter name. I see two options here:

Add a validator to dynamic attributes that will allow to enter only Latin letters, digits and "_" symbol code field. First letter have to be a lowercase Latin letter.

### Sample Project

Sample project: [dynattr-cyrillic-error.zip](https://github.com/jmix-framework/jmix/files/14994139/dynattr-cyrillic-error.zip)

See [forum topic](https://forum.jmix.ru/t/dinamicheskie-atributy-kirillicza-v-nazvanii-kategorij-i-atributov/1736)

**Comment by fractal3000** [comment]
Issue for documentaion correction is created https://github.com/jmix-framework/jmix-docs/issues/851

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)
2) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
3) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

Now, dynamic attribute code can not contain Cirillic letters.
Message appears: "The field can contain only Latin letters, digits and "_" symbol. First letter have to be a lowercase Latin letter."
