### ISSUE TITLE
Unable to obtain access token with Password grant when multitenancy add-on is added to the project

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3168]
### Environment

Jmix version: 2.3.999-SNAPSHOT

### Bug Description

Request to token endpoint fails with an error

### Steps To Reproduce

1. Create new project.
1. Add REST API, Authorization server and Multitenancy add-on.
1. Configure [resource owner password credentials](https://github.com/jmix-framework/jmix/issues/2499) grant (see docs in the [PR](https://github.com/jmix-framework/jmix-docs/pull/678)).
1. Try to obtain access token.

```
curl -X POST http://localhost:8080/oauth2/token \
   --basic --user myapp:mysecret \
   -H "Content-Type: application/x-www-form-urlencoded" \
   -d "grant_type=password" \
   -d "username=user1" \
   -d "password=1"
```

### Current Behavior

Exception:

```
org.springframework.security.authentication.InternalAuthenticationServiceException: Could not open JPA EntityManager for transaction
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:118) ~[spring-security-core-6.2.3.jar:6.2.3]
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:133) ~[spring-security-core-6.2.3.jar:6.2.3]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) ~[spring-security-core-6.2.3.jar:6.2.3]
	at io.jmix.authserver.authentication.OAuth2ResourceOwnerPasswordCredentialsAuthenticationProvider.authenticateUserInJmix(OAuth2ResourceOwnerPasswordCredentialsAuthenticationProvider.java:217) ~[jmix-authserver-2.3.999-SNAPSHOT.jar:na]
	at io.jmix.authserver.authentication.OAuth2ResourceOwnerPasswordCredentialsAuthenticationProvider.authenticate(OAuth2ResourceOwnerPasswordCredentialsAuthenticationProvider.java:83) ~[jmix-authserver-2.3.999-SNAPSHOT.jar:na]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) ~[spring-security-core-6.2.3.jar:6.2.3]
	at org.springframework.security.oauth2.server.authorization.web.OAuth2TokenEndpointFilter.doFilterInternal(OAuth2TokenEndpointFilter.java:167) ~[spring-security-oauth2-authorization-server-1.2.3.jar:1.2.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.5.jar:6.1.5]
```

### Expected Behavior

Access token must be returned.

### Analysis

The problem is in the `io.jmix.multitenancy.core.impl.TenantProviderImpl#getCurrentUserTenantId` method. 
Invocation of `UserDetails userDetails = currentAuthentication.getUser();` fails because Authentication contains the `OAuth2ClientAuthenticationToken` with registered authorization client credentials.

### Sample Project

[rest-mt-password-grant.zip](https://github.com/jmix-framework/jmix/files/15021612/rest-mt-password-grant.zip)

See [forum](https://forum.jmix.io/t/how-to-authenticate-in-rest-with-jmix-user-credentials/3965/16)

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6366-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6368-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

There is no exception. 
By command the access_token was generated - Ok.
Users were got from application with Bearer authorization with the access-token - Ok.
