### ISSUE TITLE
Exception when exporting not from first page

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#3189]
### Environment

Jmix version: 1.5.5

### Steps To Reproduce

1. Run project 
[TestExportExcel.zip](https://github.com/jmix-framework/jmix/files/15126357/TestExportExcel.zip)
2. Open Test Data For Exports screen
3. Click generate 1000 row if table has less than one page
4. Go to second page of the table and try to export all data to excel
**AR:**
```java
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/java.util.Vector.elementData(Vector.java:731)
	at java.base/java.util.Vector.get(Vector.java:752)
	at io.jmix.gridexportui.exporter.excel.AllRecordsExporter.lambda$exportAll$0(AllRecordsExporter.java:110)
	at org.springframework.transaction.support.TransactionOperations.lambda$executeWithoutResult$0(TransactionOperations.java:68)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.transaction.support.TransactionOperations.executeWithoutResult(TransactionOperations.java:67)
	at io.jmix.gridexportui.exporter.excel.AllRecordsExporter.exportAll(AllRecordsExporter.java:82)
	at io.jmix.gridexportui.exporter.excel.ExcelExporter.exportTable(ExcelExporter.java:247)
	at io.jmix.gridexportui.action.ExportAction.doExport(ExportAction.java:197)
	at io.jmix.gridexportui.action.ExportAction$1.actionPerform(ExportAction.java:148)
	at io.jmix.ui.sys.DialogsImpl$OptionDialogBuilderImpl.lambda$show$0(DialogsImpl.java:344)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
        ...
```

**Comment by gorbunkov** [comment]
Check this in 1.x and 2.x

**Comment by KremnevDmitry** [comment]
Can't be reproduced on 1.6.999-SNAPSHOT and 2.3.999-SNAPSHOT

Created related issues: 
- https://github.com/jmix-framework/jmix/issues/3314
- https://github.com/jmix-framework/jmix/issues/3315
- https://github.com/jmix-framework/jmix/issues/3316
