### ISSUE TITLE
IllegalArgumentException when adding action with the same id to HasActions components 

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3260]
### Environment

Jmix version: 2.2+

### Bug Description

When adding action with the same id to HasActions components (ValuePicker, EntityPicker, EntityCombobox, DataGrid, GenericFilter, etc.) `IllegalArgumentException` is thrown.

### Steps To Reproduce

Open `UserDetailView` from the demo project

### Current Behavior

```
java.lang.IllegalArgumentException: Cannot insert element with index 4 when there are 3 children
	at com.vaadin.flow.dom.Node.insertChild(Node.java:358) ~[flow-server-24.3.3.jar:24.3.3]
	at com.vaadin.flow.dom.Node.insertChild(Node.java:340) ~[flow-server-24.3.3.jar:24.3.3]
	at com.vaadin.flow.component.HasComponents.addComponentAtIndex(HasComponents.java:165) ~[flow-server-24.3.3.jar:24.3.3]
	at io.jmix.flowui.kit.component.valuepicker.ValuePickerActionSupport.addButton(ValuePickerActionSupport.java:99) ~[jmix-flowui-kit-2.2.1.jar:na]
	at io.jmix.flowui.kit.component.valuepicker.ValuePickerActionSupport.addActionInternal(ValuePickerActionSupport.java:80) ~[jmix-flowui-kit-2.2.1.jar:na]
```

### Expected Behavior

No exception

### Sample Project

[jmix-issues-2.zip](https://github.com/jmix-framework/jmix/files/15348603/jmix-issues-2.zip)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6460-233
IntelliJ version: IntelliJ IDEA 2024.1.1
