### ISSUE TITLE
Quartz Job Sending Notification to all users when they have no User in the User Database

### ISSUE THREAD

**Issue by Jojo134** [jmix-framework/jmix#3269]
### Environment

Jmix version: 2.2.3

### Bug Description

When a Quartz Job is triggered it tries to send a notification to all users. This fails because not all active sessions have a corresponding User in the User Database.

### Steps To Reproduce

1. Create Project using the Quartz and OIDC Connect Add-ons by following the Docs https://docs.jmix.io/jmix/oidc/index.html
2. Create Quartz Job in Code with a trigger of 1 Minute
3. Visit the Site and login in using oidc
4. Observe Error on next Quartz Job run

### Current Behavior

Exception occurs when the job triggers.

```
2024-05-21T14:35:30.129+02:00 ERROR 63809 --- [eduler_Worker-2] org.quartz.core.ErrorLogger              : Unable to notify JobListener(s) of Job to be executed: (Job will NOT be executed!). trigger= DEFAULT.DEFAULT.PingerJobTrigger job= DEFAULT.PingerJob

org.quartz.SchedulerException: JobListener 'quartz_JobExecutionListener' threw exception: User not found
	at org.quartz.core.QuartzScheduler.notifyJobListenersToBeExecuted(QuartzScheduler.java:1929) ~[quartz-2.3.2.jar:na]
	at org.quartz.core.JobRunShell.notifyListenersBeginning(JobRunShell.java:324) ~[quartz-2.3.2.jar:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:173) ~[quartz-2.3.2.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar:na]
Caused by: org.springframework.security.core.userdetails.UsernameNotFoundException: User not found
	at io.jmix.securitydata.user.AbstractDatabaseUserRepository.loadUserByUsername(AbstractDatabaseUserRepository.java:186) ~[jmix-security-data-2.2.3.jar:na]
	at io.jmix.core.security.impl.SystemAuthenticationProvider.authenticate(SystemAuthenticationProvider.java:48) ~[jmix-core-2.2.3.jar:na]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) ~[spring-security-core-6.2.3.jar:6.2.3]
	at io.jmix.core.security.impl.SystemAuthenticatorImpl.begin(SystemAuthenticatorImpl.java:75) ~[jmix-core-2.2.3.jar:na]
	at io.jmix.core.security.impl.SystemAuthenticatorImpl.runWithUser(SystemAuthenticatorImpl.java:117) ~[jmix-core-2.2.3.jar:na]
	at io.jmix.flowui.UiEventPublisher.sendEventToUserSessions(UiEventPublisher.java:105) ~[jmix-flowui-2.2.3.jar:na]
	at io.jmix.flowui.UiEventPublisher.publishEventForUsersInternal(UiEventPublisher.java:88) ~[jmix-flowui-2.2.3.jar:na]
	at io.jmix.flowui.UiEventPublisher.onUiUserEvent(UiEventPublisher.java:83) ~[jmix-flowui-2.2.3.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:365) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:237) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:168) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384) ~[spring-context-6.1.5.jar:6.1.5]
	at io.jmix.core.cluster.ClusterApplicationEventPublisher.onAppEventMessage(ClusterApplicationEventPublisher.java:56) ~[jmix-core-2.2.3.jar:na]
	at io.jmix.core.cluster.LocalApplicationEventChannelSupplier$1.lambda$send$0(LocalApplicationEventChannelSupplier.java:52) ~[jmix-core-2.2.3.jar:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at io.jmix.core.cluster.LocalApplicationEventChannelSupplier$1.send(LocalApplicationEventChannelSupplier.java:52) ~[jmix-core-2.2.3.jar:na]
	at org.springframework.messaging.MessageChannel.send(MessageChannel.java:45) ~[spring-messaging-6.1.5.jar:6.1.5]
	at io.jmix.core.cluster.ClusterApplicationEventPublisher.publish(ClusterApplicationEventPublisher.java:70) ~[jmix-core-2.2.3.jar:na]
	at io.jmix.flowui.UiEventPublisher.publishEventForUsers(UiEventPublisher.java:163) ~[jmix-flowui-2.2.3.jar:na]
	at io.jmix.quartzflowui.event.JobExecutionListener.jobToBeExecuted(JobExecutionListener.java:67) ~[jmix-quartz-flowui-2.2.3.jar:na]
	at org.quartz.core.QuartzScheduler.notifyJobListenersToBeExecuted(QuartzScheduler.java:1927) ~[quartz-2.3.2.jar:na]
	... 3 common frames omitted
```

### Expected Behavior

No Exception is fired when the Quartz Job triggers

Or make the sending of Notifications for Quartz Job configurable

### Sample Project

[quartz-session-events.zip](https://github.com/jmix-framework/jmix/files/15390021/quartz-session-events.zip)

**Comment by gorbunkov** [comment]
UI events won't be sent after fix in #3281 
See also https://github.com/jmix-framework/jmix-docs/issues/756
