### ISSUE TITLE
NPE on downloading PDF file in Chrome

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3401]
### Environment

Jmix version: 2.2.3

### Bug Description

NullPointerException appears when users try to download the PDF file from the Chrome PDF viewer.

See [forum topic](https://forum.jmix.io/t/pdf-download-in-chrome/4973).

### Steps To Reproduce

Create a screen that downloads a PDF file using the `Downloader` bean, for example:

```java
    @Subscribe(id = "downloadPdfBtn", subject = "clickListener")
    public void onDownloadPdfBtnClick(final ClickEvent<JmixButton> event) {
        downloader.download(
                reportService.createPdf(),
                "report.pdf",
                DownloadFormat.PDF
        );
    }
```

Run the application, and initiate the downloading.

The PDF file will be opened in Chrome browser.

Try to download the file using the button in Chrome PDF viewer:

<img width="989" alt="Screenshot 2024-06-19 at 09 54 07" src="https://github.com/jmix-framework/jmix/assets/7888486/6c4ea299-a25c-49e5-8a2a-e85e1c6a3dd2">

### Current Behavior

An exception will be thrown and the file with 0 bytes size will be downloaded.

```
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "source" is null
	at com.vaadin.flow.server.StreamResource$Pipe.read(StreamResource.java:119) ~[flow-server-24.3.8.jar:24.3.8]
	at com.vaadin.flow.server.StreamResource$Pipe.copy(StreamResource.java:109) ~[flow-server-24.3.8.jar:24.3.8]
	at com.vaadin.flow.server.StreamResource$Pipe.accept(StreamResource.java:84) ~[flow-server-24.3.8.jar:24.3.8]
	at io.jmix.flowui.component.filedownloader.JmixFileDownloader.lambda$runCommand$18809115$1(JmixFileDownloader.java:121) ~[jmix-flowui-2.2.3.jar:na]
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[na:na]
	at io.jmix.flowui.component.filedownloader.JmixFileDownloader.lambda$beforeClientResponseDownloadHandler$69016e48$1(JmixFileDownloader.java:158) ~[jmix-flowui-2.2.3.jar:na]
	at com.vaadin.flow.server.communication.SessionRequestHandler.handleRequest(SessionRequestHandler.java:64) ~[flow-server-24.3.8.jar:24.3.8]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1574) ~[flow-server-24.3.8.jar:24.3.8]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398) ~[flow-server-24.3.8.jar:24.3.8]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) ~[vaadin-spring-24.3.8.jar:na]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
```

It looks like Chrome tries to access downloader controller multiple times: when it opens the document for preview and when the download button in the viewer is clicked.

### Expected Behavior

File dowloaded successfully.

### Sample Project

[pdf-download.zip](https://github.com/user-attachments/files/15896228/pdf-download.zip)

**Comment by Flaurite** [comment]
Cannot reproduce on Windows 10 and Chrome 127.0.6533.120.
Need to check on MacOS and Ubuntu.

**Comment by SergeiAksenov2** [comment]
Tested on Ubuntu on original project:
Jmix version: 2.2.3
Jmix Studio plugin version: 2.3.0-241
IntelliJ version: IntelliJ IDEA 2024.1.5 (Community Edition)

Tested on Ubuntu on IJ IDEA 233:
1) Jmix version: 2.2.3
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.1
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)

Tested on Ubuntu on IJ IDEA 241:
1) Jmix version: 2.2.3
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.5 (Community Edition)
2) Jmix version: 2.3.1
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.5 (Community Edition)

Tested on Mac-Mini:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.2-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6674-242
IntelliJ version: IntelliJ IDEA 2024.2 RC (Community Edition)

The PDF file is loads correctly - Ok.

**Comment by Flaurite** [comment]
Reproduced in Chrome v131.0.6778.86.
The Jmix downloader creates a file in the temporary directory during the process and deletes it after the 'view' or 'download.' The problem is that Chrome sends a second request for this file (PDF), but it has already been deleted.
