### ISSUE TITLE
Exception in case of wrong value in a field with the NumberFormat annotation 

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3512]
### Environment

Jmix version: 2.3.1

### Bug Description

An exception is thrown when wrong value is typed into the textField associated with entity attribute that has the `@NumberFormat` annotation.

### Steps To Reproduce

1. Create an entity that has some number attribute with the `@NumberFormat` annotation.
2. Generate views for the entity
3. Enter wrong value to the textFIeld

```java
@JmixEntity
@Table(name = "PRODUCT")
@Entity
public class Product {

    @Column(name = "WEIGHT")
    @NumberFormat(pattern = "#")
    private Integer weight;

   // ...
```

### Current Behavior

An exception:

```
java.lang.NullPointerException: Cannot invoke "io.jmix.core.Messages.formatMessage(String, String, Object[])" because "this.messages" is null
	at io.jmix.core.metamodel.datatype.impl.NumberDatatype.parse(NumberDatatype.java:88) ~[jmix-core-2.3.1.jar:na]
	at io.jmix.core.metamodel.datatype.impl.AdaptiveNumberDatatype.parse(AdaptiveNumberDatatype.java:120) ~[jmix-core-2.3.1.jar:na]
	at io.jmix.core.metamodel.datatype.impl.AdaptiveNumberDatatype.parse(AdaptiveNumberDatatype.java:35) ~[jmix-core-2.3.1.jar:na]
	at io.jmix.flowui.component.textfield.TypedTextField.convertToModel(TypedTextField.java:316) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.component.textfield.TypedTextField.onValueChange(TypedTextField.java:295) ~[jmix-flowui-2.3.1.jar:na]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:239) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:228) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.Component.fireEvent(Component.java:411) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:416) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setValue(AbstractFieldSupport.java:209) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setModelValue(AbstractFieldSupport.java:169) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.AbstractField.setModelValue(AbstractField.java:225) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.AbstractSinglePropertyField.doSetModelValue(AbstractSinglePropertyField.java:360) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.AbstractSinglePropertyField.handlePropertyChange(AbstractSinglePropertyField.java:352) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.AbstractSinglePropertyField$1.propertyChange(AbstractSinglePropertyField.java:329) ~[flow-server-24.3.10.jar:24.3.10]
```

### Expected Behavior

Error message displayed in the UI near the field

### Sample Project

[untitled80.zip](https://github.com/user-attachments/files/16359457/untitled80.zip)

**Comment by SergeiAksenov2** [comment]
Tested on Java:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)

Tested on Kotlin:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

No exception in case of wrong value in a field - Ok.
