### ISSUE TITLE
Exception when a user removes a role that has been assigned to them

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3543]
### Environment

Jmix version: 2.3.1

### Bug Description

When the user removes the resource role that is assigned to them, the exception occurs. Also users report on [forum](https://forum.jmix.ru/t/udalenie-rolej-tekushhego-polzovatelya/1918) that the removed role is not removed from the roles cache.

### Steps To Reproduce

1. Create a user.
2. Create a role.
3. Assign the new role to the user.
4. Assign the Full access role to the user
5. Login with this user
6. Open the resource roles list view
7. Remove the role that has been created previously

### Current Behavior

Exception occurs:

```
java.lang.IllegalStateException: ResourceRole not found by code: role1
	at io.jmix.security.impl.role.ResourceRoleRepositoryImpl.getRoleByCode(ResourceRoleRepositoryImpl.java:78) ~[jmix-security-2.3.1.jar:na]
	at io.jmix.security.impl.role.ResourceRoleRepositoryImpl.getRoleByCode(ResourceRoleRepositoryImpl.java:34) ~[jmix-security-2.3.1.jar:na]
	at io.jmix.security.impl.constraint.AuthenticationPolicyStore.extractResourcePoliciesFromAuthenticationByScope(AuthenticationPolicyStore.java:149) ~[jmix-security-2.3.1.jar:na]
	at io.jmix.security.impl.constraint.AuthenticationPolicyStore.getEntityResourcePolicies(AuthenticationPolicyStore.java:82) ~[jmix-security-2.3.1.jar:na]
	at io.jmix.security.impl.constraint.SecureOperationsImpl.isEntityOperationPermitted(SecureOperationsImpl.java:57) ~[jmix-security-2.3.1.jar:na]
	at io.jmix.security.impl.constraint.SecureOperationsImpl.isEntityCreatePermitted(SecureOperationsImpl.java:36) ~[jmix-security-2.3.1.jar:na]
	at io.jmix.securityflowui.constraint.UiEntityConstraint.applyTo(UiEntityConstraint.java:52) ~[jmix-security-flowui-2.3.1.jar:na]
	at io.jmix.securityflowui.constraint.UiEntityConstraint.applyTo(UiEntityConstraint.java:28) ~[jmix-security-flowui-2.3.1.jar:na]
	at io.jmix.core.AccessManager.lambda$applyConstraints$2(AccessManager.java:77) ~[jmix-core-2.3.1.jar:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at io.jmix.core.AccessManager.applyConstraints(AccessManager.java:76) ~[jmix-core-2.3.1.jar:na]
	at io.jmix.core.AccessManager.applyRegisteredConstraints(AccessManager.java:86) ~[jmix-core-2.3.1.jar:na]
	at io.jmix.flowui.action.list.CreateAction.isPermitted(CreateAction.java:303) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.action.SecuredBaseAction.refreshState(SecuredBaseAction.java:50) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.action.list.ListDataComponentAction.onSelectionChange(ListDataComponentAction.java:156) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.component.delegate.AbstractGridDelegate.onSelectionChange(AbstractGridDelegate.java:593) ~[jmix-flowui-2.3.1.jar:na]
	at com.vaadin.flow.component.grid.AbstractGridSingleSelectionModel.lambda$addSelectionListener$c8df87e0$1(AbstractGridSingleSelectionModel.java:154) ~[vaadin-grid-flow-24.3.12.jar:na]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:239) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:228) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.Component.fireEvent(Component.java:411) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.grid.Grid.access$000(Grid.java:219) ~[vaadin-grid-flow-24.3.12.jar:na]
	at com.vaadin.flow.component.grid.Grid$SelectionMode$1.fireSelectionEvent(Grid.java:354) ~[vaadin-grid-flow-24.3.12.jar:na]
	at com.vaadin.flow.component.grid.AbstractGridSingleSelectionModel.doSelect(AbstractGridSingleSelectionModel.java:192) ~[vaadin-grid-flow-24.3.12.jar:na]
	at com.vaadin.flow.component.grid.AbstractGridSingleSelectionModel.select(AbstractGridSingleSelectionModel.java:74) ~[vaadin-grid-flow-24.3.12.jar:na]
	at com.vaadin.flow.component.grid.AbstractGridSingleSelectionModel.deselect(AbstractGridSingleSelectionModel.java:89) ~[vaadin-grid-flow-24.3.12.jar:na]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at com.vaadin.flow.data.selection.SelectionModel$Single.setSelectedItem(SelectionModel.java:86) ~[flow-data-24.3.10.jar:24.3.10]
	at com.vaadin.flow.data.selection.SelectionModel$Single.deselectAll(SelectionModel.java:92) ~[flow-data-24.3.10.jar:24.3.10]
	at io.jmix.flowui.component.delegate.AbstractGridDelegate.deselectAll(AbstractGridDelegate.java:323) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.component.delegate.AbstractGridDelegate.refreshSelection(AbstractGridDelegate.java:254) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.component.delegate.AbstractGridDelegate.itemsItemSetChanged(AbstractGridDelegate.java:214) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.kit.event.EventBus.fireEvent(EventBus.java:82) ~[jmix-flowui-kit-2.3.1.jar:na]
	at io.jmix.flowui.data.grid.ContainerDataGridItems.containerCollectionChanged(ContainerDataGridItems.java:72) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:172) ~[jmix-core-2.3.1.jar:na]
	at io.jmix.flowui.model.impl.CollectionContainerImpl.fireCollectionChanged(CollectionContainerImpl.java:238) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.model.impl.CollectionContainerImpl.lambda$getMutableItems$0(CollectionContainerImpl.java:86) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.model.impl.ObservableList.fireCollectionChanged(ObservableList.java:69) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.model.impl.ObservableList.remove(ObservableList.java:161) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.util.RemoveOperation.removeItems(RemoveOperation.java:210) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.util.RemoveOperation.performAction(RemoveOperation.java:188) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.util.RemoveOperation.lambda$performActionWithConfirmation$2(RemoveOperation.java:332) ~[jmix-flowui-2.3.1.jar:na]
	at io.jmix.flowui.kit.event.EventBus.fireEvent(EventBus.java:82) ~[jmix-flowui-kit-2.3.1.jar:na]
	at io.jmix.flowui.kit.action.BaseAction.actionPerform(BaseAction.java:67) ~[jmix-flowui-kit-2.3.1.jar:na]
	at io.jmix.flowui.impl.DialogsImpl.lambda$createButton$be7404f0$1(DialogsImpl.java:124) ~[jmix-flowui-2.3.1.jar:na]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:239) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:488) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:298) ~[flow-server-24.3.10.jar:24.3.10]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447) ~[flow-server-24.3.10.jar:24.3.10]
```

### Expected Behavior

The role is removed, all role assignments for this role are also removed.

**Comment by rusiaikinat** [comment]
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6718-242
IntelliJ version: IntelliJ IDEA 2024.2.0.1 (Ultimate Edition)
Kotlin, java
