### ISSUE TITLE
NPE rises if press "Run" button for a not persisted report

### ISSUE THREAD

**Issue by ilushaaa** [jmix-framework/jmix#3579]
### Environment

Jmix version: 2.3

### Steps To Reproduce

1. Create Jmix project
2. Add reports addon
3. Create new report
4. Press "Run"

It works fine if user saves report, reopen it and press "Run".

### Current Behavior

![image](https://github.com/user-attachments/assets/675156ef-8567-476c-991a-c884bdd43197)

java.lang.NullPointerException: items cannot be null
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at com.vaadin.flow.data.provider.ListDataProvider.<init>(ListDataProvider.java:55)
	at com.vaadin.flow.data.provider.DataProvider.ofCollection(DataProvider.java:278)
	at com.vaadin.flow.data.provider.HasListDataView.setItems(HasListDataView.java:55)
	at com.vaadin.flow.component.combobox.ComboBoxBase.setItems(ComboBoxBase.java:572)
	at io.jmix.reportsflowui.view.run.InputParametersFragment.initContent(InputParametersFragment.java:131)
	at io.jmix.reportsflowui.view.run.InputParametersFragment.initContent(InputParametersFragment.java:58)
	at com.vaadin.flow.component.Composite.getContent(Composite.java:129)
	at com.vaadin.flow.component.Composite.getElement(Composite.java:173)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.vaadin.flow.component.HasComponents.add(HasComponents.java:75)
	at com.vaadin.flow.component.HasComponents.add(HasComponents.java:58)
	at io.jmix.reportsflowui.view.run.InputParametersDialog.onBeforeShow(InputParametersDialog.java:124)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:239)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:228)
	at com.vaadin.flow.component.Component.fireEvent(Component.java:411)
	at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:416)
	at io.jmix.flowui.view.ViewControllerUtils.fireEvent(ViewControllerUtils.java:118)
	at io.jmix.flowui.view.DialogWindow.fireViewBeforeShowEvent(DialogWindow.java:248)
	at io.jmix.flowui.view.DialogWindow.open(DialogWindow.java:195)
	at io.jmix.reportsflowui.view.report.ReportDetailView.onRunAction(ReportDetailView.java:954)
	at io.jmix.flowui.kit.event.EventBus.fireEvent(EventBus.java:82)
	at io.jmix.flowui.kit.action.BaseAction.actionPerform(BaseAction.java:67)
	at io.jmix.flowui.kit.component.button.JmixButtonActionSupport.onButtonClick(JmixButtonActionSupport.java:151)

### Expected Behavior
Run report without npe.

**Comment by ilushaaa** [comment]
Update.
Exception on "Run reports" screen.
![image](https://github.com/user-attachments/assets/08d40956-05a3-4a1f-9dc3-25a856687c87)

But user friendly message on "Reports" screen.
![image](https://github.com/user-attachments/assets/a083dbdb-2c26-44dc-9756-934340ab4089)

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6700-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6702-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)


Not saved report are run correctly. The reports from the page "Run reports" are run correctly if the have a template.
