### ISSUE TITLE
Misleading exception when trying to import unsupported file

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#367]
- Open entity inspector
- Try to import arbitrary file, say an XLS
- You get a weird exception:

```
java.lang.IllegalStateException: Unable to find window for component class io.jmix.ui.component.impl.FileUploadFieldImpl
	at io.jmix.ui.component.ComponentsHelper.getWindowNN(ComponentsHelper.java:339)
	at io.jmix.ui.component.ComponentsHelper.getScreenContext(ComponentsHelper.java:353)
	at io.jmix.ui.component.impl.AbstractSingleFileUploadField.onFileExtensionNotAllowed(AbstractSingleFileUploadField.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:709)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:399)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:363)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1216)
	at io.jmix.ui.widget.JmixFileUpload.fireFileExtensionNotAllowed(JmixFileUpload.java:499)
	at io.jmix.ui.widget.JmixFileUpload$1.fileExtensionNotAllowed(JmixFileUpload.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
```

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4299-213)
jmix version (1.3.999-SNAPSHOT)
