### ISSUE TITLE
DataGrid with KeyValueCollection fails with exception

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3797]
### Environment

Jmix version: **2.4.0-RC1**
Caused by: https://github.com/jmix-framework/jmix/issues/3641

### Bug Description

When the `DataGrid` specifies KeyValueCollection container, the view loading fails with exception.

### Steps To Reproduce

1. Download demo project: [key-value-demo.zip](https://github.com/user-attachments/files/17487499/key-value-demo.zip)

2. Open `Key value demo view`

### Current Behavior
Stacktrace:
```
java.lang.IllegalArgumentException: Property 'username' not found in sys_KeyValueEntity
	at io.jmix.core.metamodel.model.impl.MetaClassImpl.getProperty(MetaClassImpl.java:95)
	at io.jmix.core.FetchPlanBuilder.add(FetchPlanBuilder.java:110)
	at io.jmix.core.impl.FetchPlanRepositoryImpl.addAttributesToLocalFetchPlan(FetchPlanRepositoryImpl.java:279)
	at io.jmix.core.impl.FetchPlanRepositoryImpl.deployDefaultFetchPlan(FetchPlanRepositoryImpl.java:260)
	at io.jmix.core.impl.FetchPlanRepositoryImpl.retrieveFetchPlan(FetchPlanRepositoryImpl.java:421)
	at io.jmix.core.impl.FetchPlanRepositoryImpl.findFetchPlan(FetchPlanRepositoryImpl.java:215)
	at io.jmix.core.impl.FetchPlanRepositoryImpl.getFetchPlan(FetchPlanRepositoryImpl.java:190)
	at io.jmix.flowui.xml.layout.loader.component.AbstractGridLoader.loadData(AbstractGridLoader.java:136)
	at io.jmix.flowui.xml.layout.loader.component.AbstractGridLoader.loadComponent(AbstractGridLoader.java:110)
	at io.jmix.flowui.xml.layout.loader.container.AbstractContainerLoader.loadSubComponents(AbstractContainerLoader.java:37)
	at io.jmix.flowui.xml.layout.loader.container.AbstractContainerLoader.loadSubComponentsAndExpand(AbstractContainerLoader.java:74)
	at io.jmix.flowui.xml.layout.loader.ViewLoader.loadComponent(ViewLoader.java:75)
	at io.jmix.flowui.sys.ViewSupport.loadWindowFromXml(ViewSupport.java:450)
	at io.jmix.flowui.sys.ViewSupport.initView(ViewSupport.java:123)
```

### Expected Behavior

A view is loaded and `DataGrid` displays data.

**Comment by Flaurite** [comment]
Probably relates to https://github.com/jmix-framework/jmix/issues/3641
