### ISSUE TITLE
REST filter passing via GET returns Bad Request 

### ISSUE THREAD

**Issue by dvaschenko** [jmix-framework/jmix#3829]
### Environment

Jmix version: 2.3.4

### Bug Description

When trying to pass filter criteria using URL parameter with GET request - the Bad Request is being returned from server

The request:

```
curl --location --globoff 'http://localhost:8080/rest/entities/Task_/search?filter={%22conditions%22%3A[{%22property%22%3A%22name%22%2C%22operator%22%3A%22contains%22%2C%22value%22%3A%22Prepare%22}]}' \
--header 'Authorization: Bearer valid_token_here
```

### Steps To Reproduce

* Create Jmix 2.3.4 application with simple data model
* Add REST API and Authorization Server add-ons to application
* Define and assign a role for application entities access and rest-minimal to authorization server client like:

```
jmix.authserver.client.myclient.resource-roles=application-rest-role, rest-minimal
```

* Try to define and call GET request with filter like described here: https://docs.jmix.io/jmix/rest/entities-api/load-entities.html#load-list-search-filter

* The Bad Request is returned when call is being made from Postman, terminal curl, and browser. 

### Current Behavior

Stacktrace (published only one time):

```
java.lang.IllegalArgumentException: Invalid character found in the request target [/rest/entities/Task_/search?filter={%22conditions%22:[{%22property%22:%22name%22,%22operator%22:%22contains%22,%22value%22:%22Prepare%22}]} ]. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:482) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:257) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

### Expected Behavior

Filter criteria is passed correctly and result is returned

### Sample Project

[Rest-get-filter-broken.zip](https://github.com/user-attachments/files/17588904/Rest-get-filter-broken.zip)

**Comment by Ki10V01T** [comment]
No changes are required, due to the fact that the GET request generated in this task is not fully encoded (as it turned out, because of postman bug). According to the RFC 7230 standard, direct use of the characters {} and [] in the URL request is prohibited. Such characters are subject to mandatory encoding.

Current example:
> http://localhost:8080/rest/entities/Task_/search?filter={%22conditions%22%3A[{%22property%22%3A%22name%22%2C%22operator%22%3A%22contains%22%2C%22value%22%3A%22Prepare%22}]}

Correct example:
> http://localhost:8080/rest/entities/Task_/search?filter=%7B%22conditions%22%3A%5B%7B%22property%22%3A%22name%22%2C%22operator%22%3A%22contains%22%2C%22value%22%3A%22Prepare%22%7D%5D%7D
