### ISSUE TITLE
org.jetbrains.kotlin:kotlin-reflect causing IntrospectionException in Jmix 2.4

### ISSUE THREAD

**Issue by gmmars** [jmix-framework/jmix#3838]
### Environment

Jmix version: 2.4.0
Jmix Studio plugin version: 2.4.0-242
IntelliJ version: IntelliJ IDEA 2024.2.4 (Ultimate Edition)
[Link to forum](https://forum.jmix.ru/t/jmix-2-4-ne-rabotaet-s-kotlin-reflect-v-zavisimostyah-introspectionexception/2043)
### Bug Description

IntrospectionException: type mismatch between read and write methods

### Steps To Reproduce

1. Create new Jmix-Kotlin project.
2. Add implementation 'org.jetbrains.kotlin:kotlin-reflect' to build.gradle 
3. Run the project

### Current Behavior

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.company.testmigrationkotlin.view.login.LoginView': Post-processing of merged bean definition failed
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:577) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:321) ~[spring-beans-6.1.13.jar:6.1.13]
	at com.vaadin.flow.spring.SpringInstantiator.getOrCreate(SpringInstantiator.java:155) ~[vaadin-spring-24.4.8.jar:na]
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.getOrCreate(JmixSpringInstantiator.java:57) ~[jmix-flowui-2.4.0.jar:na]
	at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:170) ~[flow-server-24.4.8.jar:24.4.8]
	at io.jmix.flowui.sys.vaadin.JmixSpringInstantiator.createRouteTarget(JmixSpringInstantiator.java:49) ~[jmix-flowui-2.4.0.jar:na]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:148) ~[flow-server-24.4.8.jar:24.4.8]
	at java.base/java.util.Optional.orElseGet(Optional.java:364) ~[na:na]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:147) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:502) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:483) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:227) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handle(JavaScriptNavigationStateRenderer.java:78) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.component.UI.handleNavigation(UI.java:2005) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.component.UI.renderViewForRoute(UI.java:1968) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.component.UI.browserNavigate(UI.java:1833) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:239) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:488) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:298) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:473) ~[flow-server-24.4.8.jar:24.4.8]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:473) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:73) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:475) ~[flow-server-24.4.8.jar:24.4.8]
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$5(ServerRpcHandler.java:456) ~[flow-server-24.4.8.jar:24.4.8]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
```

### Expected Behavior

Project starts without exception

**Comment by Gavrilov-Ivan** [comment]
Bug in spring-data-commons.
Need update to 3.3.5 (spring-boot 3.3.5).

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6960-242
IntelliJ version: IntelliJ IDEA 2024.2.4 (Community Edition)
