### ISSUE TITLE
Incorrect entity alias for query with row level policy

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#3920]
### Environment

Jmix version: 2.4.0

### Steps

1. Run the project: [rowLevelAliasProblem.zip](https://github.com/user-attachments/files/17872249/rowLevelAliasProblem.zip)
2. Login as admin and open the Blank view
3. Press the button
**ER:** No exception
**AR:** 
```java
java.lang.IllegalArgumentException: An exception occurred while creating a query in EntityManager: 
Exception Description: Problem compiling [select tempEntityAlias from TestEntity tempEntityAlias, User e where (e.name = '123') and (tempEntityAlias.id = e.test.id)]. 
[70, 76] The state field path 'e.name' cannot be resolved to a valid type.
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1732) ~[org.eclipse.persistence.jpa-4.0.2-3-jmix.jar:na]
	at io.jmix.eclipselink.impl.JmixEclipseLinkQuery.buildJPAQuery(JmixEclipseLinkQuery.java:558) ~[jmix-eclipselink-2.4.0.jar:na]
	at io.jmix.eclipselink.impl.JmixEclipseLinkQuery.getQuery(JmixEclipseLinkQuery.java:468) ~[jmix-eclipselink-2.4.0.jar:na]
	at io.jmix.eclipselink.impl.JmixEclipseLinkQuery.getResultList(JmixEclipseLinkQuery.java:135) ~[jmix-eclipselink-2.4.0.jar:na]
	at io.jmix.eclipselink.impl.JpaDataStore.executeQuery(JpaDataStore.java:601) ~[jmix-eclipselink-2.4.0.jar:na]
	at io.jmix.eclipselink.impl.JpaDataStore.loadAll(JpaDataStore.java:169) ~[jmix-eclipselink-2.4.0.jar:na]
	at io.jmix.core.datastore.AbstractDataStore.loadList(AbstractDataStore.java:129) ~[jmix-core-2.4.0.jar:na]
	at io.jmix.core.impl.UnconstrainedDataManagerImpl.loadList(UnconstrainedDataManagerImpl.java:112) ~[jmix-core-2.4.0.jar:na]
	at io.jmix.core.FluentLoader$ByQuery.list(FluentLoader.java:573) ~[jmix-core-2.4.0.jar:na]
	at com.company.untitled4.view.blank.BlankView.onTestButtonClick(BlankView.kt:29) ~[main/:na]
        // ...
```

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7043-242
IntelliJ version: IntelliJ IDEA 2024.2.5 (Community Edition)
2) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7042-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
