### ISSUE TITLE
Entity Subclass View Resolution Not Working with Dialog Windows API

### ISSUE THREAD

**Issue by mariodavid** [jmix-framework/jmix#3964]
### Environment

**Jmix version:** `2.4.1`  

### Bug Description

When using the Dialog Windows API in combination with the Flow UI to create subclass-specific detail views (e.g., `CatDetailView`, `BirdDetailView`), the inferred type of the entity causes a compiler error. The error indicates that the type parameter `T` does not match the expected bounds.

This issue does not occur when using the View Navigators API, which correctly resolves the type and allows seamless navigation to subclass-specific views.

---

### Steps to Reproduce

1. Create a base entity `Pet` and subclasses `Cat` and `Bird`.  
2. Define specific detail views for each subclass (e.g., `CatDetailView`, `BirdDetailView`).  
3. Attempt to open a dialog for a subclass using the Dialog Windows API:

    ```java
    @Subscribe("petsDataGrid.createCat")
    public void onPetsDataGridCreateCat(final ActionPerformedEvent event) {
        dialogWindows.detail(petsDataGrid)
                .withParentDataContext(dataContext)
                .withViewClass(CatDetailView.class)
                .newEntity()
                .open();
    }
    ```

4. Observe the compiler error:

    ```
    Inferred type 'T' of type parameter 'T' is not within its bounds, should implement 'io.jmix.flowui.view.DetailView<Pet>'
    ```

---

### Current Behavior

1. The Dialog Windows API does not support dynamic resolution of subclass-specific views in the same way as the View Navigators API.  
   
   Example with View Navigators API (this works correctly):

    ```java
    @Subscribe("petsDataGrid.createCat")
    public void onPetsDataGridCreateCat(final ActionPerformedEvent event) {
        viewNavigators.detailView(petsDataGrid)
                .withViewClass(CatDetailView.class)
                .newEntity()
                .navigate();
    }
    ```

2. A workaround is required, where the entity instance must be created manually and explicitly set up in the data context before opening the dialog:

    ```java
    @Subscribe("petsDataGrid.createBird")
    public void onPetsDataGridCreateBird(final ActionPerformedEvent event) {
        Bird bird = dataContext.create(Bird.class);
        bird.setOwner(getEditedEntity());

        dialogWindows.detail(this, Bird.class)
                .newEntity(bird)
                .withViewClass(BirdDetailView.class)
                .withParentDataContext(dataContext)
                .withAfterCloseListener(e -> {
                    if (e.closedWith(StandardOutcome.SAVE)) {
                        petsDc.getMutableItems().add(bird);
                    }
                })
                .open();
    }
    ```

3. This manual setup is error-prone and inconsistent with the behavior of the View Navigators API.

---

### Expected Behavior

The Dialog Windows API should allow dynamic resolution of subclass-specific views without requiring manual setup. Developers should be able to use the `newEntity()` method to create the entity and open the corresponding detail view just as they can with the View Navigators API:

```java
@Subscribe("petsDataGrid.createCat")
public void onPetsDataGridCreateCat(final ActionPerformedEvent event) {
    dialogWindows.detail(petsDataGrid)
            .withParentDataContext(dataContext)
            .withViewClass(CatDetailView.class)
            .newEntity()
            .open();
}
```

### Sample Project

[jmix-data-modeling-entity-inheritance-sample.zip](https://github.com/user-attachments/files/17988609/jmix-data-modeling-entity-inheritance-sample.zip)

See: `PetListView.java` and `OwnerDetailView.java`

**Comment by glebfox** [comment]
Hi,

Even if we make our API accept the view of an inheritor of a base entity, we'll get an exception.

```
io.jmix.core.DevelopmentException: Invalid item's metaClass 'Pet', params={container=InstanceContainerImpl{entity=Cat, view=null}, metaClass=Pet}
	at io.jmix.flowui.model.impl.InstanceContainerImpl.setItem(InstanceContainerImpl.java:96)
	at io.jmix.flowui.view.StandardDetailView.setupEntityToEdit(StandardDetailView.java:672)
	at io.jmix.flowui.view.StandardDetailView.setEntityToEdit(StandardDetailView.java:591)
	at io.jmix.flowui.view.builder.DetailWindowBuilderProcessor.build(DetailWindowBuilderProcessor.java:92)
```

This is because a new instance is created using bean type obtained from `ListDataComponent`, `Pet` in your case, but actual view accepts its inheritor, `Cat` in your case. 

Note that `ViewNavigators` bean works because a view is opened by a route and no actual instance is passed to it, only `Id`.
