### ISSUE TITLE
IllegalArgumentException: Not found format strings for locale en when using DateField

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix#433]
- create project in Jmix Studio
- create Student entity with LocalDate field

```
@Table(name = "JMANKI_STUDENT")
@Entity(name = "jmanki_Student")
public class Student extends StandardEntity {
    private static final long serialVersionUID = 3953342371712316699L;

    @NotNull
    @Column(name = "NAME", nullable = false)
    @InstanceName
    private String name;

    @Column(name = "BIRTH_DATE")
    private LocalDate birthDate;
```
- create browse/edit screen
- run application, try to create the entity

exception fails:
```
java.lang.IllegalArgumentException: Not found format strings for locale en
	at io.jmix.core.metamodel.datatypes.impl.FormatStringsRegistryImpl.getFormatStringsNN(FormatStringsRegistryImpl.java:48)
	at io.jmix.ui.components.impl.WebDateField.afterPropertiesSet(WebDateField.java:148)
	at io.jmix.ui.sys.WebUiComponents.autowireContext(WebUiComponents.java:221)
	at io.jmix.ui.sys.WebUiComponents.create(WebUiComponents.java:169)
	at io.jmix.ui.xml.layout.loaders.DateFieldLoader.createComponent(DateFieldLoader.java:39)
	at io.jmix.ui.xml.layout.loaders.LayoutLoader.createComponent(LayoutLoader.java:133)
	at io.jmix.ui.xml.layout.loaders.FormLoader.loadComponent(FormLoader.java:168)
	at io.jmix.ui.xml.layout.loaders.FormLoader.loadComponents(FormLoader.java:154)
	at io.jmix.ui.xml.layout.loaders.FormLoader.loadColumns(FormLoader.java:133)
	at io.jmix.ui.xml.layout.loaders.FormLoader.loadComponent(FormLoader.java:87)
	at io.jmix.ui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:37)
	at io.jmix.ui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:75)
	at io.jmix.ui.xml.layout.loaders.WindowLoader.loadComponent(WindowLoader.java:87)
	at io.jmix.ui.sys.WebScreens.loadWindowFromXml(WebScreens.java:339)
	at io.jmix.ui.sys.WebScreens.createScreen(WebScreens.java:210)
	at io.jmix.ui.sys.WebScreens.create(WebScreens.java:149)
	at io.jmix.ui.builders.EditorBuilderProcessor.createScreen(EditorBuilderProcessor.java:286)
	at io.jmix.ui.builders.EditorBuilderProcessor.buildEditor(EditorBuilderProcessor.java:85)
	at io.jmix.ui.builders.EditorBuilder.build(EditorBuilder.java:358)
	at io.jmix.ui.actions.list.CreateAction.execute(CreateAction.java:335)
	at io.jmix.ui.actions.list.CreateAction.actionPerform(CreateAction.java:292)
	at io.jmix.ui.components.impl.WebButton.buttonClicked(WebButton.java:64)
	at io.jmix.ui.widgets.JmixButton.fireClick(JmixButton.java:75)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
...

```

**Comment by alexbudarov** [comment]
project
[jmanki.zip](https://github.com/jmix-framework/jmix/files/4655194/jmanki.zip)
