### ISSUE TITLE
Compatibility with JTA global transactions

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#516]

**Comment by belyaev-andrey** [comment]
The same issue as it was with CUBA: 
```
Caused by: java.lang.IllegalStateException: Cannot handle entity from orders datastore because active transaction is for main
	at io.jmix.data.impl.PersistenceSupport.getInstanceContainerResourceHolder(PersistenceSupport.java:192) ~[jmix-data-1.0-SNAPSHOT.jar:na]
	at io.jmix.data.impl.PersistenceSupport.registerInstance(PersistenceSupport.java:169) ~[jmix-data-1.0-SNAPSHOT.jar:na]
	at io.jmix.data.impl.EclipseLinkDescriptorEventListener.postClone(EclipseLinkDescriptorEventListener.java:104) ~[jmix-data-1.0-SNAPSHOT.jar:na]

```

**Comment by belyaev-andrey** [comment]
Kinda ideal solution: http://fabiomaffioletti.me/blog/2014/04/15/distributed-transactions-multiple-databases-spring-boot-spring-data-jpa-atomikos/ in terms of bean definitions, I wish we had something clear like this in Jmix with data manager and entity manager definitions
