### ISSUE TITLE
Compatibility with Elasticsearch 8.1

### ISSUE THREAD

**Issue by oshiryaeva** [jmix-framework/jmix#624]
Exception is thrown when trying to to synchronize indexes: `java.util.concurrent.ExecutionException: org.apache.http.ConnectionClosedException: Connection is closed `.
Same project with elasticsearch 7.17.1 works correctly. 

Environment:
1. Windows 10 Pro
2. elasticsearch-8.1.0 downloaded [from here](https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.1.0-windows-x86_64.zip) and installed following [this instruction](https://www.elastic.co/guide/en/elasticsearch/reference/current/zip-windows.html)
3. Jmix version 1.2.1

Steps:
1. Create jmix project as described [in docs](https://docs.jmix.io/jmix/search/getting-started.html) (or import this one: [sample.zip](https://github.com/jmix-framework/jmix/files/8315040/sample.zip) )
2. Add Quartz and Search addons (already added in the attached sample)
3. Setup the app properties, use your elastic credentials. Mine are below:
```
jmix.search.search-index-name-prefix = sample_prefix_
jmix.search.elasticsearch.url = localhost:9200
jmix.search.elasticsearch.login = `elastic`
jmix.search.elasticsearch.password = `9x3_FVPnvw-i36Nxl-fm`
```
4. Start the elastic cluster
5. Start the jmix app

Expected result: indexing
Actual result:
Exception on performing this request:
`Request{method='HEAD', endpoint='/sample_prefix_uiex1_order', params={ignore_unavailable=false, expand_wildcards=open,closed, allow_no_indices=false, ignore_throttled=false}, options=RequestOptions{}}`

![image](https://user-images.githubusercontent.com/11287637/159254513-af9a882f-ebf4-488a-aa34-a81ca5767ef0.png)

Full stacktrace:

```
2022-03-21 15:26:23.762  INFO 16996 --- [           main] i.j.s.i.impl.StartupIndexSynchronizer    : Start initial index synchronization
2022-03-21 15:26:23.762  INFO 16996 --- [           main] i.j.s.index.impl.ESIndexManagerImpl      : Synchronize search index 'sample_prefix_uiex1_order' (entity 'uiex1_Order') according to strategy 'CREATE_OR_RECREATE'
2022-03-21 15:26:23.862 ERROR 16996 --- [           main] i.j.s.i.impl.StartupIndexSynchronizer    : Failed to synchronize indexes

org.elasticsearch.ElasticsearchException: java.util.concurrent.ExecutionException: org.apache.http.ConnectionClosedException: Connection is closed

	at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2078) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1732) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1717) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:963) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at io.jmix.search.index.impl.ESIndexManagerImpl.isIndexExist(ESIndexManagerImpl.java:145) ~[jmix-search-1.2.0.jar:na]
	at io.jmix.search.index.impl.ESIndexManagerImpl.synchronizeIndexSchema(ESIndexManagerImpl.java:234) ~[jmix-search-1.2.0.jar:na]
	at io.jmix.search.index.impl.ESIndexManagerImpl.synchronizeIndexSchema(ESIndexManagerImpl.java:227) ~[jmix-search-1.2.0.jar:na]
	at io.jmix.search.index.impl.ESIndexManagerImpl.lambda$synchronizeIndexSchemas$2(ESIndexManagerImpl.java:216) ~[jmix-search-1.2.0.jar:na]
	at java.util.HashMap$Values.forEach(HashMap.java:982) ~[na:1.8.0_322]
	at io.jmix.search.index.impl.ESIndexManagerImpl.synchronizeIndexSchemas(ESIndexManagerImpl.java:215) ~[jmix-search-1.2.0.jar:na]
	at io.jmix.search.index.impl.ESIndexManagerImpl.synchronizeIndexSchemas(ESIndexManagerImpl.java:207) ~[jmix-search-1.2.0.jar:na]
	at io.jmix.search.index.impl.StartupIndexSynchronizer.postConstruct(StartupIndexSynchronizer.java:56) ~[jmix-search-1.2.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_322]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_322]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_322]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_322]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar:2.6.3]
	at com.company.sample.SampleApplication.main(SampleApplication.java:25) ~[main/:na]
Caused by: java.util.concurrent.ExecutionException: org.apache.http.ConnectionClosedException: Connection is closed
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:262) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:249) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:76) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2075) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	... 36 common frames omitted
Caused by: org.apache.http.ConnectionClosedException: Connection is closed
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:356) ~[httpcore-nio-4.4.15.jar:4.4.15]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261) ~[httpcore-nio-4.4.15.jar:4.4.15]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.15.jar:4.4.15]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.15.jar:4.4.15]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.15.jar:4.4.15]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.15.jar:4.4.15]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.15.jar:4.4.15]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.15.jar:4.4.15]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.15.jar:4.4.15]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_322]

Caused by: java.util.concurrent.ExecutionException: org.apache.http.ConnectionClosedException: Connection is closed

Caused by: org.apache.http.ConnectionClosedException: Connection is closed
```

In browser the cluster is up and running:
```
{
  "name" : "SHIRYAEVA-LAP",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "jLo26BiSQj-EFt9syLUEsA",
  "version" : {
    "number" : "8.1.0",
    "build_flavor" : "default",
    "build_type" : "zip",
    "build_hash" : "3700f7679f7d95e36da0b43762189bab189bc53a",
    "build_date" : "2022-03-03T14:20:00.690422633Z",
    "build_snapshot" : false,
    "lucene_version" : "9.0.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

Health check with curl results in empty response (HTTP):
```
# curl --cacert C:\work\elasticsearch-8.1.0\config\certs\http_ca.crt -u elastic http://localhost:9200
Enter host password for user 'elastic':
curl: (52) Empty reply from server
```
or in certificate issue (HTTPS):

```
# curl --cacert C:\work\elasticsearch-8.1.0\config\certs\http_ca.crt -u elastic https://localhost:9200
Enter host password for user 'elastic':
curl: (60) schannel: CertGetCertificateChain trust error CERT_TRUST_REVOCATION_STATUS_UNKNOWN
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

If set `https` explicitly in application.properties (`jmix.search.elasticsearch.url = https://localhost:9200`), another error occurs: 
```
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target the site is missing a valid trusted certificate
```

**Comment by artemy63** [comment]
Unable to reproduce exactly the requested problem, current status of investigations:
- there are no any visible problems with elastic 7.17.3
- for both 8.1 and 8.2(latest on the moment) versions I have next stacktrace while trying to update indicies
```
Caused by: java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203) ~[na:1.8.0_272]
	at org.elasticsearch.action.DocWriteResponse.<init>(DocWriteResponse.java:116) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.action.index.IndexResponse.<init>(IndexResponse.java:43) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.action.index.IndexResponse.<init>(IndexResponse.java:28) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.action.index.IndexResponse$Builder.build(IndexResponse.java:96) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.action.index.IndexResponse$Builder.build(IndexResponse.java:93) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.action.bulk.BulkItemResponse.fromXContent(BulkItemResponse.java:148) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.action.bulk.BulkResponse.fromXContent(BulkResponse.java:177) ~[elasticsearch-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2011) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$8(RestHighLevelClient.java:1673) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1749) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	... 14 common frames omitted

Caused by: java.io.IOException: Unable to parse response body for Response{requestLine=POST /_bulk?timeout=1m HTTP/1.1, host=http://localhost:9200, response=HTTP/1.1 200 OK}

Caused by: java.lang.NullPointerException: null

Caused by: java.lang.RuntimeException: Bulk request failed

Caused by: java.io.IOException: Unable to parse response body for Response{requestLine=POST /_bulk?timeout=1m HTTP/1.1, host=http://localhost:9200, response=HTTP/1.1 200 OK}
```
For my understanding it happens cause since 8.X versions elastic removed `type` mapping - https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html
So the same request to the elasticseach for 7.X version produces response
```
...
	"hits": {
		"total": {
			"value": 4,
			"relation": "eq"
		},
		"max_score": 1.0,
		"hits": [{
			"_index": "arar_prefix_order_",
			"_type": "_doc",
			"_id": "Order_.\"2ca07500-dc49-1732-3221-39daeef99140\"",
			"_score": 1.0,
			"_source": {
				"customer": {
					"status": ["Silver"],
					"lastName": "sanchito"
				},
				"number": "123",
				"product": "some product ordered",
				"_instance_name": " ordered by Mon May 16 00:00:00 SAMT 2022"
			}
		}
...
```
and for 8.X
```
...
	"hits": {
		"total": {
			"value": 4,
			"relation": "eq"
		},
		"max_score": 1.0,
		"hits": [{
			"_index": "arar_prefix_order_",
			"_id": "Order_.\"2ca07500-dc49-1732-3221-39daeef99140\"",
			"_score": 1.0,
			"_source": {
				"customer": {
					"status": ["Silver"],
					"lastName": "sanchito"
				},
				"number": "123",
				"product": "some product ordered",
				"_instance_name": " ordered by Mon May 16 00:00:00 SAMT 2022"
			}
		}
...
```

But when converting response current version of elastic that goes with spring boot 2.6.6 - 7.15.2 performs checking that response contains the `type` parameter - https://github.com/elastic/elasticsearch/blob/v7.15.2/server/src/main/java/org/elasticsearch/action/DocWriteResponse.java#L116

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Community Edition)
io.jmix.studio (1.3.SNAPSHOT4295-213)
jmix version (1.3.SNAPSHOT4295-213)
elasticsearch-8.1.0

**Comment by artemy63** [comment]
Notes:
A new application property has been inroduced to control wheter compatibility mode with ElasticSearch 8.X is enabled or not -
`jmix.search.restHighLevelClientApiCompatibilityModeEnabled`. By default it is enabled, that means that search add-on is able to communicate with ElasticSearch 8.X nodes.
But enabling this property makes impossible to communicate with Elasticsearch version lower than 7.11

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-compatibility.html
