### ISSUE TITLE
Error 500 on delete operation in REST Entities API

### ISSUE THREAD

**Issue by daring2** [jmix-framework/jmix#641]
Delete method in REST Entities API returns error with code 500 and message "Server error" for entities with enabled soft delete (`@DeletedBy` annotation) and existing references from other entities.

The problem can be reproduced in [jmix-petclinic](https://github.com/daring2/jmix-petclinic) project:
1. Add `@OnDeleteInverse(DeletePolicy.DENY)` for `Pet.type` property.
2. Try to delete PetType record with existing references from Pet entities, for example, "Water":
```
DELETE http://localhost:8080/rest/entities/petclinic_PetType/1e2abb1f-5f77-865e-17fa-b67e85497523
Accept: application/json
Authorization: Bearer {{cuba_token}}
```

Result: Error with code 500 and message "Server error".
Expected result: Response should contain an informative error and details.

Call response:
```
HTTP/1.1 500
Vary: Origin
...

{
  "error": "Server error",
  "details": ""
}
```

Server logs:
```
2022-03-29 20:05:46.066 ERROR 16532 --- [nio-8080-exec-2] i.j.r.i.c.RestControllerExceptionHandler : Exception in REST controller

io.jmix.core.DeletePolicyException: Unable to delete petclinic_PetType because there are references from petclinic_Pet
	at io.jmix.data.impl.DeletePolicyProcessor.processOnDeleteInverse(DeletePolicyProcessor.java:132) ~[jmix-data-1.2.0.jar:na]
	at io.jmix.data.impl.DeletePolicyProcessor.process(DeletePolicyProcessor.java:95) ~[jmix-data-1.2.0.jar:na]
	at io.jmix.eclipselink.impl.EclipselinkPersistenceSupport$OnSaveEntityVisitor.processDeletePolicy(EclipselinkPersistenceSupport.java:693) ~[jmix-eclipselink-1.2.0.jar:na]
	at io.jmix.eclipselink.impl.EclipselinkPersistenceSupport$OnSaveEntityVisitor.visit(EclipselinkPersistenceSupport.java:660) ~[jmix-eclipselink-1.2.0.jar:na]
	at io.jmix.eclipselink.impl.EclipselinkPersistenceSupport.beforeStore(EclipselinkPersistenceSupport.java:275) ~[jmix-eclipselink-1.2.0.jar:na]
	at io.jmix.eclipselink.impl.EclipselinkPersistenceSupport.traverseEntities(EclipselinkPersistenceSupport.java:262) ~[jmix-eclipselink-1.2.0.jar:na]
	at io.jmix.eclipselink.impl.EclipselinkPersistenceSupport.processFlush(EclipselinkPersistenceSupport.java:233) ~[jmix-eclipselink-1.2.0.jar:na]
	at io.jmix.eclipselink.impl.JpaDataStore.beforeSaveTransactionCommit(JpaDataStore.java:354) ~[jmix-eclipselink-1.2.0.jar:na]
	at io.jmix.core.datastore.AbstractDataStore.save(AbstractDataStore.java:229) ~[jmix-core-1.2.0.jar:na]
	at io.jmix.core.impl.UnconstrainedDataManagerImpl.saveContextToStore(UnconstrainedDataManagerImpl.java:257) ~[jmix-core-1.2.0.jar:na]
	at io.jmix.core.impl.UnconstrainedDataManagerImpl.save(UnconstrainedDataManagerImpl.java:216) ~[jmix-core-1.2.0.jar:na]
	at io.jmix.core.impl.UnconstrainedDataManagerImpl.remove(UnconstrainedDataManagerImpl.java:142) ~[jmix-core-1.2.0.jar:na]
	at io.jmix.rest.impl.service.EntitiesControllerManager.deleteEntity(EntitiesControllerManager.java:750) ~[jmix-rest-1.2.0.jar:na]
	at io.jmix.rest.impl.controller.EntitiesController.deleteEntity(EntitiesController.java:164) ~[jmix-rest-1.2.0.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.15.jar:5.3.15]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:931) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:671) ~[javax.servlet-api-4.0.1.jar:4.0.1]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
...
```

**Comment by Afanasevaa36** [comment]
1.3.999-SNAPSHOT - verified
