### ISSUE TITLE
Pagination throws IllegalStateException while creating new record in empty data container

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#685]
### Description
See forum discussion: https://forum.jmix.io/t/illegalstateexception-paginationdatabinder-has-first-result-that-is-not-applicable-for-the-page-ranges/1339

### Steps to reproduce
1. Create an entity and browse, edit screens 
2. Add to browse screen:
```
<pagination id="pagination" itemsPerPageVisible="true" align="TOP_RIGHT">
    <loaderProvider loaderId="loader_id"/>
</pagination>
```
And remove `<simplePagination/>` from table.
3. Launch the app.
4. Open browse screen and create new record:

**AR**
```
java.lang.IllegalStateException: PaginationDataBinder has first result that is not applicable for the page ranges
	at io.jmix.ui.widget.JmixPagination.setCurrentPageNumberByFirstResult(JmixPagination.java:213)
	at io.jmix.ui.component.impl.PaginationImpl.onCollectionChange(PaginationImpl.java:217)
	at io.jmix.ui.component.pagination.data.AbstractPaginationDataBinder.lambda$attachCollectionChangeListener$0(AbstractPaginationDataBinder.java:48)
	at io.jmix.ui.model.impl.WeakCollectionChangeListener.accept(WeakCollectionChangeListener.java:42)
	at io.jmix.ui.model.impl.WeakCollectionChangeListener.accept(WeakCollectionChangeListener.java:25)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.model.impl.CollectionContainerImpl.fireCollectionChanged(CollectionContainerImpl.java:241)
	at io.jmix.ui.model.impl.CollectionContainerImpl.lambda$getMutableItems$0(CollectionContainerImpl.java:89)
	at io.jmix.ui.model.impl.ObservableList.fireCollectionChanged(ObservableList.java:69)
	at io.jmix.ui.model.impl.ObservableList.add(ObservableList.java:97)
	at io.jmix.ui.builder.EditorBuilderProcessor.lambda$buildEditor$0(EditorBuilderProcessor.java:121)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124)
	at io.jmix.ui.screen.Screen.close(Screen.java:330)
	at io.jmix.ui.screen.StandardEditor.lambda$closeWithCommit$11(StandardEditor.java:617)
	at io.jmix.ui.util.SuccessOperationResult.compose(SuccessOperationResult.java:35)
	at io.jmix.ui.screen.StandardEditor.closeWithCommit(StandardEditor.java:617)
	at io.jmix.ui.screen.StandardEditor.commitAndClose(StandardEditor.java:570)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220)
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
```

Possible workaround:
1. Inject loader to the screen controller
2. In `AfterShowEvent` set to the loader first result 0:
```
@Autowired
private CollectionLoader<Customer> customersDl;

@Subscribe
public void onAfterShow(AfterShowEvent event) {
    customersDl.setFirstResult(0);
}
```
Related issue: https://github.com/jmix-framework/jmix/issues/644

**Comment by kendovitskii** [comment]
verified on
IntelliJ IDEA 2021.3 (Community Edition)
    io.jmix.studio (1.3.SNAPSHOT4204-213)
    jmix version (1.3.999-SNAPSHOT)
