### ISSUE TITLE
Various problems with DataContext and EntityInspector

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#687]
### 1. [fixed] Unfetched attribute exception during DataContext merge 
```java
ava.lang.IllegalStateException: Cannot get unfetched attribute [commonData] from detached object com.company.Contract-d98305ff-7cbf-bd98-27d1-ec1c0bfee43f [detached].
at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100)
at io.jmix.eclipselink.impl.JmixEntityFetchGroup.onUnfetchedAttribute(JmixEntityFetchGroup.java:67)
at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:3027)
at com.company.Document._persistence_checkFetched(Document.java)
at com.company.Contract._persistence_get_commonData(Contract.java)
at com.company.Contract.getCommonData(Contract.java:158)
at io.jmix.core.entity.BaseEntityEntry.getAttributeValue(BaseEntityEntry.java:85)
at io.jmix.core.entity.BaseEntityEntry.setAttributeValue(BaseEntityEntry.java:101)
at io.jmix.core.entity.EntityValues.setValue(EntityValues.java:89)
at io.jmix.ui.model.impl.DataContextImpl.setPropertyValue(DataContextImpl.java:342)
at io.jmix.ui.model.impl.DataContextImpl.setPropertyValue(DataContextImpl.java:336)
at io.jmix.ui.model.impl.DataContextImpl.mergeState(DataContextImpl.java:298)
at io.jmix.ui.model.impl.DataContextImpl.internalMerge(DataContextImpl.java:236)
at io.jmix.ui.model.impl.DataContextImpl.mergeState(DataContextImpl.java:312)
at io.jmix.ui.model.impl.DataContextImpl.internalMerge(DataContextImpl.java:236)
at io.jmix.ui.model.impl.DataContextImpl.merge(DataContextImpl.java:180)
at io.jmix.ui.model.impl.DataContextImpl.merge(DataContextImpl.java:191)
at io.jmix.ui.model.impl.DataContextImpl.mergeCommitted(DataContextImpl.java:775)
at io.jmix.ui.model.impl.DataContextImpl.commit(DataContextImpl.java:651)
at io.jmix.ui.screen.StandardEditor.lambda$commitChanges$9(StandardEditor.java:427)
at io.jmix.ui.screen.StandardEditor.commitChanges(StandardEditor.java:455)
at io.jmix.ui.screen.StandardEditor.closeWithCommit(StandardEditor.java:616)
at io.jmix.ui.screen.StandardEditor.commitAndClose(StandardEditor.java:570)
...
```
**Cause:** merging fetched attribute into copy with unfetched attribute.
**Solution:** additional checks added. In case of destination embedded or local attribute not loaded it will not be merged

### 2. [fixed] Absent owner component for embedded property form in `EntityInspectorEditor`
**Solution:** added.

### QA Notes:
Case 1: covered by autotest, not need to be tested
Case 2:
1. Create new project
2.Create Embeddable entity with ManyToOne reference, e.g.: 
```java
@JmixEntity
@Embeddable
public class Address {
    @Column(name = "ADDR_STR")
    private String addrStr;

    @JoinColumn(name = "ITEM")
    @ManyToOne(fetch = FetchType.LAZY)
    private Item item; //some jpa entity

   //... getters and setters ...
}
```
3.Create entity and add embedded one to it:
```java
@JmixEntity
@Table(name = "PERSON")
@Entity
public class Person {
    @JmixGeneratedValue
    @Column(name = "ID", nullable = false)
    @Id
    private UUID id;

    @InstanceName
    @Column(name = "NAME")
    private String name;

    @EmbeddedParameters(nullAllowed = false)
    @Embedded
    private Address address;

  //... getters and setters
}
```
3. Open Entity Inspector and select entity `Person`
4. Create new, try to select item (press `...`)
E.R. Item browser opened
A.R.
```java
java.lang.IllegalArgumentException: Null reference passed as parameter
	at io.jmix.core.common.util.Preconditions.checkNotNullArgument(Preconditions.java:87)
	at io.jmix.ui.ScreenBuilders.lookup(ScreenBuilders.java:233)
	at io.jmix.ui.action.entitypicker.EntityLookupAction.execute(EntityLookupAction.java:139)
	at io.jmix.ui.action.entitypicker.EntityLookupAction.actionPerform(EntityLookupAction.java:120)
	at io.jmix.ui.component.impl.ValuePickerImpl.lambda$setupButtonAction$0(ValuePickerImpl.java:231)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	...
```

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Community Edition)
io.jmix.studio (1.3.SNAPSHOT4226-213)
jmix version (1.2.999-SNAPSHOT)
