### ISSUE TITLE
NPE when "Use existing fetch plan" is selected and no fetch plan is specified

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#718]
- Create a report with "List of entities" parameter
- Select "Use existing fetch plan" for the dataset, and leave "Fetch plan name" field empty
- You will get NPE on report execution:
```
Caused by: java.lang.NullPointerException: null
	at io.jmix.core.impl.FetchPlanRepositoryImpl.isDefaultFetchPlan(FetchPlanRepositoryImpl.java:421) ~[jmix-core-1.2.2.jar:na]
	at io.jmix.core.impl.FetchPlanRepositoryImpl.retrieveFetchPlan(FetchPlanRepositoryImpl.java:414) ~[jmix-core-1.2.2.jar:na]
	at io.jmix.core.impl.FetchPlanRepositoryImpl.findFetchPlan(FetchPlanRepositoryImpl.java:213) ~[jmix-core-1.2.2.jar:na]
	at io.jmix.core.impl.FetchPlanRepositoryImpl.getFetchPlan(FetchPlanRepositoryImpl.java:188) ~[jmix-core-1.2.2.jar:na]
	at io.jmix.core.impl.FetchPlanRepositoryImpl.getFetchPlan(FetchPlanRepositoryImpl.java:174) ~[jmix-core-1.2.2.jar:na]
	at io.jmix.reports.libintegration.AbstractEntityDataLoader.getFetchPlan(AbstractEntityDataLoader.java:68) ~[jmix-reports-1.2.2.jar:na]
	at io.jmix.reports.libintegration.AbstractEntityDataLoader.reloadEntityByDataSetFetchPlan(AbstractEntityDataLoader.java:46) ~[jmix-reports-1.2.2.jar:na]
	at io.jmix.reports.libintegration.MultiEntityDataLoader.loadData(MultiEntityDataLoader.java:91) ~[jmix-reports-1.2.2.jar:na]
```

**Comment by knstvk** [comment]
Take this project:
[demo.zip](https://github.com/jmix-framework/jmix/files/9016800/demo.zip)

![image](https://user-images.githubusercontent.com/5513878/176602479-28192774-9a83-459e-92d8-9e21c9475d3d.png)

**Comment by reznikova21** [comment]
1.3.999-SNAPSHOT - verified
