### ISSUE TITLE
CreateProcess error=193, %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by flybyray** [jmix-framework/jmix#736]
When scripts are executed within WSL GenerateModelProcess throws errors like this

```
2022-05-27 10:48:20,430 [2339461]   INFO - #c.h.j.b.l.JmixLiquibaseManager - Unable to read databasechangelog. Most possibly is does not exist.
2022-05-27 10:48:20,433 [2339464]   INFO - #c.h.j.i.a.l.UpdateDatabaseActionProcess - Found unapplied changelogs: [io/jmix/uidata/liquibase/changelog/001-ui-data.xml, io/jmix/securitydata/liquibase/changelog/001-security-data.xml, io/jmix/securitydata/liquibase/changelog/002-security-data.xml, io/jmix/securitydata/liquibase/changelog/003-security-data.xml, com/ndgit/jmix/xcaweb/liquibase/changelog/010-init-user.xml]
2022-05-27 10:48:21,024 [2340055]   WARN - #c.h.j.i.u.m.GenerateModelProcess - Cannot run program "\\wsl$\Ubuntu\usr\lib\jvm\java-17-openjdk-amd64\bin\java": CreateProcess error=193, %1 is not a valid Win32 application
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "\\wsl$\Ubuntu\usr\lib\jvm\java-17-openjdk-amd64\bin\java": CreateProcess error=193, %1 is not a valid Win32 application
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:362)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:92)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:41)
	at com.haulmont.jmixstudio.intellij.action.liquibase.JmixLiquibaseUpdateProcess.executeCommandLine(ApplyChangeLogsProcesses.kt:104)
	at com.haulmont.jmixstudio.liquibase.LiquibaseUpdateProcess$run$2.invokeSuspend(LiquibaseUpdateProcess.kt:91)
	at com.haulmont.jmixstudio.liquibase.LiquibaseUpdateProcess$run$2.invoke(LiquibaseUpdateProcess.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.haulmont.jmixstudio.liquibase.LiquibaseUpdateProcess.run$suspendImpl(LiquibaseUpdateProcess.kt:50)
	at com.haulmont.jmixstudio.liquibase.LiquibaseUpdateProcess.run(LiquibaseUpdateProcess.kt)
	at com.haulmont.jmixstudio.intellij.action.liquibase.UpdateDataStoreProcess$run$2.invokeSuspend(ApplyChangeLogsProcesses.kt:65)
	at com.haulmont.jmixstudio.intellij.action.liquibase.UpdateDataStoreProcess$run$2.invoke(ApplyChangeLogsProcesses.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.haulmont.jmixstudio.intellij.action.liquibase.UpdateDataStoreProcess.run(ApplyChangeLogsProcesses.kt:46)
	at com.haulmont.jmixstudio.intellij.action.liquibase.UpdateDatabaseActionProcess$run$2.invokeSuspend(UpdateDatabaseActionProcess.kt:46)
	at com.haulmont.jmixstudio.intellij.action.liquibase.UpdateDatabaseActionProcess$run$2.invoke(UpdateDatabaseActionProcess.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.haulmont.jmixstudio.intellij.action.liquibase.UpdateDatabaseActionProcess.run(UpdateDatabaseActionProcess.kt:20)
	at com.haulmont.jmixstudio.intellij.ui.modelgeneration.GenerateModelProcess.checkDbState(GenerateModelProcess.kt:87)
	at com.haulmont.jmixstudio.intellij.ui.modelgeneration.GenerateModelProcess$run$2.invokeSuspend(GenerateModelProcess.kt:40)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.io.IOException: Cannot run program "\\wsl$\Ubuntu\usr\lib\jvm\java-17-openjdk-amd64\bin\java": CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:438)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:352)
	... 58 more
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
```

**Comment by gorbunkov** [comment]
The issue for Jmix Studio: https://youtrack.jmix.io/issue/JST-3076
