### ISSUE TITLE
Ignore saved filter if it cannot be loaded due to changes in data model

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#747]
Now the whole screen cannot be opened with the exception like:
```
Caused by: java.lang.IllegalArgumentException: Can’t create component for the ‘endedDate’ with given meta class ‘Request’
at io.jmix.ui.component.UiComponentsGenerator.generate(UiComponentsGenerator.java:57) ~[jmix-ui-1.2.0.jar!/:na]
at io.jmix.ui.component.propertyfilter.SingleFilterSupport.generateValueComponent(SingleFilterSupport.java:56) ~[jmix-ui-1.2.0.jar!/:na]
at io.jmix.ui.component.impl.PropertyFilterImpl.setOperationInternal(PropertyFilterImpl.java:177) ~[jmix-ui-1.2.0.jar!/:na]
at io.jmix.ui.component.impl.PropertyFilterImpl.setOperation(PropertyFilterImpl.java:151) ~[jmix-ui-1.2.0.jar!/:na]
at io.jmix.ui.component.propertyfilter.PropertyFilterConverter.convertToComponent(PropertyFilterConverter.java:70) ~[jmix-ui-1.2.0.jar!/:na]
at io.jmix.ui.component.propertyfilter.PropertyFilterConverter.convertToComponent(PropertyFilterConverter.java:40) ~[jmix-ui-1.2.0.jar!/:na]
at io.jmix.ui.component.groupfilter.GroupFilterConverter.convertToComponent(GroupFilterConverter.java:71) ~[jmix-ui-1.2.0.jar!/:na]
at io.jmix.ui.component.groupfilter.GroupFilterConverter.convertToComponent(GroupFilterConverter.java:40) ~[jmix-ui-1.2.0.jar!/:na]
at io.jmix.uidata.filter.FilterConfigurationConverter.toConfiguration(FilterConfigurationConverter.java:62) ~[jmix-ui-data-1.2.0.jar!/:na]
at io.jmix.uidata.filter.UiDataFilterSupport.getConfigurationsMap(UiDataFilterSupport.java:91) ~[jmix-ui-data-1.2.0.jar!/:na]
at io.jmix.ui.component.impl.FilterImpl.loadConfigurationsAndApplyDefault(FilterImpl.java:373) ~[jmix-ui-1.2.0.jar!/:na]
at io.jmix.ui.xml.layout.loader.FilterLoader.lambda$loadConfigurations$4(FilterLoader.java:152) ~[jmix-ui-1.2.0.jar!/:na]
at io.jmix.ui.xml.layout.loader.ComponentLoaderContext.executePostInitTasks(ComponentLoaderContext.java:141) ~[jmix-ui-1.2.0.jar!/:na]
```

**Comment by reznikova21** [comment]
1.3.999-SNAPSHOT - verified
