### ISSUE TITLE
[Table/DataGrid] Programmatic aggregation creation leads to NPE

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#765]
Add aggregation programmatically:

```
public class ProductBrowse extends StandardLookup<Product> {

    @Autowired
    private GroupTable<Product> productsTable;

    @Subscribe
    public void onInit(InitEvent event) {
        productsTable.setAggregatable(true);
        productsTable.setAggregationStyle(Table.AggregationStyle.BOTTOM);

        Table.Column<Product> column = Objects.requireNonNull(productsTable.getColumn("price"));

        AggregationInfo aggregation = new AggregationInfo();
        aggregation.setPropertyPath(column.getMetaPropertyPathNN());
        aggregation.setType(AggregationInfo.Type.SUM);

        column.setAggregation(aggregation);
    }
}
```

ER:

Aggregation settings are applied

AR:

```
java.lang.NullPointerException: Aggregation must be executed at least by one field
	at io.jmix.ui.component.data.aggregation.impl.AggregatableDelegate.aggregate(AggregatableDelegate.java:78)
	at io.jmix.ui.component.impl.AbstractTable.__aggregate(AbstractTable.java:2788)
	at io.jmix.ui.component.impl.GroupTableImpl$AggregatableGroupTableDataContainer.aggregate(GroupTableImpl.java:164)
	at io.jmix.ui.widget.JmixTable.updateFooterAggregation(JmixTable.java:881)
	at io.jmix.ui.widget.JmixTable.beforeClientResponse(JmixTable.java:858)
```

**Comment by reznikova21** [comment]
1.3.999-SNAPSHOT - verified
