### ISSUE TITLE
REST API: Entity operation fail if identity attribute is not called "id"

### ISSUE THREAD

**Issue by joelbohnes** [jmix-framework/jmix#775]
# Version
Version: Jmix 1.2.3

# Problem Description
If the primary key attribute in a entity class is not named "id" several REST Operations
that operate to a single entity fail. For example a entity retrieval (`GET entities/<name>/<id>`) fails
for such entities.

Additionally, while listing these entities, a "id" attribute is added even though no such attribute
exists.

# Example
**Course.java**
```java
@JmixEntity
@Table(name = "COURSE")
@Entity
public class Course {
    @Column(name = "ID", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer myId;

    @Column(name="NAME", nullable=false)
    @InstanceName
    private String name;

   ... getter/setter omitted
}
```

## Listing Entities
Listing these entities works - but notice that a "id" attribute is added to the json even though such an attribute
does not exist in the entity class. Unsure if this is a feature or a bug.

**Request**
`GET http://localhost:8080/rest/entities/Course`

**Response**
```json
[
    {
        "_entityName": "Course",
        "_instanceName": "Test",
        "id": "1",
        "myId": 1,
        "name": "Test"
    }
]
```

## Retrieving entity by id
**Request**
`GET http://localhost:8080/rest/entities/Course/1`

**Response**
`500 Internal Server Error`
```json
{
    "error": "Server error",
    "details": ""
}
```

**Relevant server log**
```
java.lang.NoSuchMethodException: com.company.mtm.entity.Course.getId()
	at java.base/java.lang.Class.getMethod(Class.java:2227) ~[na:na]
	at io.jmix.rest.impl.service.EntitiesControllerManager.getIdFromString(EntitiesControllerManager.java:784) ~[jmix-rest-1.2.3.jar:na]
	at io.jmix.rest.impl.service.EntitiesControllerManager.loadEntity(EntitiesControllerManager.java:127) ~[jmix-rest-1.2.3.jar:na]
	at io.jmix.rest.impl.controller.EntitiesController.loadEntity(EntitiesController.java:54) ~[jmix-rest-1.2.3.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.19.jar:5.3.19]
<log truncated>
```
## QA Notes
Check "Retrieving entity by id" case only.
Case "Listing Entities" is not a bug.

**Comment by joelbohnes** [comment]
Cause is the hardcoded call to the "getId" inside `EntitiesControllerManager`:
https://github.com/jmix-framework/jmix/blob/212b03171bdb552293602fa0a8e83e5c1a9b0006/jmix-rest/rest/src/main/java/io/jmix/rest/impl/service/EntitiesControllerManager.java#L784-L785

Maybe we could use the  `getPrimaryKeyProperty` from the `MetadataTools` instead. Something like:
```java
Class<?> idClass = metadataTools.getPrimaryKeyProperty(metaClass).getJavaType();
```
