### ISSUE TITLE
ClassCastException in Business Calendars when creating holidays

### ISSUE THREAD

**Issue by Afanasevaa36** [jmix-framework/jmix#784]
Jmix version: 1.3.0-RC1
Jmix Studio plugin version: 1.3.SNAPSHOT4339-213
IntelliJ version: IntelliJ IDEA 2022.1 (Ultimate Edition)

Steps:
1. Create new project.
2. Add add-ons Business Calendars.
3. Run project.
4. Log in admin/admin.
5. Click Administration>Business Calendars>Create>Create.

AR:
![Screenshot_8](https://user-images.githubusercontent.com/95623805/174749935-5b189d37-0fd4-4829-aac2-2dd191e423d1.png)

```java.lang.ClassCastException: class [Ljava.time.Month; cannot be cast to class [Lio.jmix.core.metamodel.datatype.impl.EnumClass; ([Ljava.time.Month; is in module java.base of loader 'bootstrap'; [Lio.jmix.core.metamodel.datatype.impl.EnumClass; is in unnamed module of loader 'app')
	at io.jmix.ui.component.data.options.EnumOptions.<init>(EnumOptions.java:32)
	at io.jmix.ui.component.data.DataAwareComponentsTools.setupOptions(DataAwareComponentsTools.java:223)
	at io.jmix.ui.component.impl.ComboBoxImpl.valueBindingConnected(ComboBoxImpl.java:168)
	at io.jmix.ui.component.impl.AbstractValueComponent.setValueSource(AbstractValueComponent.java:58)
	at io.jmix.ui.xml.layout.loader.AbstractComponentLoader.lambda$loadContainer$0(AbstractComponentLoader.java:842)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.jmix.ui.xml.layout.loader.AbstractComponentLoader.loadContainer(AbstractComponentLoader.java:841)
	at io.jmix.ui.xml.layout.loader.AbstractComponentLoader.loadData(AbstractComponentLoader.java:834)
	at io.jmix.ui.xml.layout.loader.AbstractFieldLoader.loadComponent(AbstractFieldLoader.java:36)
	at io.jmix.ui.xml.layout.loader.ComboBoxLoader.loadComponent(ComboBoxLoader.java:34)
	at io.jmix.ui.xml.layout.loader.FormLoader.loadComponent(FormLoader.java:168)
	at io.jmix.ui.xml.layout.loader.FormLoader.loadComponents(FormLoader.java:153)
	at io.jmix.ui.xml.layout.loader.FormLoader.loadColumns(FormLoader.java:132)
	at io.jmix.ui.xml.layout.loader.FormLoader.loadComponent(FormLoader.java:87)
	at io.jmix.ui.xml.layout.loader.ContainerLoader.loadSubComponents(ContainerLoader.java:36)
	at io.jmix.ui.xml.layout.loader.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:74)
	at io.jmix.ui.xml.layout.loader.WindowLoader.loadComponent(WindowLoader.java:85)
	at io.jmix.ui.sys.ScreensImpl.loadWindowFromXml(ScreensImpl.java:319)
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:204)
	at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:133)

**Comment by artemy63** [comment]
Fixed in `master` and `release_1_3` branches

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT - Verified
