### ISSUE TITLE
Composition editing doesn't work for entities with identity ID

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#787]
- Create a usual Order / OrderLines composition, use Identity id for entities
- Create browser/editor for Order, editor for OrderLine
- Run the app, create Order, add OrderLine
- When saving OrderLine, you'll get the exception:

```
java.lang.IllegalArgumentException: entityId is null
	at io.jmix.core.common.util.Preconditions.checkNotNullArgument(Preconditions.java:101)
	at io.jmix.core.EntitySet.optional(EntitySet.java:80)
	at io.jmix.core.EntitySet.optional(EntitySet.java:94)
	at io.jmix.ui.screen.StandardEditor.lambda$commitChanges$9(StandardEditor.java:435)
	at io.jmix.ui.screen.StandardEditor.commitChanges(StandardEditor.java:455)
	at io.jmix.ui.screen.StandardEditor.closeWithCommit(StandardEditor.java:616)
	at io.jmix.ui.screen.StandardEditor.commitAndClose(StandardEditor.java:570)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220)
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2022.1.3 (Community Edition)
io.jmix.studio (1.3.SNAPSHOT4410-213)
jmix versions (1.3.0, 1.3.0-RC1)
