### ISSUE TITLE
JPQL query with condition comparing references doesn't work in JPQL dataset

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#809]
Jmix version: 1.3.0

Create a report with JPQL dataset. The dataset must contain a query with condition that compare references, e.g.:

```
select
e.number as "number"
from Order_ e
where e.manager = ${manager}
```

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/7888486/177176428-18f3430a-3649-4e6d-98a7-2eca515a3176.png">

Try to run the report. As a result, you'll get the exception:

```
Caused by: java.lang.IllegalArgumentException: You have attempted to set a value of type class java.util.UUID for parameter 1 with expected type of class com.company.reportrefparam.entity.User from query string select

e.number from Order_ e
where e.manager = ?1.
	at org.eclipse.persistence.internal.jpa.QueryImpl.setParameterInternal(QueryImpl.java:946) ~[org.eclipse.persistence.jpa-2.7.9-6-jmix.jar:na]
	at org.eclipse.persistence.internal.jpa.QueryImpl.setParameterInternal(QueryImpl.java:920) ~[org.eclipse.persistence.jpa-2.7.9-6-jmix.jar:na]
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:481) ~[org.eclipse.persistence.jpa-2.7.9-6-jmix.jar:na]
	at io.jmix.eclipselink.impl.JmixEclipseLinkQuery$Param.apply(JmixEclipseLinkQuery.java:931) ~[jmix-eclipselink-1.3.0.jar:na]
	at io.jmix.eclipselink.impl.JmixEclipseLinkQuery.getQuery(JmixEclipseLinkQuery.java:489) ~[jmix-eclipselink-1.3.0.jar:na]
	at io.jmix.eclipselink.impl.JmixEclipseLinkQuery.getResultList(JmixEclipseLinkQuery.java:134) ~[jmix-eclipselink-1.3.0.jar:na]
	at io.jmix.reports.libintegration.JpqlDataLoader.lambda$executeQuery$0(JpqlDataLoader.java:110) ~[jmix-reports-1.3.0.jar:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.20.jar:5.3.20]
	at io.jmix.reports.libintegration.JpqlDataLoader.executeQuery(JpqlDataLoader.java:108) ~[jmix-reports-1.3.0.jar:na]
	at io.jmix.reports.libintegration.JpqlDataLoader.loadData(JpqlDataLoader.java:91) ~[jmix-reports-1.3.0.jar:na]
	... 112 common frames omitted
```

The problem is the `io.jmix.reports.libintegration.JpqlParametersConverter` converts all parameters which are entities into their IDs. This probably came from old CUBA behavior.

The workaround is to override the query in the following way:

```
select
e.number as "number"
from Order_ e
where e.manager.id = ${manager}
```

Sample project: [report-ref-param.zip](https://github.com/jmix-framework/jmix/files/9040336/report-ref-param.zip)

The report: [Report for entity _Order_.zip](https://github.com/jmix-framework/jmix/files/9040338/Report.for.entity._Order_.zip)

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2022.1.3 (Community Edition)
io.jmix.studio (1.4.SNAPSHOT4449-213)
jmix version (1.4.999-SNAPSHOT)
