### ISSUE TITLE
Support dynamic attributes in Search add-on

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#829]
We have two options here: 

1. Implement dynamic attributes support in Search add-on
2. Provide a sample that demonstrates how to hook into indexing and searching in order to support dynamic attributes at project level

Forum topic: https://forum.jmix.io/t/dynamic-attributes-in-elasticsearch-index/1316/6

**Comment by knstvk** [comment]
Depends on #3218

**Comment by fractal3000** [comment]
Test cases:

1. There are no "Dynamic Attributes add-on", but there is "Search add-on"
    There are no configured indexes for "Search add-on"
    There is search indexes but @DynamicAttributes annotation is not used
    There is search indexes but @DynamicAttributes annotation is used(the annoation should be ignored with a message in the console log)
    Perform ElasticSearch and OpenSearch smoke test

**Comment by SergeiAksenov2** [comment]
### Environment

Jmix version: 2.8.999-SNAPSHOT
Jmix Studio Plugin Version: 2.8.SNAPSHOT8034-252
IntelliJ version: IntelliJ IDEA 2025.2.5 (Community Edition)

### Bug Description

Creation manual Index MappingDefinition with both StaticAttributesGroupConfiguration and DynamicAttributesGroupConfiguration
without .withOrder(n) leads to project start up error.

### Steps To Reproduce

1. UseEntity IndexDefinition with manual MappingDefinition in project.
2. Run the demo project.

WA:
If add method .withOrder(n) to all AttributesGroupConfiguration.builder(), the project starts propely.


```
@ExtendedSearch
@JmixEntitySearchIndex(entity = Car.class)
public interface CarIndexDefinition {

    @ManualMappingDefinition
    default MappingDefinition mapping(AutoMappingStrategy autoMappingStrategy,
                                      SimplePropertyValueExtractor simplePropertyValueExtractor) {

        return MappingDefinition.builder()
                .addStaticAttributesGroup(
                        StaticAttributesGroupConfiguration.builder()
                                .includeProperties("*")
                                .excludeProperties("name")
                                .withFieldMappingStrategyClass(AutoMappingStrategy.class)
                                .build()
                )
                .addDynamicAttributesGroup(
                        DynamicAttributesGroupConfiguration.builder()
                                .excludeCategories("CarCategory2")
                                .withFieldMappingStrategyClass(AutoMappingStrategy.class)
                                .build()
                )
                .addDynamicAttributesGroup(
                        DynamicAttributesGroupConfiguration.builder()
                                .excludeProperties("carCategory1Attr2")
                                .withFieldMappingStrategyClass(AutoMappingStrategy.class)
                                .build()
                )
                .addDynamicAttributesGroup(
                        DynamicAttributesGroupConfiguration.builder()
                                .withFieldMappingStrategyClass(AutoMappingStrategy.class)
                                .withReferenceAttributesIndexingMode(ReferenceAttributesIndexingMode.INSTANCE_NAME_ONLY)
                                .build()
                )
                .build();
    }
}

```

### Current Behavior

Run error appears:

```
2025-12-05T10:37:53.486+04:00 ERROR 21240 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'search_EntityIndexingManagementFacade': Unsatisfied dependency expressed through field 'indexingQueueManager': Error creating bean with name 'search_IndexingQueueManager' defined in class path resource [io/jmix/autoconfigure/search/SearchAutoConfiguration.class]: Failed to instantiate [io.jmix.search.index.queue.IndexingQueueManager]: Factory method 'indexingQueueManager' threw exception with message: Error creating bean with name 'io.jmix.search.index.queue.impl.JpaIndexingQueueManager': Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'search_OpenSearchEntityIndexer' defined in class path resource [io/jmix/autoconfigure/searchopensearch/SearchOpenSearchAutoConfiguration.class]: Unsatisfied dependency expressed through method 'openSearchEntityIndexer' parameter 2: Error creating bean with name 'search_IndexConfigurationManager' defined in URL [jar:file:/C:/Users/../.gradle/caches/modules-2/files-2.1/io.jmix.search/jmix-search/2.8.999-SNAPSHOT/f9dee1dd46220c5c19e111782634343e0bb3c43e/jmix-search-2.8.999-SNAPSHOT.jar!/io/jmix/search/index/mapping/IndexConfigurationManager.class]: Failed to instantiate [io.jmix.search.index.mapping.IndexConfigurationManager]: Constructor threw exception
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:788) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:768) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:146) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:509) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1459) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:606) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:373) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.instantiateSingleton(DefaultListableBeanFactory.java:1221) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingleton(DefaultListableBeanFactory.java:1187) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:1123) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:987) ~[spring-context-6.2.11.jar:6.2.11]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627) ~[spring-context-6.2.11.jar:6.2.11]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.5.6.jar:3.5.6]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[spring-boot-3.5.6.jar:3.5.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[spring-boot-3.5.6.jar:3.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) ~[spring-boot-3.5.6.jar:3.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1361) ~[spring-boot-3.5.6.jar:3.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1350) ~[spring-boot-3.5.6.jar:3.5.6]
	at com.company.t829searchdynattr.T829SearchDynattrApplication.main(T829SearchDynattrApplication.java:32) ~[main/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'search_IndexingQueueManager' defined in class path resource [io/jmix/autoconfigure/search/SearchAutoConfiguration.class]: Failed to instantiate [io.jmix.search.index.queue.IndexingQueueManager]: Factory method 'indexingQueueManager' threw exception with message: Error creating bean with name 'io.jmix.search.index.queue.impl.JpaIndexingQueueManager': Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'search_OpenSearchEntityIndexer' defined in class path resource [io/jmix/autoconfigure/searchopensearch/SearchOpenSearchAutoConfiguration.class]: Unsatisfied dependency expressed through method 'openSearchEntityIndexer' parameter 2: Error creating bean with name 'search_IndexConfigurationManager' defined in URL [jar:file:/C:/Users/./.gradle/caches/modules-2/files-2.1/io.jmix.search/jmix-search/2.8.999-SNAPSHOT/f9dee1dd46220c5c19e111782634343e0bb3c43e/jmix-search-2.8.999-SNAPSHOT.jar!/io/jmix/search/index/mapping/IndexConfigurationManager.class]: Failed to instantiate [io.jmix.search.index.mapping.IndexConfigurationManager]: Constructor threw exception
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:645) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1375) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1205) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:569) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:373) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1760) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1643) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:785) ~[spring-beans-6.2.11.jar:6.2.11]
	... 22 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.jmix.search.index.queue.IndexingQueueManager]: Factory method 'indexingQueueManager' threw exception with message: Error creating bean with name 'io.jmix.search.index.queue.impl.JpaIndexingQueueManager': Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'search_OpenSearchEntityIndexer' defined in class path resource [io/jmix/autoconfigure/searchopensearch/SearchOpenSearchAutoConfiguration.class]: Unsatisfied dependency expressed through method 'openSearchEntityIndexer' parameter 2: Error creating bean with name 'search_IndexConfigurationManager' defined in URL [jar:file:/C:/Users/../.gradle/caches/modules-2/files-2.1/io.jmix.search/jmix-search/2.8.999-SNAPSHOT/f9dee1dd46220c5c19e111782634343e0bb3c43e/jmix-search-2.8.999-SNAPSHOT.jar!/io/jmix/search/index/mapping/IndexConfigurationManager.class]: Failed to instantiate [io.jmix.search.index.mapping.IndexConfigurationManager]: Constructor threw exception
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.lambda$instantiate$0(SimpleInstantiationStrategy.java:200) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiateWithFactoryMethod(SimpleInstantiationStrategy.java:89) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:169) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-6.2.11.jar:6.2.11]
	... 35 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.jmix.search.index.queue.impl.JpaIndexingQueueManager': Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'search_OpenSearchEntityIndexer' defined in class path resource [io/jmix/autoconfigure/searchopensearch/SearchOpenSearchAutoConfiguration.class]: Unsatisfied dependency expressed through method 'openSearchEntityIndexer' parameter 2: Error creating bean with name 'search_IndexConfigurationManager' defined in URL [jar:file:/C:/Users/../.gradle/caches/modules-2/files-2.1/io.jmix.search/jmix-search/2.8.999-SNAPSHOT/f9dee1dd46220c5c19e111782634343e0bb3c43e/jmix-search-2.8.999-SNAPSHOT.jar!/io/jmix/search/index/mapping/IndexConfigurationManager.class]: Failed to instantiate [io.jmix.search.index.mapping.IndexConfigurationManager]: Constructor threw exception
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:804) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:240) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1395) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:569) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:328) ~[spring-beans-6.2.11.jar:6.2.11]
	at io.jmix.autoconfigure.search.SearchAutoConfiguration.indexingQueueManager(SearchAutoConfiguration.java:75) ~[jmix-search-starter-2.8.999-SNAPSHOT.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.lambda$instantiate$0(SimpleInstantiationStrategy.java:172) ~[spring-beans-6.2.11.jar:6.2.11]
	... 38 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'search_OpenSearchEntityIndexer' defined in class path resource [io/jmix/autoconfigure/searchopensearch/SearchOpenSearchAutoConfiguration.class]: Unsatisfied dependency expressed through method 'openSearchEntityIndexer' parameter 2: Error creating bean with name 'search_IndexConfigurationManager' defined in URL [jar:file:/C:/Users/../.gradle/caches/modules-2/files-2.1/io.jmix.search/jmix-search/2.8.999-SNAPSHOT/f9dee1dd46220c5c19e111782634343e0bb3c43e/jmix-search-2.8.999-SNAPSHOT.jar!/io/jmix/search/index/mapping/IndexConfigurationManager.class]: Failed to instantiate [io.jmix.search.index.mapping.IndexConfigurationManager]: Constructor threw exception
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:804) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:546) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1375) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1205) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:569) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:373) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1760) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1643) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:913) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-6.2.11.jar:6.2.11]
	... 50 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'search_IndexConfigurationManager' defined in URL [jar:file:/C:/Users/../.gradle/caches/modules-2/files-2.1/io.jmix.search/jmix-search/2.8.999-SNAPSHOT/f9dee1dd46220c5c19e111782634343e0bb3c43e/jmix-search-2.8.999-SNAPSHOT.jar!/io/jmix/search/index/mapping/IndexConfigurationManager.class]: Failed to instantiate [io.jmix.search.index.mapping.IndexConfigurationManager]: Constructor threw exception
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:321) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:309) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1395) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:569) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:373) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1760) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1643) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:913) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-6.2.11.jar:6.2.11]
	... 64 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.jmix.search.index.mapping.IndexConfigurationManager]: Constructor threw exception
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:223) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.2.11.jar:6.2.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:318) ~[spring-beans-6.2.11.jar:6.2.11]
	... 78 common frames omitted
Caused by: java.lang.RuntimeException: Conflicted mapping fields: '+carCategory1AttrEntity' and '+carCategory1AttrEntity'
	at io.jmix.search.index.mapping.processor.impl.AnnotatedIndexDefinitionProcessor.lambda$processMappingDefinition$10(AnnotatedIndexDefinitionProcessor.java:367) ~[jmix-search-2.8.999-SNAPSHOT.jar:na]
	at java.base/java.util.HashMap.merge(HashMap.java:1383) ~[na:na]
	at java.base/java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1673) ~[na:na]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at io.jmix.search.index.mapping.processor.impl.AnnotatedIndexDefinitionProcessor.processMappingDefinition(AnnotatedIndexDefinitionProcessor.java:363) ~[jmix-search-2.8.999-SNAPSHOT.jar:na]
	at io.jmix.search.index.mapping.processor.impl.AnnotatedIndexDefinitionProcessor.createIndexMappingConfig(AnnotatedIndexDefinitionProcessor.java:226) ~[jmix-search-2.8.999-SNAPSHOT.jar:na]
	at io.jmix.search.index.mapping.processor.impl.AnnotatedIndexDefinitionProcessor.createIndexConfiguration(AnnotatedIndexDefinitionProcessor.java:108) ~[jmix-search-2.8.999-SNAPSHOT.jar:na]
	at io.jmix.search.index.mapping.IndexConfigurationManager.lambda$initializeIndexDefinitions$13(IndexConfigurationManager.java:257) ~[jmix-search-2.8.999-SNAPSHOT.jar:na]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[na:na]
	at io.jmix.search.index.mapping.IndexConfigurationManager.initializeIndexDefinitions(IndexConfigurationManager.java:256) ~[jmix-search-2.8.999-SNAPSHOT.jar:na]
	at io.jmix.search.index.mapping.IndexConfigurationManager.<init>(IndexConfigurationManager.java:79) ~[jmix-search-2.8.999-SNAPSHOT.jar:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:210) ~[spring-beans-6.2.11.jar:6.2.11]
	... 80 common frames omitted

```

### Expected Behavior

The project starts without errors.

### Sample Project

[T829-search-dynattr.zip](https://github.com/user-attachments/files/23955990/T829-search-dynattr.zip)
