### ISSUE TITLE
[Table] declarative aggregation definition leads to an exception

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#831]
Cause: https://github.com/jmix-framework/jmix/issues/765

```
<table id="testEntitiesTable"
          dataContainer="testEntitiesDc"
          aggregatable="true">
...
    <columns>
        <column id="username"/>
        <column id="value">
            <aggregation type="SUM"/>
        </column>
    </columns>
...
</table>
```

AR:

```
Caused by: java.lang.IllegalStateException: Table container is not AggregationContainer: class com.vaadin.v7.data.util.IndexedContainer
	at io.jmix.ui.widget.JmixTable.addContainerPropertyAggregation(JmixTable.java:647) ~[jmix-ui-1.3.1.jar:na]
	at io.jmix.ui.component.impl.AbstractTable$ColumnImpl.setAggregation(AbstractTable.java:2068) ~[jmix-ui-1.3.1.jar:na]
	at io.jmix.ui.xml.layout.loader.AbstractTableLoader.loadAggregation(AbstractTableLoader.java:582) ~[jmix-ui-1.3.1.jar:na]
	at io.jmix.ui.xml.layout.loader.AbstractTableLoader.loadColumn(AbstractTableLoader.java:517) ~[jmix-ui-1.3.1.jar:na]
	at io.jmix.ui.xml.layout.loader.AbstractTableLoader.loadColumns(AbstractTableLoader.java:374) ~[jmix-ui-1.3.1.jar:na]
	at io.jmix.ui.xml.layout.loader.AbstractTableLoader.loadTableData(AbstractTableLoader.java:160) ~[jmix-ui-1.3.1.jar:na]
```

For QA: Check both declarative and programmatic aggregation creation

**Comment by reznikova21** [comment]
1.3.999-SNAPSHOT - verified
