### ISSUE TITLE
Re-work shortcuts

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#847]
* `FlowUiComponentProperties` - remove default shortcuts
*  Keep only EditAction `Enter` shortcut

**Comment by knstvk** [comment]
Open a detail view, change something, then click Cancel:
```
java.lang.NullPointerException
	at io.jmix.flowui.impl.DialogsImpl$OptionDialogBuilderImpl.initKeyCombination(DialogsImpl.java:310)
	at io.jmix.flowui.impl.DialogsImpl$OptionDialogBuilderImpl.open(DialogsImpl.java:289)
	at io.jmix.flowui.view.ViewValidation.showSaveConfirmationDialog(ViewValidation.java:214)
	at io.jmix.flowui.view.StandardDetailView.preventUnsavedChanges(StandardDetailView.java:343)
	at io.jmix.flowui.view.StandardDetailView.onBeforeClose(StandardDetailView.java:74)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:206)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:195)
	at com.vaadin.flow.component.Component.fireEvent(Component.java:378)
	at io.jmix.flowui.view.View.close(View.java:113)
	at io.jmix.flowui.view.View.close(View.java:108)
	at io.jmix.flowui.action.view.DetailCloseAction.execute(DetailCloseAction.java:48)
	at io.jmix.flowui.action.view.ViewAction.actionPerform(ViewAction.java:124)
```
