### ISSUE TITLE
NPE occurs after adding dynamic attribute manually to a table

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#855]
### Description
User has two dynamic attributes. One of them added manually to the usersTable:
```
<column id="+user-category-type"/>
```
Loader contains: `dynamicAttributes="true"`

### Steps to reproduce
1. Download demo project: [demo.zip](https://github.com/jmix-framework/jmix/files/9138932/demo.zip)

2. Launch the app
3. Open User browse.

```
java.lang.NullPointerException
	at io.jmix.security.impl.constraint.SecureOperationsImpl.isEntityAttrUpdatePermitted(SecureOperationsImpl.java:88)
	at io.jmix.security.constraint.EntityAttributeConstraint.applyTo(EntityAttributeConstraint.java:50)
	at io.jmix.security.constraint.EntityAttributeConstraint.applyTo(EntityAttributeConstraint.java:26)
	at io.jmix.core.AccessManager.lambda$applyConstraints$2(AccessManager.java:77)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.jmix.core.AccessManager.applyConstraints(AccessManager.java:76)
	at io.jmix.core.AccessManager.applyRegisteredConstraints(AccessManager.java:86)
	at io.jmix.ui.component.impl.AbstractTable.lambda$getPropertyColumns$6(AbstractTable.java:1581)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.jmix.ui.component.impl.AbstractTable.getPropertyColumns(AbstractTable.java:1588)
	at io.jmix.ui.component.impl.AbstractTable.setItems(AbstractTable.java:1511)
	at io.jmix.ui.component.impl.GroupTableImpl.setItems(GroupTableImpl.java:69)
	at io.jmix.ui.xml.layout.loader.AbstractTableLoader.setupDataContainer(AbstractTableLoader.java:251)
	at io.jmix.ui.xml.layout.loader.AbstractTableLoader.loadTableData(AbstractTableLoader.java:169)
	at io.jmix.ui.xml.layout.loader.AbstractTableLoader.loadComponent(AbstractTableLoader.java:136)
	at io.jmix.ui.xml.layout.loader.GroupTableLoader.loadComponent(GroupTableLoader.java:44)
	at io.jmix.ui.xml.layout.loader.ContainerLoader.loadSubComponents(ContainerLoader.java:36)
	at io.jmix.ui.xml.layout.loader.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:74)
	at io.jmix.ui.xml.layout.loader.WindowLoader.loadComponent(WindowLoader.java:85)
	at io.jmix.ui.sys.ScreensImpl.loadWindowFromXml(ScreensImpl.java:319)
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:204)
	at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:145)
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.createScreen(MenuItemCommands.java:230)
```

### QA Notes
Please, check also that complex tables with embedded, composition properties and generated columns works and security constraints works for tables.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4519-213
IntelliJ version: IntelliJ IDEA 2021.3 (Community Edition)
