### ISSUE TITLE
[Table] StyleProvider and Aggregation result in NPE

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#875]
Case:

1. Add aggregation settings to some table, e.g. users table.
2. Add `StyleProvider`, e.g.:
```
usersTable.addStyleProvider((entity, property) -> "test-style1");
```
3. Open a screen
4. Open a log file

AR:
```
java.lang.IllegalArgumentException: entity or id is null
	at io.jmix.core.common.util.Preconditions.checkNotNullArgument(Preconditions.java:101) ~[jmix-core-1.4.999-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.CollectionContainerImpl.getItemIndex(CollectionContainerImpl.java:126) ~[jmix-ui-1.4.999-SNAPSHOT.jar:na]
	at io.jmix.ui.model.impl.CollectionContainerImpl.getItemOrNull(CollectionContainerImpl.java:120) ~[jmix-ui-1.4.999-SNAPSHOT.jar:na]
	at io.jmix.ui.component.data.table.ContainerTableItems.getItem(ContainerTableItems.java:96) ~[jmix-ui-1.4.999-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.AbstractTable.getGeneratedCellStyle(AbstractTable.java:1340) ~[jmix-ui-1.4.999-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.GroupTableImpl.getGeneratedCellStyle(GroupTableImpl.java:397) ~[jmix-ui-1.4.999-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.AbstractTable.generateCellStyle(AbstractTable.java:3168) ~[jmix-ui-1.4.999-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.AbstractTable$StyleGeneratorAdapter.getStyle(AbstractTable.java:3356) ~[jmix-ui-1.4.999-SNAPSHOT.jar:na]
```

**Comment by reznikova21** [comment]
1.3.999-SNAPSHOT - verified
