### ISSUE TITLE
Maps add-on has jts-core dependency that is incompatible with geotools dependencies

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#908]
### Description

**org.geotools** dependencies defined in `bom.gradle` have transitive dependency:
```
org.locationtech.jts:jts-core:1.16.0
```

**maps** add-on uses **org.geotools** dependencies and at the same time defines:
```
org.locationtech.jts:jts-core:1.17.1
```

It makes incompatible some API that provided by **geotools**. For instance:
```
JTS.transform(polygon, transform);
```
Throws an exception:
```
java.lang.NoSuchMethodError: 'org.locationtech.jts.geom.LineString org.locationtech.jts.geom.Polygon.getExteriorRing()'
	at org.geotools.geometry.jts.GeometryCoordinateSequenceTransformer.transformPolygon(GeometryCoordinateSequenceTransformer.java:284)
	at org.geotools.geometry.jts.GeometryCoordinateSequenceTransformer.transform(GeometryCoordinateSequenceTransformer.java:158)
	at org.geotools.geometry.jts.JTS.transform(JTS.java:450)
```

### QA
1. Check that maps add-on works as expected.
2. Check that no errors in the console of dev tools.

**Comment by Afanasevaa36** [comment]
1.4.999-SNAPSHOT - Verified
