### ISSUE TITLE
Exception when starting the project with BPM and Notifications add-ons

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#912]
Jmix 1.3.1

* Create new project
* Add BPM and Notifications add-ons
* Start the project

AR: Exception in the log

```
2022-08-02 12:13:38.964  WARN 82038 --- [           main] i.j.b.n.BpmNotificationTemplateProvider  : Unexpected exception occurs while parsing notification templates

java.lang.IllegalArgumentException: argument "in" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4829) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.ObjectMapper.createParser(ObjectMapper.java:1264) ~[jackson-databind-2.13.3.jar:2.13.3]
	at io.jmix.bpm.notifications.BpmNotificationTemplateProvider.init(BpmNotificationTemplateProvider.java:52) ~[jmix-bpm-1.3.1.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.20.jar:5.3.20]
...
```

[Forum topic](https://forum.jmix.io/t/java-lang-illegalargumentexception-argument-in-is-null/1752)

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4507-213
IntelliJ version: IntelliJ IDEA 2021.3 (Community Edition)
