### ISSUE TITLE
Redis cache doesn't work with LockManager

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#913]
Jmix 1.3.1

1. Create new project
2. Add Redis dependency:
```
implementation 'org.springframework.boot:spring-boot-starter-data-redis'
```
3. Start Redis, e.g. using Docker:
```
docker run --name redis -p 6379:6379 -d redis
```
4. Start the project
5. Open the User browse screen and try to edit the user

AR: Exception:

```
Caused by: java.lang.IllegalStateException: Cannot convert cache key io.jmix.core.pessimisticlocking.impl.LockManagerImpl$LockKey to String. Please register a suitable Converter via 'RedisCacheConfiguration.configureKeyConverters(...)' or override 'LockKey.toString()'.
	at org.springframework.data.redis.cache.RedisCache.convertKey(RedisCache.java:353) ~[spring-data-redis-2.7.2.jar:2.7.2]
	at org.springframework.data.redis.cache.RedisCache.createCacheKey(RedisCache.java:309) ~[spring-data-redis-2.7.2.jar:2.7.2]
	at org.springframework.data.redis.cache.RedisCache.createAndConvertCacheKey(RedisCache.java:391) ~[spring-data-redis-2.7.2.jar:2.7.2]
	at org.springframework.data.redis.cache.RedisCache.lookup(RedisCache.java:89) ~[spring-data-redis-2.7.2.jar:2.7.2]
	at org.springframework.cache.support.AbstractValueAdaptingCache.get(AbstractValueAdaptingCache.java:65) ~[spring-context-5.3.22.jar:5.3.22]
	at io.jmix.core.pessimisticlocking.impl.LockManagerImpl.lock(LockManagerImpl.java:130) ~[jmix-core-1.3.999-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.PessimisticLockSupport.lock(PessimisticLockSupport.java:58) ~[jmix-ui-1.3.999-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.StandardEditor.setupLock(StandardEditor.java:244) ~[jmix-ui-1.3.999-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.StandardEditor.beforeShow(StandardEditor.java:156) ~[jmix-ui-1.3.999-SNAPSHOT.jar:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-1.3.999-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124) ~[jmix-ui-1.3.999-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:58) ~[jmix-ui-1.3.999-SNAPSHOT.jar:na]
	at io.jmix.ui.sys.ScreensImpl.fireScreenBeforeShowEvent(ScreensImpl.java:1364) ~[jmix-ui-1.3.999-SNAPSHOT.jar:na]
	at io.jmix.ui.sys.ScreensImpl.show(ScreensImpl.java:357) ~[jmix-ui-1.3.999-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.Screen.show(Screen.java:306) ~[jmix-ui-1.3.999-SNAPSHOT.jar:na]
	at io.jmix.ui.action.list.EditAction.execute(EditAction.java:377) ~[jmix-ui-1.3.999-SNAPSHOT.jar:na]
	at io.jmix.ui.action.list.EditAction.actionPerform(EditAction.java:324) ~[jmix-ui-1.3.999-SNAPSHOT.jar:na]
```

See [forum topic](https://forum.jmix.io/t/exception-when-adding-a-redis/1746)

**Comment by MaxKatyshev** [comment]
1.3.999-SNAPSHOT - verified
