### ISSUE TITLE
NPE on starting process if no query is set to dialog parameter of entity type

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#931]
Create a start event with input dialog using BPMN designer in Studio. Add an entity parameter and leave JPQL Query parameter empty as suggested in [Getting Started with BPM](https://docs.jmix.io/jmix/bpm/getting-started.html#creating-start-form) tutorial.

You will get NPE on process start:
```
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221) ~[na:na]
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178) ~[na:na]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at io.jmix.bpm.data.form.FormField.getPropertiesMap(FormField.java:84) ~[jmix-bpm-1.3.1.jar:na]
	at io.jmix.bpmui.screen.dynamicform.DynamicFormFieldComponentsFactoryBean.createEntityField(DynamicFormFieldComponentsFactoryBean.java:182) ~[jmix-bpm-ui-1.3.1.jar:na]
	at io.jmix.bpmui.screen.dynamicform.DynamicFormFieldComponentsFactoryBean.createComponent(DynamicFormFieldComponentsFactoryBean.java:99) ~[jmix-bpm-ui-1.3.1.jar:na]
	at io.jmix.bpmui.screen.dynamicform.DynamicProcessForm.initForm(DynamicProcessForm.java:29) ~[jmix-bpm-ui-1.3.1.jar:na]
	at io.jmix.bpmui.screen.dynamicform.DynamicStartProcessForm.setProcessDefinition(DynamicStartProcessForm.java:45) ~[jmix-bpm-ui-1.3.1.jar:na]
	at io.jmix.bpmui.processform.screencreator.impl.InputDialogProcessFormScreenCreator.createStartProcessScreen(InputDialogProcessFormScreenCreator.java:40) ~[jmix-bpm-ui-1.3.1.jar:na]
	at io.jmix.bpmui.processform.ProcessFormScreensImpl.createStartProcessForm(ProcessFormScreensImpl.java:44) ~[jmix-bpm-ui-1.3.1.jar:na]
	at io.jmix.bpmui.screen.startprocess.StartProcessScreen.onProcessDefinitionsTableStartProcess(StartProcessScreen.java:95) ~[jmix-bpm-ui-1.3.1.jar:na]
```

**Comment by KremnevDmitry** [comment]
The bug is not in the framework
Related to Studio Issue: [JST-3178](https://youtrack.haulmont.com/issue/JST-3178)

**Comment by knstvk** [comment]
I still think there should not be an NPE but a more specific exception describing what's wrong with the process definition.

**Comment by KremnevDmitry** [comment]
> I still think there should not be an NPE but a more specific exception describing what's wrong with the process definition.

Both when building a process with UI BPMN, and with the BPMN studio, the error is no longer thrown

**Comment by knstvk** [comment]
> Both when building a process with UI BPMN, and with the BPMN studio, the error is no longer thrown

That's not the point. Look at the code. What if any other property is null for some reason? User will get an obscure NPE and won't have any clue for the cause.

**Comment by KremnevDmitry** [comment]
> > Both when building a process with UI BPMN, and with the BPMN studio, the error is no longer thrown
> 
> That's not the point. Look at the code. What if any other property is null for some reason? User will get an obscure NPE and won't have any clue for the cause.

Clearly, I will research the problem in more detail and add error handlers.

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4604-222
IntelliJ version: IntelliJ IDEA 2022.2.1 (Ultimate Edition)
