### ISSUE TITLE
User obtained through CurrentAuthentication has not all attributes loaded 

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#948]
Try to get the current user in a service method invoked through [REST Services API](https://docs.jmix.io/jmix/rest/business-logic.html#using-the-services-api): you will get the user entity with only basic attributes of UserDetails loaded.

It prevents from using User attributes in security constraints and other queries through parameters like `:current_user_myProp` .

**Comment by gorbunkov** [comment]
Since 1.4 user entity instance is reloaded when it is obtained using `CurrentAuthentication.getUser()` or `CurrentUserSubstitution.getEffectiveUser()`.

New application property has been introduced:

```properties
jmix.core.current-authentication-user-reload-enabled=true
```

Setting this property to `false` will disable user reloading.

**Comment by gorbunkov** [comment]
Application fails if multitenancy add-on is added

```
java.lang.StackOverflowError
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:353)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:218)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider$1.resolveCandidate(DefaultListableBeanFactory.java:2007)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getObject(DefaultListableBeanFactory.java:2010)
    at io.jmix.core.impl.UnconstrainedDataManagerImpl.load(UnconstrainedDataManagerImpl.java:285)
    at io.jmix.core.security.impl.CurrentAuthenticationUserLoaderImpl.reloadUser(CurrentAuthenticationUserLoaderImpl.java:49)
    at io.jmix.core.security.impl.CurrentAuthenticationImpl.getUser(CurrentAuthenticationImpl.java:70)
    at io.jmix.multitenancy.core.impl.TenantProviderImpl.getCurrentUserTenantId(TenantProviderImpl.java:47)
    at io.jmix.multitenancy.data.HasTenantAdditionalCriteriaProvider.getCriteriaParameters(HasTenantAdditionalCriteriaProvider.java:71)
    at io.jmix.eclipselink.impl.JmixEntityManager.setAdditionalProperties(JmixEntityManager.java:602)
    at io.jmix.eclipselink.impl.JmixEntityManager.<init>(JmixEntityManager.java:87)
    at io.jmix.eclipselink.impl.JmixEntityManagerFactory.createJmixEntityManager(JmixEntityManagerFactory.java:38)
    at io.jmix.eclipselink.impl.JmixEntityManagerFactory.createEntityManager(JmixEntityManagerFactory.java:43)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.createNativeEntityManager(AbstractEntityManagerFactoryBean.java:585)
    at jdk.internal.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.invokeProxyMethod(AbstractEntityManagerFactoryBean.java:487)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean$ManagedEntityManagerFactoryInvocationHandler.invoke(AbstractEntityManagerFactoryBean.java:734)
    at com.sun.proxy.$Proxy170.createNativeEntityManager(Unknown Source)
    at org.springframework.orm.jpa.JpaTransactionManager.createEntityManagerForTransaction(JpaTransactionManager.java:485)
    at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:410)
    at io.jmix.eclipselink.impl.JmixEclipselinkTransactionManager.doBegin(JmixEclipselinkTransactionManager.java:34)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
    at io.jmix.eclipselink.impl.JpaDataStore.beginLoadTransaction(JpaDataStore.java:369)
    at io.jmix.core.datastore.AbstractDataStore.load(AbstractDataStore.java:84)
    at io.jmix.core.impl.UnconstrainedDataManagerImpl.load(UnconstrainedDataManagerImpl.java:97)
    at io.jmix.core.FluentLoader$ById.optional(FluentLoader.java:197)
    at io.jmix.core.security.impl.CurrentAuthenticationUserLoaderImpl.reloadUser(CurrentAuthenticationUserLoaderImpl.java:49)
    at io.jmix.core.security.impl.CurrentAuthenticationImpl.getUser(CurrentAuthenticationImpl.java:70)
    at io.jmix.multitenancy.core.impl.TenantProviderImpl.getCurrentUserTenantId(TenantProviderImpl.java:47)
    at io.jmix.multitenancy.data.HasTenantAdditionalCriteriaProvider.getCriteriaParameters(HasTenantAdditionalCriteriaProvider.java:71)
    at io.jmix.eclipselink.impl.JmixEntityManager.setAdditionalProperties(JmixEntityManager.java:602)
    at io.jmix.eclipselink.impl.JmixEntityManager.<init>(JmixEntityManager.java:87)
    at io.jmix.eclipselink.impl.JmixEntityManagerFactory.createJmixEntityManager(JmixEntityManagerFactory.java:38)
    at io.jmix.eclipselink.impl.JmixEntityManagerFactory.createEntityManager(JmixEntityManagerFactory.java:43)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.createNativeEntityManager(AbstractEntityManagerFactoryBean.java:585)
    at jdk.internal.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.invokeProxyMethod(AbstractEntityManagerFactoryBean.java:487)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean$ManagedEntityManagerFactoryInvocationHandler.invoke(AbstractEntityManagerFactoryBean.java:734)
    at com.sun.proxy.$Proxy170.createNativeEntityManager(Unknown Source)
    at org.springframework.orm.jpa.JpaTransactionManager.createEntityManagerForTransaction(JpaTransactionManager.java:485)
    at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:410)
    at io.jmix.eclipselink.impl.JmixEclipselinkTransactionManager.doBegin(JmixEclipselinkTransactionManager.java:34)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
    at io.jmix.eclipselink.impl.JpaDataStore.beginLoadTransaction(JpaDataStore.java:369)
    at io.jmix.core.datastore.AbstractDataStore.load(AbstractDataStore.java:84)
    at io.jmix.core.impl.UnconstrainedDataManagerImpl.load(UnconstrainedDataManagerImpl.java:97)
    
```

**Comment by MaxKatyshev** [comment]
Jmix version: 1.4.999-SNAPSHOT - verified
