### ISSUE TITLE
Error when exporting/importing an entity via Entity Inspector if the group and HTML field is not filled in

### ISSUE THREAD

**Issue by Afanasevaa36** [jmix-framework/jmix#950]
Jmix version: 1.3.2
Jmix Studio plugin version: 1.4.SNAPSHOT4520-213
IntelliJ version: IntelliJ IDEA 2022.2 (Ultimate Edition)

See [topic](https://forum.jmix.ru/t/oshibka-pri-eksporte-importe-sushhnosti-s-pomoshhyu-entityinspector/540).
1. Install [ForumErrorGroup.zip](https://github.com/jmix-framework/jmix/files/9348469/ForumErrorGroup.zip).
2. Run project.
3. Log In admin/admin.
4. Administration>Entity Inspector>Design email template.
5. Click TestNotGroup and Export as JSON.
6. Import the downloaded file.
**ER**:
1 entities imported.
**AR**:
```
ava.lang.NullPointerException: null
	at io.jmix.datatoolsui.screen.entityinspector.EntityInspectorBrowser.createEntityImportPlan(EntityInspectorBrowser.java:529) ~[jmix-datatools-ui-1.3.2.jar:na]
	at io.jmix.datatoolsui.screen.entityinspector.EntityInspectorBrowser.lambda$createButtonsPanel$5(EntityInspectorBrowser.java:387) ~[jmix-datatools-ui-1.3.2.jar:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-1.3.2.jar:na]
	at io.jmix.ui.component.impl.AbstractComponent.publish(AbstractComponent.java:85) ~[jmix-ui-1.3.2.jar:na]
	at io.jmix.ui.component.impl.AbstractSingleFileUploadField.fireFileUploadSucceed(AbstractSingleFileUploadField.java:314) ~[jmix-ui-1.3.2.jar:na]
	at io.jmix.ui.component.impl.AbstractSingleFileUploadField.onUploadSucceeded(AbstractSingleFileUploadField.java:147) ~[jmix-ui-1.3.2.jar:na]
	at io.jmix.ui.component.impl.FileUploadFieldImpl.onUploadSucceeded(FileUploadFieldImpl.java:85) ~[jmix-ui-1.3.2.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:709) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:399) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:363) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1216) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	at io.jmix.ui.widget.JmixFileUpload.fireUploadSuccess(JmixFileUpload.java:492) ~[jmix-ui-1.3.2.jar:na]

```
7.Click TestNotHTML and Export as JSON.
8. Import the downloaded file.
**ER**:
1 entities imported.
**AR**:
```
java.lang.IllegalStateException: Cannot get unfetched attribute [html] from object io.jmix.emailtemplates.entity.JsonEmailTemplate-dc6c559d-4d09-1eba-3126-5616e563ee32 [managed]
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:3029) ~[org.eclipse.persistence.jpa-2.7.9-6-jmix.jar:na]
	at io.jmix.emailtemplates.entity.EmailTemplate._persistence_checkFetched(EmailTemplate.java) ~[jmix-emailtemplates-1.3.2.jar:na]
	at io.jmix.emailtemplates.entity.JsonEmailTemplate._persistence_get_html(JsonEmailTemplate.java) ~[jmix-emailtemplates-1.3.2.jar:na]
	at io.jmix.emailtemplates.entity.JsonEmailTemplate.getHtml(JsonEmailTemplate.java:52) ~[jmix-emailtemplates-1.3.2.jar:na]
	at io.jmix.emailtemplates.impl.TemplateConverterImpl.getHtmlReportTemplate(TemplateConverterImpl.java:65) ~[jmix-emailtemplates-1.3.2.jar:na]
	at io.jmix.emailtemplates.impl.TemplateConverterImpl.convertToReport(TemplateConverterImpl.java:59) ~[jmix-emailtemplates-1.3.2.jar:na]
	at io.jmix.emailtemplates.entity.listener.JsonEmailTemplateDetachListener.onBeforeDetach(JsonEmailTemplateDetachListener.java:46) ~[jmix-emailtemplates-1.3.2.jar:na]
	at io.jmix.emailtemplates.entity.listener.JsonEmailTemplateDetachListener.onBeforeDetach(JsonEmailTemplateDetachListener.java:32) ~[jmix-emailtemplates-1.3.2.jar:na]
	at io.jmix.data.impl.EntityListenerManager.fireListener(EntityListenerManager.java:227) ~[jmix-data-1.3.2.jar:na]
	at io.jmix.eclipselink.impl.EclipselinkPersistenceSupport.fireBeforeDetachEntityListener(EclipselinkPersistenceSupport.java:243) ~[jmix-eclipselink-1.3.2.jar:na]
	at io.jmix.eclipselink.impl.EclipselinkPersistenceSupport.detach(EclipselinkPersistenceSupport.java:326) ~[jmix-eclipselink-1.3.2.jar:na]
	at io.jmix.eclipselink.impl.JmixEntityManager.detach(JmixEntityManager.java:245) ~[jmix-eclipselink-1.3.2.jar:na]
	at io.jmix.eclipselink.impl.JpaDataStore.detachEntity(JpaDataStore.java:593) ~[jmix-eclipselink-1.3.2.jar:na]
	at io.jmix.eclipselink.impl.JpaDataStore.beforeLoadTransactionCommit(JpaDataStore.java:377) ~[jmix-eclipselink-1.3.2.jar:na]
	at io.jmix.core.datastore.AbstractDataStore.load(AbstractDataStore.java:93) ~[jmix-core-1.3.2.jar:na]

```

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT - Verified
