### ISSUE TITLE
InstantiationException, when creating Email template via Entity Inspector

### ISSUE THREAD

**Issue by Afanasevaa36** [jmix-framework/jmix#951]
Jmix version: 1.3.2
Jmix Studio plugin version: 1.4.SNAPSHOT4520-213
IntelliJ version: IntelliJ IDEA 2022.2 (Ultimate Edition)

1. Create project.
2. Add addon Email Template.
3. Run project.
4. Log In admin/admin.
5. Click Administration>Entity Inspector>Email template>Create.
**AR**:
```
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:157) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:442) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:407) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:275) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:83) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1636) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:465) ~[vaadin-server-8.14.1-1-jmix.jar:8.14.1-1-jmix]
	
```

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT - Verified
