### ISSUE TITLE
Tenant field is not set for report

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#969]
see [forum topic](https://forum.jmix.ru/t/sozdanie-otchetov-s-tenantami/553/4)

**Environment**
Jmix version: 1.3.2

**Steps to reproduce**

1. Run test project [reports_and_tenants_pg.zip](https://github.com/jmix-framework/jmix/files/9402033/reports_and_tenants_pg.zip))
2. Open Tenants > Create tenant1
3. Open Users > Create User1 with tenant=tenant1
4. Add full access role to User1
5. Logout, log in using "tenant1|User1"
6. Open Reports > Report groups > Create group1
7. Open Reports > Reports > Create > New
    -   Name = report1
    -   Group = group1
    -   Default template = (Create template > load empty template [empty.xlsx](https://github.com/jmix-framework/jmix/files/9402037/empty.xlsx))
8. Click Save

AR: 
```
java.lang.IllegalStateException: No results
	at io.jmix.core.FluentLoader$ById.one(FluentLoader.java:216)
	at io.jmix.reports.impl.ReportsPersistenceImpl.save(ReportsPersistenceImpl.java:89)
	at io.jmix.reportsui.screen.report.edit.ReportEditor.commitDelegate(ReportEditor.java:220)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.jmix.ui.sys.delegate.InstalledFunction.apply(InstalledFunction.java:37)
	at io.jmix.ui.model.impl.DataContextImpl.commitToDataManager(DataContextImpl.java:713)
	at io.jmix.ui.model.impl.DataContextImpl.performCommit(DataContextImpl.java:693)
	at io.jmix.ui.model.impl.DataContextImpl.commit(DataContextImpl.java:654)
...
```
*See full stacktrace in file [stacktrace.txt](https://github.com/jmix-framework/jmix/files/9401901/stacktrace.txt)*

9. Close dialog, open Reports > Reports
  AR: report "report1" is not visible

10. Logout, log in with admin
11. Open Reports > Reports
  AR: report "report1" is visible

In database, group has tenant:
![image](https://user-images.githubusercontent.com/73226373/186145106-3c553da5-3ee9-47aa-9d65-877edebf0712.png)
But report hasn't:
![image](https://user-images.githubusercontent.com/73226373/186145650-9e3f33aa-9699-408c-a5e6-e08a3f1a9e98.png)

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT - Verified
