### ISSUE TITLE
Security UI improvements

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#971]
1. Custom filer should use `flowBox` for filter fields, so they are displayed on the next line if nit enough space
<img width="600" alt="Screenshot 2022-08-24 at 11 35 49" src="https://user-images.githubusercontent.com/6077149/186359352-b2899921-45ec-4bec-bfd4-8200ab404f1c.png">

2. Not all columns values have localization, e.g. Type, Action, Source
<img width="1251" alt="Screenshot 2022-08-22 at 11 38 28" src="https://user-images.githubusercontent.com/6077149/186359646-fe0a199b-09fe-4400-976f-44fa0f36c363.png">
<img width="1250" alt="Screenshot 2022-08-22 at 11 38 14" src="https://user-images.githubusercontent.com/6077149/186359665-05123e29-057d-422b-beb4-1fe7251adfdb.png">

3. (Code) **Create Entity resource policy** - actions must be presented with `CheckBoxGroup` instead of separate `CheckBox`es
<img width="614" alt="Screenshot 2022-08-24 at 11 41 01" src="https://user-images.githubusercontent.com/6077149/186360180-41dd106b-452b-4f47-9a51-502781a7d84f.png">

4. All **Create** policy screens have to check unsaved changes. Currently only Specific Policy and GraphQL Policy do that.
5. GraphQL Policy is **edited** (not created) with the DefaultPolicyEditor instead of its own
6. **Row-level policy** - Dialog buttons must be aligned to the left as all dialog buttons do. Documentation link can be aligned to the right. Also it's worth implementing **docs link** using the `Link` component instead of `LinkButton` with programmatic page opening
<img width="782" alt="Screenshot 2022-08-24 at 11 47 58" src="https://user-images.githubusercontent.com/6077149/186361613-dcdde5e9-b011-4e73-86e6-8b1b17ac4007.png">

**Comment by Flaurite** [comment]
There should be fix for NPE:
```
aused by: java.lang.NullPointerException: null
	at io.jmix.securityui.screen.resourcepolicy.EntityResourcePolicyModelCreate.getPolicyActions(EntityResourcePolicyModelCreate.java:91) ~[jmix-security-ui-1.5.999-SNAPSHOT.jar:na]
	at io.jmix.securityui.screen.resourcepolicy.EntityResourcePolicyModelCreate.validateScreen(EntityResourcePolicyModelCreate.java:128) ~[jmix-security-ui-1.5.999-SNAPSHOT.jar:na]
```

Steps to reproduce:
1. Resource Role ->create new one -> create Entity Policy
2. Click OK without selecting anything

**Comment by rusiaikinat** [comment]
Reopen
TC:  

- Open Resource role

Create Resource policies:
1) Create - Menu policy - Set Resource - After select null string resource
AR: NullPointerException: Cannot invoke "String.equals(Object)" because "id" is null

```
 java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "id" is null
at io.jmix.ui.menu.MenuConfig.findItem(MenuConfig.java:563)
at io.jmix.securityui.model.DefaultResourcePolicyGroupResolver.resolvePolicyGroupForMenuPolicy(DefaultResourcePolicyGroupResolver.java:174)
at io.jmix.securityui.model.DefaultResourcePolicyGroupResolver.resolvePolicyGroup(DefaultResourcePolicyGroupResolver.java:120)
...
```


2) Create - Screen policy - Set Resource - After select null string resource
AR: NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
...
```
