### ISSUE TITLE
Java serialization doesn't work correctly for JPA entities and lazy loading

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#986]
Jmix version: 1.3.2

1. Serialize some jmix entity with a reference to another entity, e.g. User with Department reference.
1. Deserialize the entity.
1. Try to get the department from the deserialized user.

ER: the department reference will be loaded by lazy-loading mechanism

AR: the exception:

```
java.lang.NullPointerException
	at io.jmix.eclipselink.impl.lazyloading.AbstractValueHolder.getMetadata(AbstractValueHolder.java:355)
	at io.jmix.eclipselink.impl.lazyloading.SingleValueOwningPropertyHolder.loadValue(SingleValueOwningPropertyHolder.java:52)
	at io.jmix.eclipselink.impl.lazyloading.AbstractValueHolder.getValue(AbstractValueHolder.java:275)
	at com.company.entityserializationerror.entity.User._persistence_get_department(User.java)
	at com.company.entityserializationerror.entity.User.getDepartment(User.java:68)
	at com.company.entityserializationerror.EntitySerializationErrorApplicationTests.testEntitySerialization(EntitySerializationErrorApplicationTests.java:75)
```

See `EntitySerializationErrorApplicationTests.java` in sample project: [entity-serialization-error.zip](https://github.com/jmix-framework/jmix/files/9469949/entity-serialization-error.zip)

```java
    @Test
    void testEntitySerialization() throws IOException, ClassNotFoundException {
        systemAuthenticator.begin();
        try {
            User initialUser = dataManager.load(Id.of(user)).one();

            ByteArrayOutputStream bout = new ByteArrayOutputStream();
            ObjectOutputStream oos = new ObjectOutputStream(bout);
            oos.writeObject(initialUser);

            byte[] bytes = bout.toByteArray();

            ObjectInputStream ois = new ObjectInputStream(new ByteArrayInputStream(bytes));
            User deserializedUser = (User) ois.readObject();

            Department initialDepartment = initialUser.getDepartment();
            assertEquals("IT", initialDepartment.getName());

            //we'll get an exception because deserialized lazy-loading value holder for department field is invalid
            Department deserializedDepartment = deserializedUser.getDepartment();
            assertEquals("IT", deserializedDepartment.getName());

            String firstName = deserializedUser.getFirstName();
            assertEquals(initialUser.getFirstName(), firstName);
        } finally {
            systemAuthenticator.end();
        }
    }
```

**Comment by gorbunkov** [comment]
We should try using the `StandardSerialization` bean for entity serialization. If it works fine in the test then the issue should be closed.
