### ISSUE TITLE
Liquibase update error for MySQL

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#998]
1. Create new project with Jmix version 1.2.4
1. Change database type to MySQL
1. Add email, bpm and quartz addon
1. Recreate database using studio action
1. Update project to Jmix 1.3.2
1. Update database using studio action (update will be successful)
1. Run the project

ER: project started successfully

AR: projects fails with exception:

```
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     2 change sets check sum
          io/jmix/bpm/liquibase/changelog/002-bpm.xml::4::bpm was: 8:6c73ba7a5e29908be1a981487560831f but is now: 8:01738e7d714fd8b2b2b00560e52d7edd
          io/jmix/email/liquibase/changelog/001-email.xml::6::email was: 8:422728a555a404f36e3bf3c711ae6f12 but is now: 8:79ebd7ffe2e096e7ecee73ee5522ab39

	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:296) ~[liquibase-core-4.11.0.jar:na]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:231) ~[liquibase-core-4.11.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.11.0.jar:na]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.11.0.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.11.0.jar:na]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.11.0.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:2405) ~[liquibase-core-4.11.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:211) ~[liquibase-core-4.11.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:197) ~[liquibase-core-4.11.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314) ~[liquibase-core-4.11.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269) ~[liquibase-core-4.11.0.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.22.jar:5.3.22]
	... 18 common frames omitted
```

However if you will not invoke the database update operation from Studio, but will run the application with `./gradlew bootRun` command, the database will be updated successfully.

It seems that liquibase inside studio generates different checksum for the changeset than the liquibase inside the running application.

See [forum topic](https://forum.jmix.io/t/liquibase-validationfailedexception-when-upgrading-to-1-3-1-from-1-2-4/1745/8).

The issue relates to https://github.com/jmix-framework/jmix/issues/906

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.2
Jmix Studio plugin version: 1.3.SNAPSHOT4660-213
IntelliJ version: IntelliJ IDEA 2021.3.3 (Community Edition)

AR: projects fails with exception. Please look into attached file
[task bootRun failed.txt](https://github.com/jmix-framework/jmix/files/9732120/task.bootRun.failed.txt)

test project 
[seveteenonly.zip](https://github.com/jmix-framework/jmix/files/9732124/seveteenonly.zip)

**Comment by gorbunkov** [comment]
@konyashkina 
Have you tried the latest Jmix version (1.3.3) and the latest Studio plugin release version as I asked in the previous comment?

**Comment by gorbunkov** [comment]
The error from the attached log file seems to be related not to the migration from one Jmix version to another:

```
java.sql.SQLSyntaxErrorException: Table 'only17.ACT_GE_PROPERTY' doesn't exist
```

This message means that Flowable tables haven't been created at all

@konyashkina Please try to run the application after creating the new project on Jmix 1.2.4 and adding the add-ons. Ensure that it works. Only after that do the migration to Jmix 1.3

**Comment by konyashkina** [comment]
Blocked by issue #1085

**Comment by konyashkina** [comment]
Re-tested on 
Jmix version: 1.3.3
Jmix Studio plugin version: 1.3.7-213
IntelliJ version: IntelliJ IDEA 2021.3.3 (Community Edition)
with `&nullDatabaseMeansCurrent=true `to the connection params in Data Store settings 
and all mentioned addons: BPM, Email and Quartz.

Project started successfully.
